bufferapp/buffer-publish

README.md

After flipping the switch to make this a public repo, we felt it would be nice to explicitly share that this is not released for other's use outside Buffer. We may change this in the future, but think it would be good to put this in there early!
@hharnisc what do you think?! 😄

Add explicit Buffer copyright

---

buffer-publish/templates/ingress.yaml
buffer-publish/values.yaml

Follow the camelcase

---

packages/sent/middleware.js
packages/sent/middleware.test.js
packages/sent/package.json
packages/server/rpc/index.js
packages/server/rpc/sentPosts/index.js

_This repo is CI/CD enabled and staging deployment should be available at https://<branch_name>.publish.buffer.com :smile:_

sent updates data!

---

packages/server/rpc/index.js
packages/server/rpc/profileSettings/index.js
packages/settings/middleware.js
packages/settings/middleware.test.js
packages/settings/package.json

Adds data fetching for the settings package :) Data transformation in separate PR
_This repo is CI/CD enabled and staging deployment should be available at https://<branch_name>.publish.buffer.com :smile:_

set up fetching for settings package yay!

---

packages/login/index.js
packages/login/middleware.js
packages/login/reducer.js
packages/login/reducer.test.js
packages/web/__snapshots__/snapshot.test.js.snap
packages/web/components/App/index.jsx
packages/web/components/DefaultPage/index.jsx

Show a default page when you're not logged in.
Appears for a few seconds when you have a cookie and we're fetching profile data, etc. Will improve UX in future PRs. (Login and loading state related ones.)
https://default-page.publish.buffer.com

[WIP] Show a default page

---

packages/components/LinkStateless/index.jsx
packages/components/__snapshots__/snapshot.test.js.snap
packages/profile-sidebar/__snapshots__/snapshot.test.js.snap
packages/settings/__snapshots__/snapshot.test.js.snap
packages/shared-components/Tab/index.jsx
packages/shared-components/Tabs/index.jsx
packages/shared-components/__snapshots__/snapshot.test.js.snap
packages/tabs/__snapshots__/snapshot.test.js.snap
packages/web/__snapshots__/snapshot.test.js.snap
packages/web/components/ProfilePage/index.jsx

Just a quick tweak to the tab styling to keep it more inline with the Invision/mockup.

Fix tab style ✨

---

packages/login/middleware.js

Use a different cookie domain locally so it doesn't conflict with the one on prod.
Just a quick tweak until we start managing cookies/sessions fully on the server.

Use a different cookie locally 🍪

---

packages/app-sidebar/__snapshots__/snapshot.test.js.snap
packages/app-sidebar/components/PopoverButton/index.jsx
packages/app-sidebar/components/PopoverMenu/index.jsx
packages/server/lib/controller.js
packages/web/__snapshots__/snapshot.test.js.snap

Fix the popover menus in Firefox.
Also added keyboard support to popover menus using roving tabIndex! :)
https://www.w3.org/TR/wai-aria-practices-1.1/#kbd_roving_tabindex

Fix app-sidebar buttons in Firefox + Improve a11y

---

packages/queue/components/QueuedPosts/index.jsx
packages/queue/index.js
packages/shared-components/EmptyState/index.jsx
packages/shared-components/EmptyState/story.jsx
packages/shared-components/__snapshots__/snapshot.test.js.snap
packages/shared-components/index.js

Adds a generic empty queue state :)
cc @hamstu 

Queue empty state

---

packages/profile-sidebar/__snapshots__/snapshot.test.js.snap
packages/profile-sidebar/components/ProfileListItem/index.jsx
packages/profile-sidebar/components/ProfileSidebar/index.jsx
packages/queue/components/QueuedPosts/story.jsx
packages/queue/index.test.jsx
packages/server/index.html
packages/web/__snapshots__/snapshot.test.js.snap

* Ensure the height of the profile sidebar is 100% 
* Hide scrollbars to keep things clean
* Update to colors/spacing and style in profile-sidebar

Fix profile sidebar height in Safari + style tweaks 🌟

---

packages/profile-sidebar/components/ProfileBadge/index.jsx
packages/queue/components/QueuedPosts/index.jsx
packages/sent/__snapshots__/snapshot.test.js.snap
packages/sent/components/SentPosts/index.jsx
packages/sent/components/SentPosts/story.jsx
packages/sent/index.test.jsx
packages/shared-components/EmptyState/index.jsx
packages/shared-components/EmptyState/story.jsx
packages/shared-components/__snapshots__/snapshot.test.js.snap

Just added dimensions so images scale correctly on Retina. And adjusted spacing a a bit.

Style tweaks to queue empty state

---

Dockerfile.development
packages/profile-sidebar/__snapshots__/snapshot.test.js.snap
packages/profile-sidebar/components/ProfileSidebar/index.jsx
packages/queue/__snapshots__/snapshot.test.js.snap
packages/queue/components/QueuedPosts/index.jsx
packages/sent/components/SentPosts/index.jsx
packages/server/index.html
packages/server/index.js
packages/shared-components/ScrollableContainer/index.jsx
packages/shared-components/index.js
packages/web/__snapshots__/snapshot.test.js.snap
packages/web/components/ProfilePage/index.jsx
packages/web/package.json

* Move the scroll functionality into a separate component
* Fix style for 'loading more...'
* Style scrollbars in webkit

📜 Scroll to top when changing tabs, scroll tweaks, etc.

---

packages/app-sidebar/components/AppSidebar/index.jsx
packages/app-sidebar/components/PopoverButton/index.jsx

Until now the Reply and Analyze links in the app sidebar didn't do anything. Now they do!

Add links to app sidebar! 🔗 ➕

---

packages/web/components/ProfilePage/index.jsx
packages/web/components/ProfilePage/story.jsx

Fixes a bug with infinite loading introduced in #116. 

Fix infinite loading  \∞/

---

packages/app-sidebar/__snapshots__/snapshot.test.js.snap
packages/app-sidebar/components/AppSidebar/index.jsx
packages/app-sidebar/components/UserAvatar/index.jsx
packages/utils/userParser.js

Completes [this flow task.](https://app.getflow.com/organizations/369191/teams/339227/tasks/25545991)
Remove:
In favor of:

Use a generic avatar

---

packages/components/style/color.js

Add "bali hai" color to @bufferapp/components package

---

packages/profile-sidebar/components/LoadingProfileListItem/index.jsx
packages/profile-sidebar/components/ProfileListItem/index.jsx
packages/profile-sidebar/components/ProfileSidebar/index.jsx
packages/profile-sidebar/index.js
packages/profile-sidebar/reducer.js
packages/profile-sidebar/reducer.test.js
packages/server/index.html
packages/web/__snapshots__/snapshot.test.js.snap
packages/web/components/DefaultPage/index.jsx

Resolves [this task in Flow](https://app.getflow.com/organizations/369191/teams/339227/tasks/26146392) as well as adding some polish to the UI with loading animation. 💅 

Profile sidebar loading ✨

---

packages/server/webpack.config.js

Fixing up an error in webpack bundling that showed up yesterday at about 10 AM UTC. 
Full background details are here -> https://paper.dropbox.com/doc/Plan-for-webpack-config-error-of-Buffer-Publish-gRibh8o1jnrPGMFMMJEGl#:uid=539565976936751064627124&h2=Background:
While this works and things seem to be working fine, I'm not well versed in the nuances of `webpack` bundling and would love to get some eyes on this to see if I have broken anything in the background. 
https://task-fix-webpack-config-error-publish.dev.buffer.com

Fixing webpack config error

---

packages/app-sidebar/__snapshots__/snapshot.test.js.snap
packages/app-sidebar/components/AppSidebar/index.jsx
yarn.lock

Reverts bufferapp/buffer-publish#213. Looks like I messed something up and it causes the web page to download when going to publish.buffer.com. Oops!

Revert "Task/remove my account sidebar"

---

packages/app-switcher/components/AppSwitcher/index.jsx
packages/app-switcher/index.js
packages/app-switcher/middleware.js
packages/app-switcher/package.json
packages/app-switcher/reducer.js
packages/notifications/__snapshots__/snapshot.test.js.snap
packages/notifications/components/Notifications/index.jsx
packages/server/rpc/index.js
packages/server/rpc/sendFeedback/index.js
packages/store/index.js
packages/store/package.json
packages/store/reducers.js
packages/web/__snapshots__/snapshot.test.js.snap
packages/web/components/App/index.jsx
packages/web/package.json

For [this task in flow](https://beta.getflow.com/organizations/369191/teams/339227/tasks/28351357).
Depends on a new `/1/publish/feedback.json` API which is introduced here: https://github.com/bufferapp/buffer-web/pull/14419

Add app switcher and beta feedback modal 🔂

---

packages/app-switcher/components/AppSwitcher/index.jsx
packages/app-switcher/middleware.js
packages/app-switcher/reducer.js
packages/beta-redirect/components/EnsurePublishBetaUser/index.jsx
packages/beta-redirect/index.js
packages/beta-redirect/middleware.js
packages/beta-redirect/package.json
packages/beta-redirect/reducer.js
packages/queue/__snapshots__/snapshot.test.js.snap
packages/queue/components/QueuedPosts/index.jsx
packages/queue/index.js
packages/sent/package.json
packages/server/index.html
packages/server/index.js
packages/server/rpc/index.js
packages/server/rpc/savePublishBetaRedirect/index.js
packages/shared-components/BufferLoading/index.jsx
packages/shared-components/BufferLoading/story.jsx
packages/shared-components/__snapshots__/snapshot.test.js.snap
packages/shared-components/index.js
packages/store/index.js
packages/store/package.json
packages/store/reducers.js
packages/web/__snapshots__/snapshot.test.js.snap
packages/web/components/App/index.jsx
packages/web/package.json

Adds a component high up in the chain that prevents anything from showing until we know the user has [the correct feature flip for Publish](https://paper.dropbox.com/doc/Onboarding-for-Publish-Beta-oDdREMXsLhM6OSFJPetIA).
If they don't have the feature we send them back to classic Buffer. &nbsp;&nbsp;  _Be gone user! 👊🏻_
* [Redirect user to Buffer web if they go to Publish but don't have feature flip](https://beta.getflow.com/organizations/369191/teams/339227/tasks/28351518)
* [If Tester goes to Publish, remember that for next time](https://beta.getflow.com/organizations/369191/teams/339227/tasks/28351518)
---
* This PR also moves the app switcher to the top right of the screen.
* Also adds a dope new loading animation! ✨ 
Depends on https://github.com/bufferapp/buffer-web/pull/14455 …

Publish Beta Redirects 🔂 👊🏻

---

packages/queue/package.json

Use the latest composer version (which has changes so it actually works in Publish!).

Use latest composer version 🆙

---

yarn.lock

Need the lock file too! (Oops) 🙆‍♂️

Update lock file 🔒 ✨

---

packages/queue/components/MiniCalendar/index.jsx

Adds in handling of post data in the calendar ui, using spoof data for now.
Makes some style tweaks

Mini Calendar updates: spoof data & styling

---

packages/app-sidebar/components/AppSidebar/index.jsx

To make the Publish button work in other products like Reply or Analyze :)

Update App Sidebar so that the Publish button links to publish instead of "/"

---

README.md

Make our documentation better (better `README.md` file.)
👉  View it here: https://github.com/bufferapp/buffer-publish/blob/cd5a5556a1ab8f6f78b97fd5f3e3be47aeafb5d4/README.md
This is a work in progress. More things to add:

[WIP] Improve Documentation ✨ 📖

---

README.md

Hey @hamstu! I'm not 100% sure if we need the login service as well so I wanted to ask you first. Please, feel free to merge the change if it's ok.

Update README.md to add login as a necessary service to work on the project

---

package.json
packages/app-switcher/components/AppSwitcher/index.jsx
packages/server/index.html
yarn.lock

* Fix font size for the app switcher
* Add npm `postinstall` to ensure that the correct gRPC binary is installed for the Docker container
* Change `<title>`

Fix app switcher and add `postinstall` script

---

packages/modals/components/AppModals/__snapshots__/index.test.jsx.snap
packages/modals/components/AppModals/index.test.jsx
packages/modals/index.js
packages/modals/index.test.js
packages/queue/components/ComposerWrapper/index.jsx
packages/queue/package.json
yarn.lock

Just a bit o' code to catch the new 'event' from the composer when the user hits the 'See paid plans' button.
⭐️ See https://github.com/bufferapp/buffer-composer/pull/67 for the deets 

Show upgrade modal when queue limit is hit from composer

---

packages/edit-email/.babelrc
packages/edit-email/.storybook/addons.js
packages/edit-email/.storybook/config.js
packages/edit-email/.storybook/preview-head.html
packages/edit-email/.storybook/webpack.config.js
packages/edit-email/README.md
packages/edit-email/__snapshots__/snapshot.test.js.snap
packages/edit-email/components/EditEmail/index.jsx
packages/edit-email/components/EditEmail/story.jsx
packages/edit-email/components/Modal/index.jsx
packages/edit-email/components/Modal/story.jsx
packages/edit-email/index.js
packages/edit-email/index.test.jsx
packages/edit-email/middleware.js
packages/edit-email/middleware.test.js
packages/edit-email/package.json
packages/edit-email/reducer.js
packages/edit-email/reducer.test.js
packages/edit-email/snapshot.test.js
packages/preferences/components/Preferences/index.jsx
packages/server/rpc/index.js
packages/server/rpc/updateEmail/index.js
packages/server/rpc/updateEmail/index.test.js
packages/store/index.js
packages/store/package.json
packages/store/reducers.js
yarn.lock

Allow users to change their email address on Publish.
I've created a `modal` component in the package and I'm managing it's state with the `edit-email` reducer because it's state and "user flow" is purely tied to this component. If the modal was to be triggered through different app events (like the upgrade modal) it'd would have been moved elsewhere :)

[PUB-375] Add edit email package

---

packages/upgrade-modal/__snapshots__/snapshot.test.js.snap
packages/upgrade-modal/components/UpgradeModal/index.jsx

Change Upgrade Modal styles to fit smaller screens/ mobile.
Task: [PUB-359](https://buffer.atlassian.net/browse/PUB-359)

[PUB-359] Make upgrade modal fit screen

---

packages/manage-apps-extras/middleware.js
packages/manage-apps-extras/middleware.test.js

Fix a small issue, since I was not using the right exported value to check the event type in the middleware (fixed for https://github.com/bufferapp/buffer-publish/pull/301).
I think no review is necessary but adding @hharnisc here for context :)

Fix notification when revoking access of connected app

---

package.json
packages/app-sidebar/package.json
packages/beta-redirect/package.json
packages/change-password/package.json
packages/close-account/package.json
packages/drafts/package.json
packages/example/package.json
packages/i18n/translations/en-us.json
packages/manage-apps-extras/package.json
packages/notifications/package.json
packages/preferences/package.json
packages/profile-page/__snapshots__/snapshot.test.js.snap
packages/profile-page/package.json
packages/profile-sidebar/__snapshots__/snapshot.test.js.snap
packages/profile-sidebar/components/ProfileSidebar/story.jsx
packages/profile-sidebar/middleware.js
packages/profile-sidebar/package.json
packages/queue/package.json
packages/sent/package.json
packages/server/index.html
packages/settings/package.json
packages/shared-components/package.json
packages/upgrade-modal/package.json
packages/web/package.json
yarn.lock

Link to the Org Admin for managing social accounts.

[PUB-312] Link to the Org Admin for managing social accounts

---

packages/queue/middleware.js
packages/queue/middleware.test.js

Add composer notifications when scheduling a post.

[PUB-573] Add composer notifications when scheduling a post

---

packages/queue/package.json
yarn.lock

Reverts bufferapp/buffer-publish#325

Revert "Update composer package"

---

packages/default-page/package.json

fixed deps for default-page

---

packages/queue/package.json
yarn.lock

Update composer to 1.12

---

packages/queue/components/ComposerPopover/index.jsx

Align composer to the left side in new Publish
Task: [PUB-655](https://buffer.atlassian.net/browse/PUB-655)

Fix alignment of the composer in Publish

---

packages/profile-page/components/ProfilePage/index.jsx
packages/shared-components/ScrollableContainer/index.jsx

Fixing issue with the composer window being truncated when you have only 1 post in your queue
This relates to task: [PUB-659](https://buffer.atlassian.net/browse/PUB-659)

[PUB-659] Fixing issue with truncated composer window

---

packages/queue/package.json
yarn.lock

Update composer version to 1.12.3

Bump composer version to 1.12.3

---

packages/queue/package.json
yarn.lock

Update composer version to 1.12.4

Bump composer version to 1.12.4

---

packages/settings/components/ProfileSettings/index.jsx

Fix issue with Drag and Drop getting stuck.
The issue appears to be a side-effect of object property modification, as when an object is modified, and its not handled correctly, the original object gets into an invalid state, causing the UI to crash in different places.

[PUB-500] Drag and Drop in New Publish Queue not working

---

packages/shared-components/ImagePost/index.jsx
packages/shared-components/LinkPost/index.jsx
packages/shared-components/MultipleImagesPost/index.jsx
packages/shared-components/Post/index.jsx
packages/shared-components/Post/story.jsx
packages/shared-components/TextPost/index.jsx
packages/shared-components/VideoPost/index.jsx
packages/utils/postParser.js

Add statistics props to each post to be able to later on show those stats for pro users
[PUB-713](https://buffer.atlassian.net/browse/PUB-713)

[PUB-713] Add post statistics props

---

package.json
packages/shared-components/ImagePost/index.jsx
packages/shared-components/ImagePost/story.jsx
packages/shared-components/LinkPost/index.jsx
packages/shared-components/LinkPost/story.jsx
packages/shared-components/MultipleImagesPost/index.jsx
packages/shared-components/MultipleImagesPost/story.jsx
packages/shared-components/TextPost/index.jsx
packages/shared-components/TextPost/story.jsx
packages/shared-components/VideoPost/story.jsx
yarn.lock

Adding line breaks for posts in queue where there are line breaks in the original post (in edit mode)
Just waiting for components repo to be approved to merge before adding in the component version number to this repository of the final published version

WIP PUB-482 | Show line breaks in post queue

---

packages/product-features/README.md
packages/product-features/components/FeatureLoader/index.jsx
packages/product-features/components/FeatureLoader/story.jsx
packages/product-features/index.js
packages/product-features/index.test.jsx
packages/product-features/middleware.js
packages/product-features/middleware.test.js
packages/product-features/package-lock.json
packages/product-features/package.json
packages/product-features/reducer.js
packages/product-features/reducer.test.js
packages/profile-sidebar/components/ProfileSidebar/index.jsx
packages/profile-sidebar/components/ProfileSidebar/story.jsx
packages/profile-sidebar/package.json
packages/store/index.js
packages/store/reducers.js
packages/utils/featureParser.js

Switch the sidebar from saying publish free for pro users to saying publish pro instead using the new RPC endpoint
Work in progress, feedback always welcome, definitely not stable at present / fully functional 😄

[PUB-705] Switch sidebar from displaying publish free for pro users

---

packages/sent/components/SentPosts/index.jsx
packages/shared-components/ImagePost/index.jsx
packages/shared-components/LinkPost/index.jsx
packages/shared-components/MultipleImagesPost/index.jsx
packages/shared-components/Post/index.jsx
packages/shared-components/PostFooter/index.jsx
packages/shared-components/PostList/index.jsx
packages/shared-components/PostLists/index.jsx
packages/shared-components/TextPost/index.jsx
packages/shared-components/VideoPost/index.jsx

Hide action buttons on footer from Sent Tab.

Hide action buttons on footer from sent tab

---

packages/queue/components/QueuedPosts/story.jsx
packages/shared-components/ImagePost/index.jsx
packages/shared-components/ImagePost/story.jsx
packages/shared-components/LinkPost/index.jsx
packages/shared-components/LinkPost/story.jsx
packages/shared-components/MultipleImagesPost/index.jsx
packages/shared-components/MultipleImagesPost/story.jsx
packages/shared-components/Post/index.jsx
packages/shared-components/Post/story.jsx
packages/shared-components/PostList/story.jsx
packages/shared-components/PostList/test.jsx
packages/shared-components/PostLists/story.jsx
packages/shared-components/PostStats/index.jsx
packages/shared-components/PostStats/story.jsx
packages/shared-components/QueueItems/story.jsx
packages/shared-components/TextPost/index.jsx
packages/shared-components/TextPost/story.jsx
packages/shared-components/VideoPost/index.jsx
packages/shared-components/VideoPost/story.jsx
packages/utils/index.js
packages/utils/number.js
packages/utils/number.test.js

Add post's stats bar to be displayed for Pro Users
Task: [PUB-714](https://buffer.atlassian.net/browse/PUB-714)

[PUB-714] Add post's stats bar

---

packages/shared-components/PostFooter/index.jsx
packages/shared-components/PostFooter/story.jsx
packages/shared-components/RetweetPanel/index.jsx

Increase size retweet panel. Small non-related fix: style tweak on custom scheduled post footer.
Task: [PUB-776](https://buffer.atlassian.net/browse/PUB-776)

[PUB-776] Increase Size Retweet Panel

---

package.json
packages/shared-components/PostFooter/index.jsx
packages/shared-components/PostFooter/story.jsx
packages/utils/postParser.js
yarn.lock

Add a custom message on the footer of each Instagram Reminder Post

[PUB-801] Display custom footer message when IG reminder

---

packages/queue/package.json
yarn.lock

Add Share Next feature for Pro and up users.
Task: [PUB-720](https://buffer.atlassian.net/browse/PUB-720)

[PUB-720] Update composer version to 1.12.5

---

packages/queue/package.json
yarn.lock

Update composer version to 1.12.6

Update composer version to 1.12.6

---

packages/queue/package.json
yarn.lock

Select the right default profile for the current pinterest board

Pinterest select right profile

---

packages/i18n/translations/en-us.json
packages/profile-sidebar/components/ProfileSidebar/index.jsx
packages/profile-sidebar/components/ProfileSidebar/story.jsx
packages/profile-sidebar/index.js
packages/utils/userParser.js

Fix tooltip to display number of accounts allowed.
Task: [PUB-807](https://buffer.atlassian.net/browse/PUB-807)

[PUB-807] Update tooltip's limit of accounts

---

packages/queue/package.json
yarn.lock

Update composer version to 2.1.1
Composer change: https://buffer.atlassian.net/browse/PUB-692

Update composer version to 2.1.1

---

package.json
yarn.lock

Fixing storybook to work again

Updating storybook versions

---

package.json
packages/queue/components/MiniCalendar/index.jsx
packages/queue/package.json
yarn.lock

Update composer to 2.1.6 and components to 3.0.2 to get style change in `InputDate` selected days.

Add design tweaks to datepickers

---

packages/tabs/components/TabNavigation/index.jsx
packages/tabs/index.js

Display Drafts and Awaiting Approval tabs to Managers and Drafts and Pending Approval tabs to Contributors

[PUB-844] Add drafts tabs logic

---

packages/queue/package.json
yarn.lock

Update composer version to 2.1.7 to have access to draftMode in Composer interface for New Publish
Task: [PUB-866](https://buffer.atlassian.net/browse/PUB-866)

Update composer version to 2.1.7

---

packages/composer-popover/package.json
yarn.lock

Changing composer version to 2.1.6, which fixes the character count bug.

Changing composer version to 2.1.9

---

packages/composer-popover/package.json
yarn.lock

Day to start week (Updating composer version).

---

packages/composer-popover/package.json
yarn.lock

Update composer package to 2.2.1 to fix composer holding state after edit
https://buffer.atlassian.net/browse/PUB-685

Update composer package to 2.2.1

---

packages/composer-popover/index.js
packages/composer-popover/package.json
packages/drafts/components/DraftList/index.jsx
packages/queue/components/QueuedPosts/index.jsx
packages/sent/components/SentPosts/index.jsx
yarn.lock

Composer positioning problems in New Publish
Task: [PUB-899](https://buffer.atlassian.net/browse/PUB-899)

[PUB-899] Fix position composer

---

packages/profile-page/package.json
packages/store/package.json
packages/web/package.json
yarn.lock

Update app-sidebar version to 1.9.24 to remove "Coming soon" label from Analyze button on sidebar.

Update app-sidebar version to 1.9.24

---

packages/composer-popover/package.json
yarn.lock

Update composer version to 2.2.4 
Highlights social account image on hover 
http://hi.buffer.com/56e138b875aa

Update composer version to 2.2.4

---

package-lock.json
packages/posting-schedule/components/TimezoneInputForm/index.jsx

Show the timezone that has been saved in posting schedule, rather than an empty input field.
The surrounding code is quite hacky so this is a quick fix that will require us to revisit the code later. This just displays the timezone that has been saved on refresh. There is more work to be done around the input not being cleared when you select into it.
Hey @anafilipadealmeida / @hamstu :D

use timezone in state

---

packages/drafts/index.js
packages/pusher-sync/package.json
packages/server/package.json
packages/shared-components/Draft/index.jsx
packages/shared-components/Draft/story.jsx
packages/shared-components/DraftFooter/index.jsx
packages/shared-components/DraftFooter/story.jsx
packages/shared-components/DraftHeader/index.jsx
packages/shared-components/DraftHeader/story.jsx
packages/shared-components/ImageDraft/story.jsx
packages/shared-components/LinkDraft/story.jsx
packages/shared-components/MultipleImagesDraft/story.jsx
packages/shared-components/QueueItems/postData.js
packages/shared-components/TextDraft/story.jsx
packages/shared-components/VideoDraft/story.jsx
yarn.lock

Show info related to a post in Drafts and Awaiting Approval
Task: [PUB-857](https://buffer.atlassian.net/browse/PUB-857)
Related to: https://github.com/bufferapp/buffer-js-publish-parsers/pull/2 -> that PR needs to be deployed first and then go to `packages/server/package.json` and update the `@bufferapp/publish-parsers` version. Has a temporary version 1.9.28-beta.1

[PUB-857] Add details header to drafts

---

packages/drafts/components/DraftList/index.jsx
packages/drafts/components/Empty/index.jsx
packages/drafts/components/Empty/story.jsx
packages/drafts/index.js
packages/profile-page/components/ProfilePage/index.jsx
packages/profile-page/index.js

See Drafts that need approval in `Pending Approval` and `Awaiting Approval` tabs. See drafts that don't need approval in `Drafts`tab.
See `Add draft` composer only in `Drafts` tab.
Task: [PUB-848](https://buffer.atlassian.net/browse/PUB-848)
I know that the code coverage is not increasing here, but once the Drafts are done I'm planning on adding tests to it.

[PUB-848]Task/add approval tabs list

---

packages/drafts/components/DraftList/index.jsx
packages/drafts/components/Empty/index.jsx

Clean drafts preexisting code: Add missing propTypes, remove unused declarations and imports, follow lint patterns.

Add missing proptypes and remove unused declarations

---

packages/drafts/index.js
packages/pusher-sync/package.json
packages/server/package.json
yarn.lock

Update publish-parsers version to get changes in postParsers (ability to get user id in each draft, to check if user is the creator of a draft)
Related to [publish-parsers PR](https://github.com/bufferapp/buffer-js-publish-parsers/pull/3)

Update publish-parsers version

---

packages/upgrade-modal/middleware.js
packages/upgrade-modal/middleware.test.js

Fixes `metdata` -> `metadata`. Oops!
This fixes the missing `source` and `user id` fields reported by @jwinternheimer.

Fix typo in tracking 🙈

---

.storybook/preview-head.html
packages/i18n/translations/en-us.json

Quick fix for a bug spotted by @jwinternheimer 😄 
Thread: https://buffer.slack.com/archives/C151RRDL1/p1542743078521500

[Hotfix] Fix discount percentage shown in upgrade modal

---

packages/profile-page/components/ProfilePage/index.jsx
packages/tabs/components/TabNavigation/index.jsx

Add analytics tab for B4B. (Next, I'll add analytics package under tab.) Analytics is currently WIP, which should be ok since we don't have B4B users yet :) 
https://paper.dropbox.com/doc/Analyze-Components-in-New-Publish--ASK4cTWL0aaixNol6_hzybIMAg-Mm9abUJq9wcC7IgjFt6V0

[PUB-932] Add analytics tab

---

package.json
packages/analytics/analytics.css
packages/analytics/index.js
packages/analytics/package.json
packages/profile-page/components/ProfilePage/index.jsx
packages/profile-sidebar/middleware.js
packages/server/analyze.config.js
packages/server/rpc/analytics/analyticsStartDate/index.js
packages/server/rpc/analytics/analyticsStartDate/index.test.js
packages/server/rpc/analytics/audience/index.js
packages/server/rpc/analytics/audience/index.test.js
packages/server/rpc/analytics/average/index.js
packages/server/rpc/analytics/average/index.test.js
packages/server/rpc/analytics/compare/index.js
packages/server/rpc/analytics/compare/index.test.js
packages/server/rpc/analytics/contextual/index.js
packages/server/rpc/analytics/contextual/index.test.js
packages/server/rpc/analytics/hourly/index.js
packages/server/rpc/analytics/hourly/index.test.js
packages/server/rpc/analytics/posts/index.js
packages/server/rpc/analytics/posts/index.test.js
packages/server/rpc/analytics/postsSummary/index.js
packages/server/rpc/analytics/postsSummary/index.test.js
packages/server/rpc/analytics/summary/index.js
packages/server/rpc/analytics/summary/index.test.js
packages/server/rpc/index.js
packages/store/index.js
packages/store/package.json
packages/store/reducers.js
yarn.lock

Add performance summary component to Analytics package
[PUB-917](https://buffer.atlassian.net/browse/PUB-917)
[Scoping Analytics doc](https://paper.dropbox.com/doc/Scoping-Analytics-for-B4B-in-New-Publish--ASky_9j9dl4PN0FzF30FuvPiAg-788eoDDmJ1QTHGzQt4vAF)
I'm currently styling it similar to Analyze. This could change after Dave reviews it. I added a css file to hide the "Add to Report" button.  
The datepicker is currently displaying an error. I'm going to add the fix with the same PR where I'm excluding datepicker styles in composer.  

[PUB-917] Add summary-table component to analytics

---

package.json
packages/analytics/index.js
packages/analytics/package.json
packages/server/analyze.config.js
packages/server/rpc/index.js
packages/store/index.js
packages/store/package.json
packages/store/reducers.js
yarn.lock

A user is able to view average performance analytics.
https://buffer.atlassian.net/browse/PUB-920

[PUB-920] Add average table component to analytics

---

analyze.config.js
jest.config.js
package.json
packages/server/webpack.config.common.js

Refactor jest config into own file and use analyze config file.
Decided to break this out into it's own PR. There is not a JIRA task for it.

Refactor jest config into its own file

---

packages/stripe/middleware.js
packages/stripe/middleware.test.js

Pass the correct param to the Stripe call

---

packages/server/lib/bugsnag.js
packages/web/components/ErrorBoundary/index.jsx

Adds quick links for FullStory recording and Buffer Admin link to Bugsnag reports.

Add FullStory and Buffer Admin Link to Bugsnag

---

packages/composer-popover/components/ComposerWrapper/index.jsx
packages/composer-popover/package.json

See https://github.com/bufferapp/buffer-composer/pull/118

Use version of composer with stateless App component

---

.storybook/config.js
.storybook/webpack.config.js

Fixing issues with storybook not compiling correctly

Fixing issues with yarn storybook

---

packages/analytics/components/AnalyticsList/index.jsx
packages/analytics/components/ProfileHeader/index.jsx
packages/analytics/components/Toolbar/index.jsx
packages/analytics/index.js
packages/analytics/package.json
packages/profile-page/components/ProfilePage/index.jsx
yarn.lock

Add profile-header component to Analytics toolbar
https://buffer.atlassian.net/browse/PUB-994

[PUB-994] Add profile-header component to Analytics toolbar

---

packages/profile-page/package.json
packages/server/rpc/upgradeToPro/index.js
packages/store/package.json
packages/web/package.json
yarn.lock

See https://github.com/bufferapp/buffer-js-app-sidebar/pull/2

Add 'Upgrade to Pro' link in Publish Sidebar

---

packages/drafts/reducer.js
packages/pusher-sync/middleware.js
packages/pusher-sync/middleware.test.js
packages/queue/reducer.js

Add Pusher for drafts.
Related to [PUB-851](https://buffer.atlassian.net/browse/PUB-851)

Pusher for drafts

---

packages/analytics/components/AnalyticsList/analytics.css
packages/analytics/components/AnalyticsList/index.jsx

Add global style to analytics css module to sandbox the css

[Fix] Add global id to sandbox analytics style

---

packages/queue/index.js

Rollback practice! Just a random comment to roll it back.

[null-op] Rollback practice!

---

packages/profile-page/components/ProfilePage/index.jsx
packages/profile-page/index.js

Add drafts, awaitingApproval and pendingApproval tabs to get ability to load more drafts.

Add ability to load more to drafts tabs

---

packages/analytics/components/AnalyticsList/analytics.css

Added comment to practice rollback :) 

Add comment to roll it back

---

packages/drafts/reducer.js

[null-op] Rollback practice

---

packages/drafts/components/Empty/story.jsx
packages/drafts/index.test.jsx
packages/drafts/reducer.js
packages/drafts/reducer.test.js

Drafts Tests

---

packages/queue/index.js
packages/queue/index.test.jsx
packages/sent/components/SentPosts/index.jsx
packages/sent/index.js
packages/sent/index.test.jsx
packages/shared-components/ImagePost/index.jsx
packages/shared-components/LinkPost/index.jsx
packages/shared-components/MultipleImagesPost/index.jsx
packages/shared-components/Post/index.jsx
packages/shared-components/PostFooter/index.jsx
packages/shared-components/PostFooter/story.jsx
packages/shared-components/PostList/index.jsx
packages/shared-components/PostLists/index.jsx
packages/shared-components/TextPost/index.jsx
packages/shared-components/VideoPost/index.jsx

Contributor should not see actions in posts (delete, edit, and so on). Only managers can perform actions in the queue's posts
Task: [PUB-1011](https://buffer.atlassian.net/browse/PUB-1011)

[PUB-1011] Task/disable actions queue contributor

---

packages/composer-popover/package.json
yarn.lock

Update composer version to fix [PUB-758](https://buffer.atlassian.net/browse/PUB-758) Emoji picker - hitting enter should select the currently highlighted emoji in the list

Update composer version to 2.4.4

---

package.json
packages/general-settings/components/GoogleAnalytics/index.jsx
packages/general-settings/components/InstagramDirectPosting/index.jsx
packages/general-settings/components/LinkShortening/LinkShorteningWrapper.jsx
packages/general-settings/components/LinkShortening/index.jsx
yarn.lock

Design tweaks to general settings tab

Normalize general settings styles

---

package.json
packages/i18n/translations/en-us.json
packages/profile-sidebar/components/ProfileSidebar/story.jsx
yarn.lock

Change “Manage Social Accounts” button copy to “Add a Social Account” 
Updated webpack-dev-server to 3.1.11

Change connect button copy

---

packages/tabs/components/TabNavigation/index.jsx
packages/tabs/components/TabNavigation/story.jsx
packages/tabs/index.js

Remove drafts feature flip

---

packages/composer-popover/package.json
yarn.lock

📖 See commit: https://github.com/bufferapp/buffer-composer/commit/5feb38d22748addc8278b00cc49f04f1b208faae

Upgrade Composer to v2.6.8

---

packages/tabs/utils/index.js

Changing calendar URL to use new generic URL (content_only)

[PUB-1039] Changing calendar URL to use new URL

---

packages/general-settings/components/GeneralSettings/index.jsx
packages/general-settings/index.js

Displaying "Enable Direct Posting" option only for IG accounts.

[PUB-1013] Displaying Enable Direct Scheduling only for Instagram accounts.

---

packages/general-settings/components/GeneralSettings/story.jsx
packages/general-settings/index.js

Validating profile data variable in case is null.

Validating profile data variable in case is null.

---

packages/general-settings/index.js
packages/general-settings/reducer.js
packages/general-settings/reducer.test.js
yarn.lock

Changing isInstagramProfile state to maintain consistency with the rest of the attributes.

Changing isInstagramProfile state to maintain consistency.

---

package.json
packages/server/webpack.config.dev.js
yarn.lock

Adding allowedHosts to webpack config for local development to prevent error messages appearing during development
more context here: 
https://buffer.slack.com/archives/C151RRDL1/p1548689750033400
https://www.npmjs.com/advisories/725
https://webpack.js.org/configuration/dev-server/#devserver-allowedhosts

Updating webpack to deal with allowedHosts error

---

packages/general-settings/components/InstagramDirectPosting/index.jsx
packages/queue/components/InstagramDirectPostingBanner/index.jsx
packages/queue/components/InstagramDirectPostingModal/index.jsx

Make copy changes to Instagram Direct Scheduling.

Change copy instagram direct scheduling

---

packages/store/index.js

Add Instagram action tracking
[PUB-1104](https://buffer.atlassian.net/browse/PUB-1104)
Hey @hamstu, I realized instead of tracking an action twice when we want custom metadata (like with the Upgrade Modal), we could just create an exception inside the function `createBufferMetricsMiddleware`.  How do you feel about it? We could even list them all in another file if in the future it gets too long 😄

[PUB-1104] Add IG data tracking

---

packages/general-settings/components/GeneralSettings/index.jsx
packages/general-settings/components/GeneralSettings/story.jsx
packages/general-settings/components/GoogleAnalytics/index.jsx
packages/general-settings/components/GoogleAnalytics/story.jsx
packages/general-settings/index.js
packages/general-settings/middleware.js
packages/general-settings/middleware.test.js
packages/general-settings/reducer.js
packages/general-settings/reducer.test.js
packages/server/rpc/getGATrackingSettings/index.js
packages/server/rpc/index.js
packages/server/rpc/saveGATrackingSettings/index.js

Adding rpc endpoint and wiring it up to Google Analytics form.

[PUB-800] Adding rpc endpoint and wiring it up to Google Analytics form.

---

packages/i18n/translations/en-us.json
packages/profile-sidebar/components/ProfileSidebar/story.jsx

Changing social media management link text to Manage Social Accounts from Connect a Social Account

Updating Connect a Social Account to Manage Social Accounts

---

packages/general-settings/middleware.js
packages/profile-sidebar/components/ProfileList/index.jsx
packages/profile-sidebar/middleware.js
packages/profile-sidebar/reducer.js
packages/profile-sidebar/reducer.test.js
packages/queue/components/Modal/index.jsx
packages/queue/components/QueuedPosts/index.jsx
packages/queue/components/QueuedPosts/story.jsx
packages/queue/index.js
packages/queue/reducer.js
packages/queue/reducer.test.js
packages/tabs/components/TabNavigation/index.jsx
packages/tabs/index.js

Adding prompt message when user selects a locked account.
I fixed a couple of bugs I noticed in the code, and added a modal prompt message with the same styles as in the rest of publish.

[PUB-1062] Adding prompt message when user selects a locked account.

---

packages/composer-popover/package.json
yarn.lock

Fix Queue limit upgrade path button in the Extension not working
[PUB-657](https://buffer.atlassian.net/browse/PUB-657)

Update composer to 2.6.12

---

packages/general-settings/components/GeneralSettings/index.jsx
packages/general-settings/components/GoogleAnalytics/index.jsx
packages/general-settings/components/InstagramDirectPosting/index.jsx
packages/general-settings/components/InstagramReminders/index.jsx
packages/general-settings/components/InstagramReminders/story.jsx
packages/general-settings/components/LinkShortening/LinkShorteningWrapper.jsx
packages/general-settings/index.js
packages/general-settings/middleware.js
packages/general-settings/reducer.js
packages/general-settings/reducer.test.js
packages/queue/middleware.js
packages/server/rpc/index.js
packages/server/rpc/toggleInstagramReminders/index.js

Instagram Reminder Toggle for New Publish
[PUB-1059](https://buffer.atlassian.net/browse/PUB-1059)
Things to add in another PR: see what happens when the user is a contributor

[PUB-1059] Instagram Reminder settings in New Publish

---

jest-raf-shim.js
packages/i18n/translations/en-us.json
packages/modals/components/AppModals/__snapshots__/index.test.jsx.snap
packages/modals/components/AppModals/index.jsx
packages/modals/components/AppModals/index.test.jsx
packages/modals/middleware.js
packages/modals/package.json
packages/modals/reducer.js
packages/profile-sidebar/components/ProfileList/index.jsx
packages/profile-sidebar/components/ProfileListItem/index.jsx
packages/profile-sidebar/components/ProfileSidebar/index.jsx
packages/profile-sidebar/index.js
packages/profile-sidebar/package.json
packages/profiles-disconnected-modal/README.md
packages/profiles-disconnected-modal/components/ProfilesDisconnectedModal/index.jsx
packages/profiles-disconnected-modal/components/ProfilesDisconnectedModal/story.jsx
packages/profiles-disconnected-modal/index.js
packages/profiles-disconnected-modal/middleware.js
packages/profiles-disconnected-modal/middleware.test.js
packages/profiles-disconnected-modal/package.json
packages/profiles-disconnected-modal/reducer.js
packages/profiles-disconnected-modal/reducer.test.js
packages/pusher-sync/package.json
packages/server/package.json
packages/store/index.js
packages/store/package.json
packages/store/reducers.js
yarn.lock

See Jira card: https://buffer.atlassian.net/browse/PUB-1055
Depends on this PR landing in `buffer-web`: https://github.com/bufferapp/buffer-web/pull/15846

[PUB-1055] Add modal for reconnecting disconnected social accounts

---

packages/web/components/ErrorBoundary/index.jsx

See https://buffer.slack.com/archives/C151RRDL1/p1548889044147800

Disable FullStory integration with BugSnag

---

packages/general-settings/components/GeneralSettings/index.jsx
packages/general-settings/components/InstagramReminders/index.jsx
packages/general-settings/components/InstagramReminders/story.jsx

Disable Instagram Reminder Toggle for contributors
[PUB-1059](https://buffer.atlassian.net/browse/PUB-1059)

[PUB-1059] Disable reminders toggle if contributor

---

packages/shared-components/Post/index.jsx

Handle postDetails being undefined in Post component

Handle postDetails being undefined in Post component

---

packages/i18n/translations/en-us.json
packages/modals/components/AppModals/index.jsx
packages/modals/middleware.js
packages/modals/middleware.test.js
packages/modals/reducer.js
packages/modals/reducer.test.js
packages/modals/util/showModal.js
packages/server/index.js
packages/steal-profile-modal/README.md
packages/steal-profile-modal/components/StealProfileModal/index.jsx
packages/steal-profile-modal/components/StealProfileModal/story.jsx
packages/steal-profile-modal/index.js
packages/steal-profile-modal/index.test.jsx
packages/steal-profile-modal/package.json
packages/steal-profile-modal/reducer.js
packages/steal-profile-modal/reducer.test.js
packages/store/reducers.js

Adding a modal warning users they are attempting to connect a profile that has already being connected to a different Buffer Org.

[PUB-1052] Adding a modal for steal profiles warning

---

packages/account-notifications/components/Notification/index.jsx
packages/account-notifications/components/Notification/story.jsx
packages/account-notifications/components/Notifications/index.jsx
packages/account-notifications/components/Notifications/story.jsx
packages/account-notifications/index.js
packages/account-notifications/index.test.jsx
packages/account-notifications/middleware.js
packages/account-notifications/middleware.test.js
packages/account-notifications/package.json
packages/account-notifications/reducer.js
packages/account-notifications/reducer.test.js
packages/preferences/components/Preferences/index.jsx
packages/preferences/constants.js
packages/pusher-sync/package.json
packages/server/package.json
packages/server/rpc/changeDateTimePreferences/test.js
packages/server/rpc/index.js
packages/server/rpc/setNotifications/index.js
packages/store/index.js
packages/store/package.json
packages/store/reducers.js
yarn.lock

Customer can toggle select email triggers on/off
[PUB-1069](https://buffer.atlassian.net/browse/PUB-1069)

[PUB-1069] Customer can toggle select email triggers on/off

---

package.json
packages/server/index.js
yarn.lock

Adding helmet to publish codebase as per this PR: https://buffer.atlassian.net/browse/PUB-1177

PUB-1177 | Adding helmet to publish codebase

---

packages/pusher-sync/package.json
packages/server/package.json
yarn.lock

Updating parser version from 1.12.4 to 1.12.5

Updating parser version from 1.12.4 to 1.12.5.

---

package.json
packages/server/package.json

moving helmet dependency to the right package

PUB-1177 | Moving helmet to the right package

---

package.json
packages/server/package.json

Reverts bufferapp/buffer-publish#556

Revert "PUB-1177 | Moving helmet to the right package"

---

package.json
packages/server/index.js
yarn.lock

Reverts bufferapp/buffer-publish#554

Revert "PUB-1177 | Adding helmet to publish codebase"

---

packages/server/index.js
packages/server/package.json
yarn.lock

Adding helmet coverage to deal with pub-1177

PUB-1177 | Adding helmet dependency

---

packages/composer-popover/package.json
yarn.lock

Update composer version to 2.6.14 to fix image stuck on "Finishing up" due to unhandled uppercase extension.
[PUB-930](https://buffer.atlassian.net/browse/PUB-930)

Update composer version to 2.6.14

---

packages/app-switcher/middleware.js
packages/modals/package.json
packages/server/package.json
packages/store/package.json
yarn.lock

Adding tracking to publish feedback modal

PUB-1112 | Implementing tagging for publish feedback modal

---

packages/composer-popover/package.json
yarn.lock

📖 See commit: https://github.com/bufferapp/buffer-composer/commit/4ee15b39c969c2823bc3396175d1960ec05f31b6

Upgrade Composer to v2.6.15

---

packages/data-tracking/package.json
packages/modals/package.json
packages/server/package.json
yarn.lock

Upgrading library to fix undefined variable issue

Upgrading library to fix undefined variable issue

---

packages/shared-components/PostList/index.jsx

Adjusting Send to mobile text.

Adjusting Send to mobile text.

---

packages/shared-components/PostList/index.jsx

Fixing alignment bug on Share again button, related to task [PUB-1065](https://buffer.atlassian.net/browse/PUB-1065) Point #1

[PUB-1065] Fixing the alignment for the buttons.

---

packages/i18n/translations/en-us.json

Changing text for welcome modal.

[PUB-1189] Changing text for welcome modal.

---

packages/composer-popover/package.json
yarn.lock

📖 See commit: https://github.com/bufferapp/buffer-composer/commit/5e9f6950f9cc7882d13f01a9979b71ddf67d74e9

Upgrade Composer to v2.6.16

---

packages/cta-banner/components/BillingUpgradeCTABanner/index.jsx
packages/cta-banner/components/BillingUpgradeCTABanner/story.jsx
packages/cta-banner/index.js
packages/cta-banner/middleware.js
packages/cta-banner/package.json
packages/cta-banner/reducer.js
packages/i18n/components/TranslationReplacer/index.jsx
packages/i18n/components/TranslationReplacer/story.jsx
packages/i18n/helper/index.js
packages/i18n/index.js
packages/i18n/translations/en-us.json
packages/pusher-sync/package.json
packages/server/package.json
packages/store/index.js
packages/web/components/App/index.jsx
yarn.lock

Show users in new publish a banner Informing users that they are actively trialling a plan
http://hi.buffer.com/a4b8ed82bced
http://hi.buffer.com/204b016db13e
vs what used to be there:
http://hi.buffer.com/204b016db13e

JIRA:PUB-1172 | Informing users that they are actively trialling a plan

---

packages/pusher-sync/package.json
packages/server/package.json
yarn.lock

Upgrading parsers library to fix issue with free to pro user upgrade messages

PUB-1172 | Adjusting logic for free to pro plan users

---

packages/app-switcher/middleware.js

Update track action middleware to use logging proxy

Update track action middleware to use logging proxy

---

packages/analytics/components/AnalyticsList/index.jsx
packages/analytics/index.js
packages/drafts/components/DraftList/index.jsx
packages/drafts/index.js
packages/general-settings/components/GeneralSettings/index.jsx
packages/general-settings/index.js
packages/past-reminders/components/PastRemindersPosts/index.jsx
packages/past-reminders/index.js
packages/queue/components/QueuedPosts/index.jsx
packages/queue/index.js
packages/sent/components/SentPosts/index.jsx
packages/sent/components/SentPosts/postData.js
packages/sent/components/SentPosts/story.jsx
packages/sent/index.js
packages/shared-components/LockedProfileNotification/index.jsx
packages/shared-components/LockedProfileNotification/story.jsx

Pro users see "Upgrade to Pro" CTA when reaching connected profile limit
[PUB-1191](https://buffer.atlassian.net/browse/PUB-1191)
Also fixed the Sent Posts story, which was not displaying any posts

[PUB-1191] Add Custom Locked Profile Notification for Pro users

---

packages/pusher-sync/package.json
packages/server/package.json
yarn.lock

Updating parsers library version, which fixes Publish crashing error.

[PUB-1159] Updating parsers library version.

---

packages/pusher-sync/package.json
packages/server/package.json
yarn.lock

Reverts bufferapp/buffer-publish#583

Revert "[PUB-1159] Updating parsers library version."

---

packages/pusher-sync/package.json
packages/server/package.json
yarn.lock

I'm putting back your library parsers work, could you take a look at that please @MayaUribe

Revert "Revert "[PUB-1159] Updating parsers library version.""

---

packages/drafts/index.js

Fixes drafts blank page for Pro customers
[PUB-1210](https://buffer.atlassian.net/browse/PUB-1210)

[PUB-1210] Fix drafts blank page error

---

packages/posting-schedule/components/PostingSchedule/index.jsx
packages/posting-schedule/components/PostingTimeForm/index.jsx
packages/posting-schedule/middleware.js

Save notification not shown when adding a time to posting schedule
[PUB-1133](https://buffer.atlassian.net/browse/PUB-1133)

[PUB-1133] Missing notification when adding a time to posting schedule

---

packages/posting-schedule/components/PostingSchedule/index.jsx
packages/queue/components/QueuePausedBar/index.jsx

Update paused queue button copy to display "Resume Queue".
[PUB-1147](https://buffer.atlassian.net/browse/PUB-1147)

[PUB-1147] Update paused queue button copy

---

packages/data-tracking/package.json
packages/modals/package.json
packages/server/package.json
yarn.lock

Upgrading publish to use the new buffermetrics to try to reduce memory consumption

Upgrading publish to use the new buffermetrics to try to reduce memory consumption

---

packages/queue/components/QueuePausedBar/index.jsx
packages/queue/components/QueuePausedBar/story.jsx
packages/queue/components/QueuedPosts/index.jsx
packages/queue/components/QueuedPosts/story.jsx
packages/queue/index.js

Contributors should not be able to resume queue through the Queue Tab.
Transform "Learn more" `<Button>` in a `<Link>`.
Write custom banner message for Contributor's `<QueuePausedBar>`.
[PUB-1248](https://buffer.atlassian.net/browse/PUB-1248)

[PUB-1248] Contributors can't resume queue through the Queue Tab

---

packages/sidebar/package.json
packages/store/package.json
yarn.lock

Updating app-sidebar package version.
app-sidebar 1.10.4 version tracks user's plan in Fullstory and limits tracking for free users.

[PUB-1222] Updating app-sidebar package version.

---

package.json

Re adding rebuild grpc command

Re adding rebuild grpc command

---

packages/queue/components/QueuedPosts/index.jsx

- Experiment: this adds a simple CSS class to the mini-cal element so that it can be targeted inside of FullStory. We can then filter and watch FS sessions just where users are interacting w/ this particular feature / element. 

Adds class name to mini-cal for FullStory experiment.

---

packages/sidebar/package.json
packages/store/package.json
yarn.lock

Updating app sidebar package version to 1.10.6: Fixing sidebar styling position when user scrolls on Firefox.

[PUB-1239] Updating app sidebar package version

---

packages/profile-page/components/ProfilePage/index.jsx
packages/profile-page/index.js
packages/profiles-disconnected-modal/components/ProfilesDisconnectedModal/index.jsx
packages/profiles-disconnected-modal/index.js
packages/profiles-disconnected-modal/middleware.js
packages/tabs/components/TabNavigation/index.jsx

Add reconnect tab in settings to reconnect profile & redirect user in disconnected profile modal to FAQ if an instagram business user

Add reconnect tab in settings and redirect user to FAQ if instagram business

---

packages/profile-page/components/ProfilePage/index.jsx
packages/profile-page/index.js
packages/profiles-disconnected-modal/components/ProfilesDisconnectedModal/index.jsx
packages/profiles-disconnected-modal/index.js
packages/profiles-disconnected-modal/middleware.js
packages/profiles-disconnected-modal/reducer.js

Redirect user to FAQ in Disconnect Modal if their disconnected profile is Instagram Business

Redirect to FAQ if disconnected profile is Instagram Business

---

packages/profile-page/components/ProfilePage/index.jsx
packages/tabs/components/TabNavigation/index.jsx

Change reconnect tab to button and right align

Change reconnect tab to a button

---

packages/preferences/components/Preferences/index.jsx
packages/profile-page/components/ProfilePage/index.jsx

Fixing sidebar scrolling issue after including top temporary banner.

Fixing sidebar scrolling issue after including top temporary banner.

---

packages/temporary-banner/components/TemporaryDashboardBanner/index.jsx

- Better align close icon in banner 
- Close icon now uses same color as text 

Adds some visual polish to the temporary banner.

---

packages/queue/components/QueuedPosts/index.jsx
packages/queue/components/QueuedPosts/story.jsx
packages/queue/index.js

Team Members should see the "Show Overview" button, which displays the mini calendar/overview calendar. Used `isBusinessAccount` prop to flag profiles from team member (includes all Managers and Contributors of team accounts).
[PUB-1243](https://buffer.atlassian.net/browse/PUB-1243)

[PUB-1243] Show overview calendar if contributor

---

package.json

Updating grpc command to download binary

Updating grpc command to download binary and do verbose output

---

packages/past-reminders/components/PastRemindersPosts/index.jsx
packages/past-reminders/components/PastRemindersPosts/story.jsx
packages/past-reminders/index.js
packages/sent/components/SentPosts/index.jsx
packages/sent/components/SentPosts/story.jsx
packages/sent/index.js
packages/shared-components/PostList/index.jsx
packages/shared-components/PostList/story.jsx
packages/shared-components/PostLists/index.jsx

Team members and users in Pro and up plans are allowed to use Share Again in Past Reminders and Sent Posts. Contributors can't send mobile notifications in Past Reminders
[PUB-1241](https://buffer.atlassian.net/browse/PUB-1241)

[PUB-1241] Team Members are allowed to Share Again

---

packages/shared-components/PostList/index.jsx
packages/shared-components/PostLists/story.jsx

Fix behavior to allow all users but Contributors to use "Send to mobile" in Past Reminders

Sent to mobile for all users except contributors

---

packages/sent/components/SentPosts/index.jsx
packages/shared-components/PostFooter/index.jsx
packages/shared-components/PostList/index.jsx

Adding classes to ensure proper behavior for Bookmarklet app.

[PUB-1193] Adding classes to ensure proper behavior for Bookmarklet app.

---

packages/preferences/components/Preferences/index.jsx

Remove FeatureLoader from Billing tab, to make it available for all users
[PUB-1318](https://buffer.atlassian.net/browse/PUB-1318)

[PUB-1318] Remove FeatureLoader from Billing tab

---

packages/locked-profile-notification/index.js
packages/locked-profile-notification/index.test.jsx
packages/locked-profile-notification/reducer.js
packages/locked-profile-notification/reducer.test.js
packages/store/reducers.js

Add tests to Locked Profile Notification package.

Add tests to Locked Profile Notification package

---

README.md

Updating readme file with gRPC fix on dev environment.

---

packages/web/components/ErrorBoundary/style.jsx

- Adds visual polish to post item error boundary component

Adds visual polish for post level error boundary component

---

packages/drafts/components/DraftList/index.jsx
packages/drafts/index.js
packages/profile-page/components/ProfilePage/index.jsx
packages/profile-page/index.js
packages/shared-components/Draft/index.jsx
packages/shared-components/DraftFooter/index.jsx
packages/shared-components/ImageDraft/index.jsx
packages/shared-components/LinkDraft/index.jsx
packages/shared-components/MultipleImagesDraft/index.jsx
packages/shared-components/PostFooter/index.jsx
packages/shared-components/QueueItems/index.jsx
packages/shared-components/TextDraft/index.jsx
packages/shared-components/VideoDraft/index.jsx

Fixing bug for drafts pages and adding icon for first comment on drafts.

Bug fixing for first comment and drafts

---

jest.config.js
packages/sidebar/package.json
yarn.lock

Updated package with this change: https://github.com/bufferapp/buffer-js-app-sidebar/blob/master/CHANGELOG.md#1111---2019-04-12. 

Update app sidebar with new 1.11.1 version

---

packages/grid/components/GridPosts/index.jsx
packages/grid/middleware.js
packages/grid/util/index.jsx

Adding tracking data for link in bio and fixing isValidUrl method.

Adding tracking data for link in bio and fixing isValidUrl method.

---

packages/grid/components/GridPosts/index.jsx
packages/grid/middleware.js
packages/grid/middleware.test.js

Updating some details for grid page: copy on texts, url saving bug, adding tooltip.

Updating some details for grid page.

---

packages/grid/components/GridPosts/index.jsx
packages/shared-components/GridList/index.jsx
packages/tabs/components/TabNavigation/index.jsx

Fixing bug with copying link on Safari, changing input placeholder and tab name.

[PUB-1329] Fixing grid tab related bugs

---

packages/tabs/components/TabNavigation/index.jsx
packages/tabs/index.js

Adding validation to check if the user has business account.

Grid - Adding validation to check if the user has business account.

---

packages/tabs/components/TabNavigation/index.jsx
packages/tabs/index.js

Release Shop Grid to all business accounts

---

packages/shared-components/GridList/index.jsx

Fixing saving links when previously empty.

Fixing saving links when previously empty.

---

helm/buffer-publish.yaml
packages/analytics/components/AnalyticsList/index.jsx
packages/analytics/components/Notification/index.jsx
packages/analytics/index.js
packages/pusher-sync/package.json
packages/server/index.js
packages/server/package.json
yarn.lock

Add instagram advanced analytics

---

packages/grid/middleware.js
packages/grid/util/index.jsx
packages/queue/util/index.jsx
packages/tabs/utils/index.js

Fixing redirection issue with base url prefix

Fixing redirection issue with base url prefix

---

packages/drafts/components/Empty/index.jsx
packages/i18n/translations/en-us.json
packages/locked-profile-notification/components/LockedProfileNotification/index.jsx

Replace "Team Member" references by "User".
[PUB-1425](https://buffer.atlassian.net/browse/PUB-1425)

[PUB-1425] Replace team member copy

---

packages/general-settings/components/GeneralSettings/index.jsx
packages/general-settings/components/GeneralSettings/story.jsx
packages/general-settings/components/ShuffleQueue/index.jsx

Contributors should not be able to see the "Shuffle Queue" option.
[PUB-1433](https://buffer.atlassian.net/browse/PUB-1433)

Hide Shuffle Queue for Contributors

---

package.json
packages/composer-popover/package.json
packages/drafts/components/DraftList/index.jsx
packages/drafts/index.js
packages/drafts/reducer.js
packages/shared-components/ImageDraft/index.jsx
packages/shared-components/ImagePost/index.jsx
packages/shared-components/MultipleImagesDraft/index.jsx
packages/shared-components/MultipleImagesPost/index.jsx
yarn.lock

Adjusting thumbnails images styles to keep original aspect ratio.

[PUB-1415] Adjusting thumbnails images styles to keep original aspect ratio.

---

packages/b4b-trial-complete-modal/README.md
packages/b4b-trial-complete-modal/components/B4bTrialCompleteModal/index.jsx
packages/b4b-trial-complete-modal/components/B4bTrialCompleteModal/story.jsx
packages/b4b-trial-complete-modal/index.js
packages/b4b-trial-complete-modal/middleware.js
packages/b4b-trial-complete-modal/middleware.test.js
packages/b4b-trial-complete-modal/package.json
packages/b4b-trial-complete-modal/reducer.js
packages/i18n/translations/en-us.json
packages/modals/components/AppModals/index.jsx
packages/modals/middleware.js
packages/modals/reducer.js
packages/pusher-sync/package.json
packages/server/package.json
packages/server/rpc/cancelTrial/index.js
packages/server/rpc/upgradeToPro/index.js
packages/store/index.js
packages/store/reducers.js
yarn.lock

Adding a modal to display when a user completes a business trial.

[PUB-1176] Adding a modal to display when a user completes a business trial.

---

packages/preferences/components/Preferences/index.jsx

Remove Profile Sidebar from Preferences
[PUB-1461](https://buffer.atlassian.net/browse/PUB-1461)

[PUB-1461] Remove Profile Sidebar from Preferences

---

packages/change-password/package.json
packages/edit-email/package.json
packages/profile-sidebar/components/ProfileSearch/index.jsx
packages/profile-sidebar/components/ProfileSearch/story.jsx
packages/profile-sidebar/components/ProfileSidebar/index.jsx
packages/profile-sidebar/index.js
packages/profile-sidebar/package.json
packages/profile-sidebar/reducer.js
packages/profile-sidebar/reducer.test.js
yarn.lock

Adding search in sidebar with Buffer UI component.

[PUB-1391] Sidebar search for profiles

---

packages/profile-sidebar/components/ProfileSidebar/index.jsx

Updating amount of profiles necessary to be able to see profile search.

Updating amount of profiles necessary to be able to see profile search.

---

.storybook/webpack.config.js
packages/account-notifications/components/Notification/index.jsx
packages/account-notifications/components/Notifications/index.jsx
packages/change-password/components/ChangePassword/index.jsx
packages/close-account/components/CloseAccount/index.jsx
packages/date-time-preferences/components/SelectDayToStartTheWeek/index.jsx
packages/date-time-preferences/components/TimeFormatPreferences/index.jsx
packages/edit-email/components/EditEmail/index.jsx
packages/manage-apps-extras/components/AppsManager/index.jsx
packages/manage-apps-extras/components/ExtrasLinks/index.jsx
packages/preferences/components/General/index.jsx
packages/preferences/components/Security/index.jsx
packages/shared-components/Row/index.jsx
packages/two-factor-auth/components/PreferencesRow/index.jsx
packages/two-factor-auth/components/TwoFactorAuth/index.jsx

Update Preferences' button and text components to BDS. Why? It's a good place to start this migration to the new design system, and it’s gonna have more relevance with the easier access through the new AppShell.
[PUB-1463](https://buffer.atlassian.net/browse/PUB-1463)
The modals used in the Preferences page were still not updated: a couple of them are related to changing passwords and emails. There's been a discussion about removing some of those https://threads.com/34366424587, and right now some of the modals are not even being used (the buttons to edit email and password are redirecting to core).

[PUB-1463] Update ui components in preferences

---

packages/profile-sidebar/components/ProfileSidebar/index.jsx

Adjusting prop to correct value for profile sidebar.

Adjusting prop to correct value for profile sidebar.

---

packages/server/package.json
yarn.lock

Add necessary dependency to server package (coming from parsers package).

Add Twitter Text dependency for parsers in server package

---

packages/server/rpc/features/index.js
packages/server/rpc/grid/index.js

Fix dependency issue with RPC

---

packages/server/parsers/src/userParser.js
yarn.lock

[PUB-1492](https://buffer.atlassian.net/browse/PUB-1492)
When a user is on a trial and the trial has ended, the status of the trial is not set to completed, even though it has.
I'm using a flag as a stand-in for the fact that status is not set correctly for the time being, until I can fix it properly, and identify where the problem is really occuring.

PUB-1492 | Updating user parser to use trial_done flag to determine state of trial for expired modal

---

packages/server/parsers/src/userParser.js

Adding additional fields to debug live output

Adding additional fields to debug live output

---

README.md
packages/server/package.json
yarn.lock

Blank readme file

---

package.json
packages/analytics/components/ProfileHeader/index.jsx
packages/grid/components/GridPosts/index.jsx
packages/profiles-disconnected-modal/components/ProfilesDisconnectedModal/index.jsx
yarn.lock

Changing to the new Avatar component and updating ui package version.
This change fixes the bug "Avatar component is only showing default avatar in Safari"

[PUB-1480] Changing to the new Avatar component and updating ui package version.

---

packages/server/parsers/src/userParser.js

Revert "Adding additional fields to debug live output"

Revert "Adding additional fields to debug live output"

---

packages/thirdParty/middleware.js
packages/thirdParty/middleware.test.js

Fixed issue reported here: https://buffer.slack.com/archives/C151RRDL1/p1558607088275100.

Fix issue with HelpScout Beacon params

---

packages/app-shell/components/AppShell/index.jsx

Reverts bufferapp/buffer-publish#742
Confusion with older spec

Revert "Place org Admin menu items before NP in AppShell"

---

package.json
packages/profile-sidebar/components/ProfileList/index.jsx
packages/profile-sidebar/components/ProfileListItem/index.jsx
packages/profile-sidebar/components/ProfileListItem/story.jsx
packages/server/parsers/src/profileParser.js
yarn.lock

Add location field from profile object to show in the hover state when we have a location, only shown in some Facebook Pages.
Fix https://buffer.atlassian.net/browse/PUB-1506
To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and …

Add location to profiles in sidebar

---

packages/shared-components/ImagePost/index.jsx
packages/shared-components/LinkPost/index.jsx
packages/shared-components/MultipleImagesPost/index.jsx
packages/shared-components/Post/index.jsx
packages/shared-components/PostDragWrapper/index.jsx
packages/shared-components/TextPost/index.jsx
packages/shared-components/VideoPost/index.jsx

Fixing hover state for drag and drop update.
Jira card: [PUB-1456](https://buffer.atlassian.net/browse/PUB-1456)
This is a small fix, to prevent double border when dragging an update.
To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR …

Fixing hover state for drag and drop update.

---

packages/grid/components/GridPosts/index.jsx

Fix https://buffer.atlassian.net/browse/PUB-1518 by checking if the profile is a business account too.

Check if it's not a business account too in Shop Grid to prevent showing it

---

packages/composer-popover/package.json
yarn.lock

As described in the title.
This change is required for first comment changes made in the composer.
https://buffer.atlassian.net/browse/PUB-1439?atlOrigin=eyJpIjoiMjYxMWFjNGYyMjM1NDMyMGJmNjVhMDA4MzYzNTMzMjQiLCJwIjoiaiJ9 …

Update composer package to 3.4.8

---

packages/shared-components/Post/index.jsx
packages/shared-components/PostStats/index.jsx

Adding Impressions instead of Reach in dashboard for twitter

Hiding elements from Publish UI around mentions for pro users

---

packages/shared-components/PostList/index.jsx

Adding the current profile type to sent posts so that we can target it with app-cues more explicitly

Adding profile service class to output

---

packages/shared-components/PostList/index.jsx

Adding extra class logic to target retweets/non-retweets directly
This should allow us to target them using AppCues more explicitly

Adding extra class logic to target retweets directly

---

packages/i18n/translations/en-us.json
packages/ig-first-comment-start-trial-modal/components/InstagramFirstCommentStartTrialModal/index.jsx
packages/ig-first-comment-start-trial-modal/components/InstagramFirstCommentStartTrialModal/story.jsx
packages/ig-first-comment-start-trial-modal/index.js
packages/ig-first-comment-start-trial-modal/package.json
packages/modals/reducer.js
packages/queue/components/QueuedPosts/index.jsx

Create instagram first comment start trial modal
Subtask: https://buffer.atlassian.net/browse/PUB-1569
related to Free -> Pro Instagram Upgrade path story: https://buffer.atlassian.net/browse/PUB-1546
http://hi.buffer.com/cb0251698e9b …

[PUB-1569] Add instagram first comment start trial modal

---

packages/composer/composer/stores/ComposerStore.js

Fix issue reported on Slack by Karel: https://buffer.slack.com/archives/C151RRDL1/p1560849082052000

Fix issue when resetting drafts in composer

---

packages/composer/composer/tests/composerStore.test.js

Add test for https://github.com/bufferapp/buffer-publish/pull/782. 

Add test for issue with draft objects after refactoring

---

packages/composer/composer/components/Composer.jsx

Display first comment textarea if a user is a team member

---

packages/composer/composer/components/Composer.jsx

Hide pro tag for IG comment toggle if user is a teammate.
Added a few refactors from quick fix on Friday. (Related to JIRA https://buffer.atlassian.net/browse/PUB-1546)
To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and click …

Hide pro tag if user is a teammate

---

packages/i18n/translations/en-us.json
packages/shared-components/ScheduleTable/ScheduleTableCell/index.jsx
packages/shared-components/ScheduleTable/ScheduleTableHeader/index.jsx
packages/temporary-banner/components/TemporaryDashboardBanner/index.jsx
packages/upgrade-modal/components/PlanCycleSelect/index.jsx
packages/upgrade-modal/components/UpgradeModal/index.jsx
packages/web/components/ErrorBoundary/errorComponent.jsx
packages/web/components/ErrorBoundary/fallbackComponent.jsx
packages/welcome-b4b-trial-modal/components/WelcomeB4BTrialModal/index.jsx

Replace Icons, Text and Buttons by the BDS version.
**Places:**
- WelcomeB4BTrialModal
- ScheduleTable
- TemporaryDashboardBanner
- UpgradeModal
- ErrorBoundary
With the new Buffer Design System (BDS) we need to keep replacing old components by the new ones from bufferapp/ui.
[PUB-1590](https://buffer.atlassian.net/browse/PUB-1590)
**WelcomeB4BTrialModal:**
**ScheduleTable:**
**TemporaryDashboardBanner:**
**UpgradeModal:**
-   [x] I have …

[PUB-1590] Replace ui buttons and text components

---

packages/composer/composer/components/css/Editor.css

Remove shadow from Emoji Popover.
[PUB-1634](https://buffer.atlassian.net/browse/PUB-1634)
**Before:**
**After:** …

[PUB-1634] Remove shadow Emoji Popover

---

packages/server/index.html
packages/server/index.js

Roy uses data from the Qualaroo script to do customer research. 
The script was in Buffer Classic and is now needed in New Publish since we're moving more and more customers over to the new platform.
JIRA: https://buffer.atlassian.net/browse/PUB-1606?atlOrigin=eyJpIjoiM2ZkMjUzY2FiMjEwNDNiZGE2NDFmYTQ2MjFiYzljNGMiLCJwIjoiaiJ9
-   [x] I have commented my code, …

[PUB-1606] Add Qualaroo script to New Publish

---

packages/thirdParty/constants.js
packages/thirdParty/middleware.js

Add test flow ID too in order to test the fix for https://buffer.atlassian.net/browse/PUB-1607 without publishing the AppCues tour. …

Include test flow ID too for Pro Trial modal

---

packages/b4b-trial-complete-modal/components/B4bTrialCompleteModal/index.jsx
packages/b4b-trial-complete-modal/components/B4bTrialCompleteModal/story.jsx
packages/composer/composer/components/DateTimeSlotPicker.jsx
packages/composer/composer/components/ImageDescriptionInput.jsx
packages/composer/composer/components/Notification.jsx
packages/composer/composer/components/css/DateTimeSlotPicker.css
packages/queue/components/QueueItems/index.jsx

Replace Icons, Text and Buttons by the BDS version.
Places:
- B4BTrialCompleteModal (replace BDS button by bufferapp/ui, looks the same)
- QueuedItems
- Composer Datepicker
- Composer Save Description
- Composer CTA
With the new Buffer Design System (BDS) we need to keep replacing old components by the new ones from bufferapp/ui.
[PUB-1590](https://buffer.atlassian.net/browse/PUB-1590)
**QueuedItems:**
**Composer Datepicker:**
**Composer Save Description:**
**Composer CTA:**
-   [x] I have …

[PUB-1590] Replace old buttons by the ui buttons

---

package.json
packages/disabled-queue/components/DisabledQueue/index.jsx
packages/shared-components/ComposerInput/index.jsx
packages/shared-components/QueueButton/index.jsx
packages/shared-components/QueueButtonGroup/index.jsx
yarn.lock

Updating bufferapp/ui package and adding up the Tooltips to the disabled elements in the empty queue.
We are adding Tooltips to better explain the customers the actions that could take place when connecting accounts.
Tooltip on hover in the input to open the composer:
Tooltip on hover the calendar buttons:
Tooltip on hover the disabled tabs:
-   [x] I have …

[PUB-1611] Adding tooltips to disabled elements in empty queue

---

packages/shared-components/PostEmptySlot/index.jsx

Changing slot style cursor when there are no profiles.

Changing slot style cursor when there are no profiles.

---

packages/general-settings/components/LinkShortening/index.jsx

Add extra copy to Link Shortening to clear confusion on why LinkedIn still uses bit.ly
https://buffer.atlassian.net/browse/PUB-1621 …

[PUB-1621] Add extra copy to Link Shortening

---

packages/composer/composer/components/Composer.jsx
packages/composer/composer/components/ShopgridComposerBar.jsx
packages/composer/composer/components/TooltipList.jsx
packages/composer/composer/components/UpdateSaver.jsx
packages/composer/composer/lib/validation/ValidateDraft.js
packages/composer/composer/stores/AppStore.js
packages/composer/composer/stores/ComposerStore.js
yarn.lock

Adding shop grid link validation in the composer as it is on the grid page.
Jira bug -> https://buffer.atlassian.net/browse/PUB-1589 …

[PUB-1589] Shop grid link validation

---

packages/app-shell/reducer.js
packages/app-shell/reducer.test.js
packages/server/parsers/src/userParser.js
packages/tabs/index.js

Don't show upgrade / start trial CTA for business team members
Fix https://buffer.atlassian.net/browse/PUB-1624. …

Hide Upgrade CTA for business team members

---

packages/composer/interfaces/buffer-publish.jsx
yarn.lock

Users that are Team Members on a Business account should have access to the "Share Next" button in the composer
https://buffer.atlassian.net/browse/PUB-1622
To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and click "details" next …

[PUB-1622] Team members should see Share Next in the composer

---

packages/notifications-provider/utils/notifications.json

Add notification for another [PR on the backend](https://github.com/bufferapp/buffer-web/pull/16326) to fix https://buffer.atlassian.net/browse/PUB-1582.

Add notification for handling wrong IG account scenario

---

analyze.config.js
packages/store/index.js
packages/store/package.json
packages/store/reducers.js
packages/stripe/package.json
yarn.lock

Fix console error `Cannot read property 'loading' of undefined` by adding analyze profile-loader package to publish store
https://buffer.atlassian.net/browse/PUB-1667
The analyze date-picker package recently added the `profile-loader` state to their middleware. 
To visit the URL of …

[PUB-1667] Add analyze profile-loader to store

---

packages/server/parsers/src/profileParser.js

Adding organization id to the profile parser file.
In Hashtag manager task, for saving hashtags we require the Organization Id for the current profile. …

Adding organization id to the profile parser.

---

packages/server/rpc/createHashtagGroup/index.js
packages/server/rpc/deleteHashtagGroup/index.js
packages/server/rpc/getHashtagGroups/index.js

Just a quick fix for a missing import in the RPC packages. 

Fix error with import in RPC packages

---

packages/hashtag-group-manager/components/HashtagGroupCreator/index.jsx
packages/hashtag-group-manager/components/HashtagGroupItem/index.jsx
packages/hashtag-group-manager/components/HashtagGroupList/index.jsx
packages/hashtag-group-manager/components/HashtagGroupManager/index.jsx

Tweaking design items as per this thread: https://buffer.slack.com/archives/C151RRDL1/p1564055955196900
changed button text to "Delete Group"
changed Copy on sub-heading
adjusted the transition on hover to 0.3s when highlighting menu item
fixed width issue (which was related to overflow scrolling) to items are now fullwidth
fixed the hashtag number in list items staying closer to the group name (but please take a look at it with an overflowed name)
-   [ ] I have performed a self-review of my …

fixing up design issues with hashtag manager

---

packages/queue/util/index.jsx

Posts with past dates are not being displayed in the queue.
JIRA card [PUB-1636](https://buffer.atlassian.net/browse/PUB-1636) …

[PUB-1636] Fixing validation to display past posts in the queue.

---

packages/composer/composer/utils/TrackingUtils.js
packages/composer/composer/utils/WebAPIUtils.js

Format the date in Post Created event to ISO string and add shareType to event.

Format date and shareType properties in Post Created tracking

---

packages/hashtag-group-manager/reducer.js

Handling issue when user has no hashtag manager groups yet

Handling empty state.groups in hashtag manager code

---

packages/composer/composer/utils/TrackingUtils.js
packages/drafts/middleware.js

Ensure we're returning null if any segment values are undefined. Segment allows for null values but a violation occurs if value is undefined.  …

Return null for segment values if undefined

---

helm/buffer-publish.dev.yaml
helm/buffer-publish.yaml
packages/server/index.js
packages/server/middlewares/verifyAccessToken.js

Redirect user to login if missing valid access token

Redirect user to login if missing valid access token

---

helm/buffer-publish.dev.yaml
helm/buffer-publish.yaml
packages/server/index.js
packages/server/middlewares/verifyAccessToken.js

Add back logic for redirect if token is invalid

---

packages/server/middlewares/verifyAccessToken.js

Follow up of #855
- Allow up to 3 retries for checking the access token.
- Treat visits with skipSessionCheck=true as skipSessionCheck=1, in case they need to still regenerate a token, and thus unblocking some of the tickets we've seen.

Logout if token check fails 3 times in a row

---

packages/composer/composer/utils/TrackingUtils.js
packages/composer/composer/utils/WebAPIUtils.js
packages/globalAccount/reducer.js

- Only return the data needed for global account
- Use the more appropriate array method "find" for profiles
- Refactor to use map to get shareType method …

Refactor tracking util methods and only return global account state being used

---

packages/hashtag-group-manager/components/HashtagGroupManager/index.jsx

Fixing typo with hashtag manager text

Fixing typo with hashtag manager

---

packages/server/middlewares/verifyAccessToken.js

I will be deprecating the convert_access_token.json endpoint b/c we don't really need it anymore in the login service. It is too complex for what we really use it for, so I will be replacing it with a smaller endpoint.
So, let's user `user.json` here, it will serve the same purpose :) 
Buffer web PR: https://github.com/bufferapp/buffer-web/pull/16386

Use user.json endpoint and handle non-production env

---

packages/analytics-middleware/readme.md

Add readme for analytics-middleware package to help others get started

Add analytics-middleware readme

---

packages/notifications-provider/utils/notifications.json

Fix https://buffer.atlassian.net/browse/PUB-1765 by removing the notification completely. 

Remove pro trial notification

---

packages/composer/composer/components/App.jsx
packages/composer/composer/components/AppStateless.jsx
packages/composer/composer/components/Composer.jsx
packages/composer/composer/components/ComposerSection.jsx
packages/composer/interfaces/buffer-publish.jsx

Add draft mode prop to Composer
By passing a draft mode prop to the Composer, it will allow us to customize the Composer experience for drafts.
There's also some code linting in this PR.
To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this …

Add draft mode prop to Composer

---

packages/close-account/components/CloseAccount/index.jsx

Redirecting to FAQ so that users can delete their account.
Due to GDPR, we need a single place for users to delete their accounts globally and for publish.  Unfortunately our current copy in Publish is very misleading because it makes our users think that they are deleting their full account. …

[PUB-1842] Redirecting to FAQ so that users can delete their account.

---

packages/close-account/components/CloseAccount/index.jsx

Adding link to send email instead of FAQ page.

[PUB-1842] Adding link to send email instead of FAQ page.

---

packages/close-account/components/CloseAccount/index.jsx

Updating email to correct one.

Updating email to correct one.

---

packages/close-account/components/CloseAccount/index.jsx

Reverts bufferapp/buffer-publish#871

Revert "Updating email to correct one."

---

packages/close-account/components/CloseAccount/index.jsx

Revert changes from these three PRs:
https://github.com/bufferapp/buffer-publish/pull/869/files
https://github.com/bufferapp/buffer-publish/pull/870/files
https://github.com/bufferapp/buffer-publish/pull/871/files
https://buffer.slack.com/archives/C151RRDL1/p1565205008237700
To …

Revert close account changes

---

packages/close-account/components/CloseAccount/index.jsx
packages/close-account/components/Modal/index.jsx

Changing copies for deleting account.

[PUB-1884] Changing copies for deleting account

---

packages/thirdParty/components/RouteMonitor/index.jsx
packages/thirdParty/middleware.js
packages/trial/middleware.js

Add three more events tracked in Appcues to have better filters there: 
- Has an Instagram Business profile connected
- Has clicked the Shop Grid tab
- Started a trial via First Comment
JIRA Issue: https://buffer.atlassian.net/browse/PUB-1874. …

Add more events tracked in Appcues

---

package.json
yarn.lock

Updating buffer-ui version to 5.2.2
Updating to latest version of buffer-ui

Updating buffer-ui version to 5.2.2

---

packages/composer/composer/stores/AppStore.js

Fixing a bugsnag error
[[Bugsnag](https://app.bugsnag.com/buffer/publish-dashboard/errors/5d2ccdecbd6c970019b7001f?event_id=5d527ecd004cd215b3fa0000&i=sk&m=rm)]
[PUB-1892](https://buffer.atlassian.net/browse/PUB-1892) …

[PUB-1892] Fixing bugsnag error, profile undefined.

---

packages/modals/middleware.js
packages/server/parsers/src/userParser.js

Making sure expired trial modal shows up when trial is expired.

Display expired pro or business modal.

---

packages/i18n/translations/en-us.json
packages/plans/components/PlanColumn/index.jsx
packages/plans/components/PlanColumn/style.jsx
packages/plans/components/Plans/index.jsx
packages/plans/index.js

Add non profit cost case
Fix over-flow styles

Small refactors to pay day logic

---

packages/profile-sidebar/index.js
packages/profile-sidebar/reducer.js

Fix onboarding feature flip name.
Did some linting on the files as well.

Fix onboarding feature flip name

---

packages/profile-sidebar/index.js
packages/profile-sidebar/reducer.js
packages/profile-sidebar/reducer.test.js

Move onboarding feature to reducer

Change feature placement

---

packages/drafts/middleware.js
packages/drafts/middleware.test.js
packages/drafts/reducer.js
packages/profile-page/index.js
packages/profile-sidebar/middleware.js

Reverts bufferapp/buffer-publish#888

Revert "[PUB-1701] Calling get drafts only on fetch profiles success to prevent calling …"

---

packages/drafts/middleware.js
packages/drafts/middleware.test.js
packages/drafts/reducer.js
packages/profile-page/index.js
packages/server/rpc/draftPosts/index.js

Reverts bufferapp/buffer-publish#893

Revert "[PUB-1701] Draft tabs content loading"

---

packages/composer/composer/stores/ComposerStore.js
packages/composer/composer/tests/composerStore.test.js
packages/composer/composer/tests/stubData.js

Fix https://buffer.atlassian.net/browse/PUB-1928 by counting FB characters too.
-   [] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [] I have commented my code, particularly in hard-to-understand areas.

Fix missing count for Facebook profiles

---

packages/drafts/middleware.js
packages/drafts/middleware.test.js
packages/drafts/reducer.js
packages/profile-page/index.js
packages/profile-sidebar/middleware.js
packages/profile-sidebar/middleware.test.js
packages/server/rpc/draftPosts/index.js

Removing condition for checking profileID that was causing problems with the composer on Edit action.

Load more drafts fix and preventing composer issue

---

packages/i18n/translations/en-us.json
packages/switch-plan-modal/components/SwitchPlanModal/index.jsx

Change modal header copy for upgrade/downgrading plans from "Switch to" to "Subscribe to"
https://buffer.atlassian.net/browse/PUB-1929 …

[PUB-1929] Change modal header and button copy to "Subscribe"

---

packages/analytics-middleware/utils/Pathname.js
packages/analytics-middleware/utils/Pathname.test.js

Return path string for name with page view tracking if cases aren't met. 

Return path for page viewed name property if cases are not met

---

packages/shared-components/CardFooter/index.jsx
packages/shared-components/CardFooter/story.jsx
packages/shared-components/PostFooter/index.jsx
packages/shared-components/PostFooter/story.jsx
packages/shared-components/PostList/test.jsx

Create a fully Presentational Component to render the Footer, no matter what type of card (either Story, Post or Draft)
- With the creation of Stories, we would be adding the same logic for the third time. This presentational component allows us to have all the styles in one place (making the consistency easier to maintain) and it allows us to adapt the existing code without major changes.
- There's also no need for so much prop drilling: some props being passed just to show delete buttons are replaced by the use of useState (react hooks)
- Allows us to have the entire Footer with BDS
- This PR includes the adaptation of PostFooter. 
**Next Septs (different PR, after deploying this):** 
- Do the same with Drafts Footer
- Remove PostFooterButtons and PostFooterDelete from codebase
- Remove …

Normalize Posts/ Drafts/ Stories Footer

---

packages/shared-components/Card/index.jsx
packages/shared-components/CardHeader/index.jsx
packages/shared-components/CardHeader/story.jsx
packages/shared-components/Story/index.jsx
packages/shared-components/Story/story.jsx

Add Story Component
[PUB-1960](https://buffer.atlassian.net/browse/PUB-1960)

[PUB-1960] Add Story Element

---

packages/server/parsers/src/storyGroupParser.js

Added author name and avatar to story group parser.

[PUB-1935] Added author name and avatar to story group parser.

---

packages/story-preview/components/EditNote/index.jsx
packages/story-preview/components/NoteWrapper/index.jsx
packages/story-preview/components/NoteWrapper/story.jsx
packages/story-preview/components/PreviewPopover/index.jsx
packages/story-preview/components/ViewNote/index.jsx
packages/story-preview/index.js
packages/story-preview/package.json

Add right column in Story Preview Panel: it has two view modes, view note and edit/add note.
[PUB-1922](https://buffer.atlassian.net/browse/PUB-1922)
With note: https://hi.buffer.com/bd08ff74229a
Without note: https://hi.buffer.com/c233565f149e …

[PUB-1922] Add Note View in Preview Story

---

packages/shared-components/Arrow/index.jsx
packages/shared-components/Arrow/story.jsx
packages/shared-components/Carousel/index.jsx
packages/shared-components/Carousel/style.js

New Arrow component.
Since we are using the Arrows in more than one place, we decided to create an isolated component for it.
<a href="http://hi.buffer.com/93d599a95e15" target="_blank"><img src="https://d2ddoduugvun08.cloudfront.net/items/2319191j3l2k2q3H0J1o/Image%202019-09-11%20at%202.05.41%20PM.png" style="display: block;height: auto;width: 100%;"/></a> …

Creating Arrow component

---

packages/shared-components/LightboxCarousel/index.jsx
packages/shared-components/index.js

Create Preview Carousel as a shared component, so it can be reused in the future if needed
To be used in the Preview Wrapper: [PUB-1920](https://buffer.atlassian.net/browse/PUB-1920)
To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR …

Add Preview Carousel

---

packages/shared-components/Carousel/style.js
packages/shared-components/Story/index.jsx
packages/story-group-composer/components/CarouselCards/index.jsx
packages/story-group-composer/components/CarouselCards/styles.jsx
packages/story-group-composer/components/StoryGroupPopover/index.jsx
packages/story-group-composer/components/StoryGroupWrapper/index.jsx
packages/story-group-composer/index.js
packages/story-group-composer/reducer.js

I've stopped the carousel card from using a background image, as it was causing repaints and throttling in the render when you interacted with an uploading carousel, and instead using an Image with src and css object-fit to create the same effect.
Swapped out the Loader component for video loading with the LoadingAnimation as it seems more performant and reduces thrashing in the UI
You can still see some tearing occuring on the video, and some render performance issues I need to investigate further, but its definitely heading in the right direction from where it was (see screenshot)
http://hi.buffer.com/ddf45f4e1349
-   [ ] I …

Implementing Image upload events + modifying carousel card to no longer use a background image

---

packages/story-group-composer/components/Carousel/CardItem/index.jsx
packages/story-group-composer/components/StoryGroupWrapper/index.jsx

Adding missing props to CardItem to prevent upload fail.

Adding missing props to prevent upload fail.

---

packages/story-group-composer/components/Carousel/CardDragWrapper/index.jsx
packages/story-group-composer/components/Carousel/CarouselCardHover/index.jsx
packages/story-group-composer/index.js
packages/story-group-composer/reducer.js

Refresh stories on story delete.
On deleting a story, reordering cards to prevent duplication on more uploads.

Refresh stories on story delete

---

packages/composer/package.json
packages/grid/middleware.js
packages/grid/middleware.test.js

Only make a gridPosts request when the profile is Instagram.
https://buffer.atlassian.net/browse/PUB-2002
https://hi.buffer.com/71393228b7a3 …

[PUB-2002] Fix 500 errors in gridPosts requests

---

packages/notifications-provider/utils/notifications.json

Add new generic notification for now when trial starts.

Add new success message when trial starts

---

packages/server/rpc/shareStoryGroupNow/index.js
packages/stories/middleware.js
packages/stories/reducer.js

Fix small issue with type of request and params for sharing now a story group.

Fix share now endpoint integration

---

packages/story-group-composer/components/StoryGroupPopover/index.jsx
packages/story-group-composer/components/StoryGroupWrapper/index.jsx
packages/story-group-composer/index.js
packages/story-group-composer/reducer.js

Adding Instagram Stories Error Messages to the UI

Show Errors in Instagram Stories composer UI

---

packages/server/rpc/createStoryGroup/index.js

Use form in the RP request instead of passing everything in the URL.

Fix create now story group request with right format

---

packages/story-group-composer/components/StoryGroupPopover/index.jsx
packages/story-group-composer/components/StoryGroupWrapper/index.jsx
packages/story-group-composer/index.js
packages/story-group-composer/middleware.js
packages/story-group-composer/reducer.js

Setting max stories to 10 as 15 was tooooooo many!!!

Limiting number of stories to 10 max

---

packages/i18n/translations/en-us.json
packages/story-group-composer/components/Carousel/CardItem/index.jsx
packages/story-group-composer/components/Carousel/CarouselCardHover/index.jsx
packages/tabs/components/TabNavigation/index.jsx

- Change note cancel text to back
- Change text and icon for upload media button
- Change add note hover button to small size
- Move stories tab to after queue
To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and click "details" …

Change text and button for story group and move stories tab

---

packages/story-preview/index.test.js
packages/story-preview/middleware.test.js
packages/story-preview/reducer.test.js

Add tests to preview popover

---

packages/server/rpc/updateStoryGroup/index.js

The update request needs to follow the same format that others requests with bodies.

Fix update story group endpoint with form

---

packages/story-group-composer/components/AddStoryFooter/index.jsx
packages/story-group-composer/components/StoryGroupWrapper/index.jsx
packages/story-group-composer/reducer.js
packages/story-group-composer/utils/AddStory.js
packages/story-group-composer/utils/AddStory.test.js

Format the date to include timezone when clicking on empty slot or editing storyGroup. 

Add timezone to datepicker calendar formats

---

package.json
packages/story-group-composer/components/NoteSection/index.jsx
packages/story-preview/components/EditNote/index.jsx
packages/story-preview/components/ViewNote/index.jsx
yarn.lock

Replace Stories textareas by BDS TextArea component.
Update bufferapp/ui version to get TextArea component.

Replace textarea component by BDS

---

packages/story-group-composer/components/StoryGroupWrapper/index.jsx

Changing composer width to 728px in order to prevent cutting off button in 3 cards scenario.

Changing composer width to 728

---

packages/i18n/translations/en-us.json
packages/story-preview/components/EditNote/index.jsx
packages/story-preview/components/NoteWrapper/index.jsx
packages/story-preview/components/PreviewPopover/index.jsx
packages/story-preview/components/ViewNote/index.jsx
packages/story-preview/index.js
packages/story-preview/index.test.js
packages/story-preview/utils/commonPropTypes.js
packages/story-preview/utils/commonPropTypes.test.js

Add translations to story preview.

Add translations to story preview

---

packages/shared-components/Carousel/style.js
packages/story-group-composer/components/Carousel/CardItem/index.jsx
packages/story-group-composer/components/Carousel/CardItem/styles.jsx
packages/story-group-composer/components/Carousel/CarouselCardHover/style.js
packages/story-group-composer/components/HeaderBar/index.jsx

Styling drag and drop.
- Adding top and bottom border on isOver event.
- Changing target opacity.

Styles fixes for drag-n-drop.

---

packages/shared-components/CardFooter/index.jsx

Fixing styling for the card footer.
Comment from Andy in our paper doc: Minor thing. The bottom bar seems to clip the shadow of the update cards as its not rounded.
Footer on Story tab:
Footer in the queue:
To visit the URL of the staging deployment, please click "Show all checks" …

Fixing border radius for card footer.

---

README.md

Change `core-authentication-service` to `authentication-service` in the readme guide.

Tiny change to readme

---

packages/i18n/translations/en-us.json
packages/stories/components/StoryGroups/index.jsx
packages/stories/components/StoryGroups/story.jsx
packages/stories/index.js
packages/story-group-composer/components/Carousel/CardItem/index.jsx
packages/story-group-composer/components/Carousel/CarouselCardHover/index.jsx
packages/story-group-composer/components/Carousel/CarouselCards/index.jsx
packages/story-group-composer/components/StoryGroupWrapper/index.jsx
yarn.lock

Adding translations for story group composer and queue.

Adding translations for story group composer and queue.

---

packages/story-preview/components/PreviewMedia/index.jsx

Replace Video `<source>` tag by `src` attribute.

Replace source tag by src in videos

---

helm/buffer-publish.dev.yaml
helm/buffer-publish.yaml

Replace `API_ADDR` and `ANALYZE_API_ADDR` values by internal URLs, both for prod and dev.

Change env API_ADDR variables

---

packages/analytics-middleware/readme.md
packages/constants/index.js
packages/i18n/translations/en-us.json
packages/plans/index.js
packages/story-group-composer/middleware.js
packages/story-group-composer/middleware.test.js
packages/story-group-composer/utils/Tracking.js

- Add `Story Group Created` tracking for story-group-composer
- Add `Story Group Updated` tracking for story-group-composer
- Fix typo in preview text
- Remove `product` property from plans tracking
[Updated - Done] There might be some nomenclature changes with the event name (`Story Created` to `StoryGroup Created` & `Story Updated` to `StoryGroup Updated`) so will wait for change to deploy. 
Locally, no violations 💃https://hi.buffer.com/0df5983bf6cf
Ana - do you have any thoughts on a general utils? 
https://buffer.atlassian.net/browse/PUB-2024
https://buffer.atlassian.net/browse/PUB-2022
https://buffer.atlassian.net/browse/PUB-2023
-   [x] All new and existing tests …

[PUB-2022] Add tracking for story group created and updated

---

package.json
packages/profile-page/index.js
packages/profile-page/index.test.js
packages/stories/middleware.js
packages/stories/middleware.test.js
packages/story-group-composer/middleware.js
yarn.lock

- Refactoring onLoadMore method to be more readable by removing the switch case statement and replacing it with an Object literal.
- Fixes on load more bug for story groups queue.
JIRA card -> [PUB-2053](https://buffer.atlassian.net/browse/PUB-2053) …

[PUB-2053] Story group queue on load more fix

---

packages/constants/index.js
packages/story-group-composer/index.js
packages/story-group-composer/middleware.js
packages/story-group-composer/middleware.test.js
packages/story-group-composer/reducer.js
packages/story-group-composer/utils/Tracking.js
packages/story-preview/index.js
packages/story-preview/middleware.js
packages/story-preview/reducer.js

Add segment tracking for adding a story note
https://buffer.atlassian.net/browse/PUB-2010

[PUB-2010] Add segment tracking for adding a story note

---

packages/story-group-composer/index.js

Fixing issue with reordering cards

---

packages/composer/composer/stores/AppStore.js

Adding an extra validation to fix 3 bugsnag issues.
Jira ticket (contains the 3 bugsnag links) -> [PUB-2013](https://buffer.atlassian.net/browse/PUB-2013) …

[PUB-2013] Fixing bugsnag bug.

---

packages/profile-sidebar/index.js

Adding validation for bugsnag error.

---

packages/constants/index.js
packages/modals/components/AppModals/index.jsx
packages/modals/middleware.js
packages/modals/middleware.test.js
packages/modals/reducer.js
packages/modals/util/showModal.js
packages/server/formatters/src/getURL.js
packages/stories-promo-modal/components/StoriesPromoModal/index.jsx
packages/stories-promo-modal/components/StoriesPromoModal/story.jsx
packages/stories-promo-modal/index.jsx
packages/stories-promo-modal/package.json

Add Stories Promo Modal, to be shown once for Free users who are not team members in business accounts.
This is a temporary modal, to be deleted once the hype around stories decreases.
https://buffer.atlassian.net/browse/PUB-2034
To visit the URL of the staging deployment, please …

[PUB-2034] Add stories promo modal

---

packages/i18n/translations/en-us.json
packages/stories/components/StoryGroups/index.jsx
yarn.lock

Add hyperlink to "Reminder" that points to our FAQ article about scheduling Instagram Stories. Opens in new tab
https://buffer.atlassian.net/browse/PUB-2073
Karel, let me know if you have a better suggestion with adding links to translations and I can go back and refactor. :) 
To …

[PUB-2073] Add FAQ link for stories reminder message

---

packages/switch-plan-modal/index.js

Add payday source to switchPlanModal store to fix tracking issue with payday.
https://buffer.atlassian.net/browse/PUB-2011 …

[PUB-2011]Fix payday tracking to include cta

---

packages/i18n/translations/en-us.json

Adding a bullet for stories on the payday page.
This change is required because we're doing an e-mail campaign with Free users and want to make them aware of the feature.
To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and click …

Add stories to payday page

---

packages/story-group-composer/components/AddNote/index.jsx

Adding missing safe image to the UI output

Adding missing safe image to the UI output

---

packages/server/parsers/src/userParser.js
packages/temporary-banner/components/TemporaryDashboardBanner/index.jsx
packages/temporary-banner/index.js

Reverts bufferapp/buffer-publish#1022

Revert "Add LinkedIn banner for new permissions"

---

packages/notifications-provider/utils/notifications.json

Adding the possibility of passing a success message after oauth flow.

Add successful connection message

---

packages/stories-promo-modal/components/StoriesPromoModal/index.jsx

Add dismiss button to Stories Promo Modal
There are reports of users not being able to dismiss the modal, mainly because it's not clear that clicking outside of it will close it. I've added a dismiss text button to provide some clarification. …

Add dismiss button to Stories Promo Modal

---

packages/profile-sidebar/components/ProfileSidebar/index.jsx

Add some CTAs to sidebar for profiles connected from there. Related to: https://buffer.atlassian.net/browse/PUB-1877. …

Add CTA for tracking profiles connection

---

packages/profile-sidebar/components/ProfileSidebar/index.jsx

Following Julian's instructions here: https://buffer.atlassian.net/browse/PUB-1877, I modified the CTAs for the sidebar when the user attempts to connect a profile in the buttons.
Related JIRA issue: https://buffer.atlassian.net/browse/PUB-1877. …

Change CTA for sidebar profile connection

---

packages/composer/composer/utils/WebAPIUtils.js

We changed the error message being shown for mention fails to be more specific to the permissions issue. Now that it's fixed, changing back to original message.
To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and click "details" …

Change back error message from permissions issue

---

packages/modals/middleware.js
packages/modals/util/showModal.js

Add premium and small business upgrade modal url.
Available urls to open the upgrade modal:
- `publish.buffer.com/?mk=upgrade-to-pro`
- `publish.buffer.com/?mk=upgrade-to-premium`
- `publish.buffer.com/?mk=upgrade-to-small`
https://buffer.atlassian.net/browse/PUB-2092
To visit the …

[PUB-2092] Add premium and small business upgrade modal url

---

helm/buffer-publish.yaml

Adjust cpu req/limit based on actual usage
The CPU req and limit parameter. The avg is around 100-200 http://hi.buffer.com/fa2f6d99f007, and the max should be limited to 400m http://hi.buffer.com/3da484fd6ccf to cover most of the cases. …

Adjust cpu req/limit based on actual usage

---

packages/hashtag-group-manager/components/HashtagGroupItem/index.jsx
packages/hashtag-group-manager/components/HashtagGroupList/index.jsx
packages/hashtag-group-manager/components/HashtagGroupWrapper/index.jsx
packages/hashtag-group-manager/index.js
packages/hashtag-group-manager/middleware.js
packages/hashtag-group-manager/reducer.js
packages/hashtag-group-manager/utils/HashtagCounter.js

Apart from fixing the prettier issues, these changes add the tracking
in Segment for 3 actions with Hashtag groups:
- Create
- Delete
- Insert in comment box.
JIRA ticket: https://buffer.atlassian.net/browse/PUB-1846. …

Added tracking for actions in Hashtag Groups

---

packages/composer/composer/components/MediaAttachmentThumbnail.jsx
packages/composer/composer/stores/ComposerStore.js

Fixing issue with userTags on uploader

---

packages/composer-user-tags/components/UserTags/index.jsx
packages/composer-user-tags/index.js
packages/composer/composer/components/InstagramUserTags.jsx

https://buffer.atlassian.net/browse/PUB-2161
Add tracking events:
- `Instagram Tags Saved`
- `Instagram User Tagged`
Tracking plan: https://github.com/bufferapp/tracking-plan/blob/master/tracking-plans/buffer-tracking-plan/events/product/publish/instagram-tags-saved.yaml
To visit …

[PUB-2161] Add tracking for user tags

---

babel.config.js
package.json
packages/composer-user-tags/components/ImageLabel/index.jsx
packages/composer-user-tags/components/TagInput/index.jsx
packages/composer-user-tags/components/TagListItem/index.jsx
packages/composer-user-tags/components/TagListItem/style.js
packages/composer-user-tags/components/UserTags/index.jsx
packages/composer-user-tags/components/UserTags/style.js
packages/composer/composer/components/css/App.css
packages/composer/composer/components/css/Composer.css
packages/composer/composer/components/css/LinkAttachment.css
packages/composer/composer/components/css/LinkAttachmentTextEditor.css
yarn.lock

* Autofocus the input when clicking to tag (updated @bufferapp/ui for this)
* Keep the input hidden until clicking to tag, then hide it after a tag is added
* Add the tag when 'Enter' is pressed
* Update style of Person icon (for toggling showing tags)
* Always show tags when one is added (in case they were hidden)
* Expand height of tags lists when tag input is not showing …

[PUB-2130] Autofocus tag input and submit on enter

---

.storybook/preview-head.html
packages/composer-user-tags/components/TagInput/index.jsx
packages/composer-user-tags/components/UserTags/index.jsx
packages/composer-user-tags/components/UserTags/story.jsx
packages/composer-user-tags/components/UserTags/style.js

Fixes https://buffer.slack.com/archives/C151RRDL1/p1572470172270700?thread_ts=1572469796.268200&cid=C151RRDL1

Fix user tagging submit in firefox

---

packages/composer-user-tags/components/ImageLabel/index.jsx
packages/composer-user-tags/components/TagInput/index.jsx
packages/composer-user-tags/components/TagInput/style.js
packages/composer-user-tags/components/UserTags/index.jsx
packages/composer-user-tags/components/UserTags/style.js
packages/i18n/translations/en-us.json
packages/shared-components/CardFooter/index.jsx
packages/shared-components/ImagePost/index.jsx
packages/shared-components/Post/index.jsx
packages/shared-components/PostFooter/index.jsx

* Show tag input as form [1]
* Show icon in queue denoting post with user tags [2]
* [1] https://buffer.atlassian.net/browse/PUB-2168
* [2] https://buffer.atlassian.net/browse/PUB-2169
To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this …

[PUB-2168] Use popup for tagging IG users / tag icon in queue

---

packages/composer-user-tags/components/TagInput/index.jsx
packages/composer-user-tags/components/UserTags/index.jsx
packages/composer-user-tags/components/UserTags/style.js
packages/i18n/translations/en-us.json

Add an input error message if user tries to tag the same ig username twice in a post. 
https://buffer.atlassian.net/browse/PUB-2171
http://hi.buffer.com/b7cfd5661270 
To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and click …

[PUB-2171] Only allow user to tag one username in a post

---

packages/composer/composer/utils/WebAPIUtils.js

https://buffer.atlassian.net/browse/PUB-2170

[PUB-2170] Clear user tags in backend when they're all removed

---

packages/composer-user-tags/components/TagInput/index.jsx

https://buffer.atlassian.net/browse/PUB-2174

[PUB-2174] Filter characters in user tag input

---

packages/story-group-composer/index.js
packages/story-group-composer/reducer.js

Add warning message for video maxlength

---

packages/server/parsers/src/userParser.js

Removing the feature flip check to bump the rollout to 100%.
* https://buffer.atlassian.net/browse/PUB-2177

[PUB-2177] Instagram User Tagging 100% Rollout

---

packages/i18n/translations/en-us.json

See slack thread: https://buffer.slack.com/archives/C151RRDL1/p1572998825451400

Copy tweaks

---

packages/shared-components/PostList/index.jsx

* https://buffer.atlassian.net/browse/PUB-2179

[PUB-2179] Only show analyze banner once

---

packages/server/index.html
packages/server/index.js
packages/thirdParty/middleware.js
packages/thirdParty/reducer.js

Adding Iterate script and removing qualaroo script to our codebase

 PUB-2142 | Implementing Iterate script and removing qualaroo

---

.codeclimate.yml

Updating code climate settings to reduce threshold for `similar code` property.
Jira Card -> [PUB-1997](https://buffer.atlassian.net/browse/PUB-1997) …

[PUB-1997] Updating code climate settings

---

packages/thirdParty/components/Loader/index.jsx
packages/thirdParty/components/RouteMonitor/index.jsx
packages/thirdParty/index.js

Sending through a custom showModals property to appcues to try to address the issue around showing modals when we are on a profile …

PUB-2102 Send custom property to appcues

---

packages/grid/components/GridPosts/index.jsx
packages/grid/index.js
packages/grid/middleware.js
packages/grid/middleware.test.js
packages/grid/reducer.js
packages/grid/util/index.jsx

Add segment tracking for shop grid
- Shop Grid Page Previewed
- Shop Grid Post URL Updated
- Shop Grid Page Link Copied
https://buffer.atlassian.net/browse/PUB-2088
Currently passing in segment
To visit the URL of the staging deployment, please click "Show all checks" at the bottom …

Add segment tracking for shop grid

---

packages/drafts/middleware.js
packages/drafts/middleware.test.js

- Add tracking event `Draft Rejected`
- Add clientName property to all draft tracking events
https://buffer.atlassian.net/browse/PUB-2089 …

[PUB-2089] Add tracking for drafts

---

packages/composer/composer/components/App.jsx
packages/composer/composer/components/AppStateless.jsx
packages/composer/composer/components/Composer.jsx
packages/composer/composer/components/ComposerSection.jsx
packages/composer/composer/stores/AppStore.js
packages/composer/composer/tests/utils/profile-filtering.test.js
packages/composer/composer/utils/DataImportUtils.js
packages/composer/composer/utils/profile-filtering.js
packages/server/parsers/src/userParser.js

Refactored and improved logic for showing hashtag manager, based on the selected profiles.

[PUB-1872] Fix logic for showing hashtag manager

---

packages/credit-card-form/components/CreditCardForm/form.jsx
packages/credit-card-form/components/CreditCardForm/index.jsx
packages/credit-card-form/index.js
packages/profile-sidebar/components/ProfileDragWrapper/index.jsx
packages/profile-sidebar/components/ProfileListItem/index.jsx
packages/server/index.js
packages/switch-plan-modal/components/SwitchPlanModal/story.jsx

Increase loading speed, by making Stripe script Async and loaded with lower priority

Increase loading speed, by making Stripe script Async and loaded with lower priority

---

packages/server/index.js
packages/thirdParty/components/RouteMonitor/index.jsx
packages/thirdParty/middleware.js

Lazy load Appcues javascript so that it doesn't block the publish code from loading, and speeds up loading times for users …

Lazy loading Appcues code

---

packages/server/index.html

Moving  scripts back out of head, as performance appears negatively impacted... will investigate more tomorrow

Revert "Moving scripts out of the document head to prevent them from blocking rendering and loading"

---

packages/composer/composer/components/Editor.jsx

- Refactored a bit the handlePastedText method to convey the method's meaning.
- Validated that the text exists before pasting to prevent bug.
Jira card -> [PUB-2119](https://buffer.atlassian.net/browse/PUB-2119) …

[PUB-2119] Bugsnag - Handle text paste on Editor bug fix

---

packages/server/index.html

Moving scripts out of the document head to prevent them from blocking rendering and loading

Moving scripts out of the document head to prevent them from blocking rendering and loading

---

packages/server/index.html

Adding back pre-connect calls to publish code

---

packages/server/index.html

Adding back bufferUser data to speed up boot time

Adding back bufferUser data to speed up boot time

---

packages/credit-card-form/components/CreditCardForm/index.jsx
packages/server/index.js
packages/server/webpack.config.prod.js

Tidying up performance changes into more friendly / readable code

---

packages/grid/index.js
packages/grid/middleware.js
packages/grid/reducer.js
packages/server/parsers/src/profileParser.js
packages/server/rpc/shopGrid/customLinks/update/index.js

- Adding custom link contrast color option to update rpc.
- Including new field in profile parser.

Adding custom link contrast color option to rpc

---

Dockerfile
packages/server/index.html
packages/server/index.js

I think this fixes the remaining issue with your PR, by inlining the script for runtime.js on live, and using the file from webpack on local. The file is now included in the docker file with the build.
I'll leave this one for you to merge into your branch if you are happy with it, and hope its all okay with you. …

Use runtime.js script from webpack or from static CDN

---

packages/shared-components/ColorPicker/components/ColorSelectorPopup/index.jsx
packages/shared-components/ColorPicker/index.jsx
packages/shared-components/ColorPicker/story.jsx
packages/shared-components/ColorPicker/styles.js

- Styling color picker selector to figma styles.
- Fix for edge case for smaller screens and color swatches preview being cut. …

Color Picker fixes

---

package.json
packages/app-pages/components/AppPages/index.jsx
packages/profile-page/components/ProfilePage/index.jsx
packages/web/components/App/index.jsx
yarn.lock

Replace react-router by react-router-dom, the package recommended for web apps.

Replace react-router by react-router-dom

---

packages/grid/reducer.js

Fixing issue where customLinks is null/undefined on live

---

packages/grid/components/CustomLinks/EditingLinkForm/index.jsx
packages/grid/components/CustomLinks/LinkDragWrapper/index.jsx
packages/grid/middleware.js
packages/grid/reducer.js

Drag and swap to reorder top links
JIRA card -> [PUB-2219](https://buffer.atlassian.net/browse/PUB-2219)

[PUB-2219] Persisting drag and drop for top links.

---

packages/composer/composer/components/InstagramFeedback.jsx
packages/composer/composer/components/css/InstagramFeedback.css

Change Instagram warning styles in the composer.
[PUB-2261](https://buffer.atlassian.net/browse/PUB-2261)

[PUB-2261] Change composer IG warnings style to match BDS

---

packages/grid/reducer.js

Adding default values to customLinks so the app doesn't crash if it all goes wrong in reducers

Adding default values to customLinks so the app doesn't crash if it all goes wrong in reducers

---

packages/grid/components/CustomLinks/EditingLinkForm/index.jsx
packages/grid/components/CustomLinks/LinkDragWrapper/index.jsx
packages/grid/components/CustomLinks/LinkPreview/index.jsx
packages/grid/components/CustomLinks/LinksHeader/index.jsx
packages/grid/components/CustomLinks/index.jsx
packages/grid/components/CustomLinks/styles.js

Improving and polishing top links.
- Replacing Tooltip for BDS one.
- Truncating link preview text with ellipsis.
- Adding confirmation buttons on delete. …

Top link improvements

---

packages/i18n/translations/en-us.json
packages/modals/reducer.js
packages/plans/components/PlanColumnWithPremiumSolo/index.jsx
packages/plans/components/PlanColumnWithPremiumSolo/style.jsx
packages/plans/components/Plans/index.jsx
packages/plans/index.js
packages/plans/utils/plans.js
packages/server/parsers/src/userParser.js
packages/switch-plan-modal/components/PlanCycleSelect/index.jsx
packages/switch-plan-modal/components/SwitchPlanModal/index.jsx
packages/switch-plan-modal/index.js
packages/switch-plan-modal/reducer.js

Design change for Awesome to Pro promotional discount.
https://buffer.atlassian.net/browse/PUB-2249

[PUB-2249] Implement promo page design

---

packages/grid/components/CustomLinks/EditingLinkForm/index.jsx
packages/grid/components/CustomLinks/index.jsx
packages/grid/components/GridPosts/index.jsx
packages/grid/index.js
packages/grid/reducer.js

For top links, on cancel edit, discard current changes.
When making changes for a link and hitting cancel, discard the latest changes. …

Top links, on cancel edit, discard current changes.

---

packages/server/lib/bugsnag.js
packages/thirdParty/middleware.js
packages/thirdParty/middleware.test.js

* https://buffer.atlassian.net/browse/PUB-2272

[PUB-2272] Tag users in appcues who upgraded to pro from legacy awesome

---

packages/queue/components/QueuedPosts/index.jsx
packages/queue/components/RemindersBanner/index.jsx
packages/queue/components/RemindersBanner/story.jsx
packages/queue/index.js
packages/server/parsers/src/profileParser.js
packages/shared-components/QueueBanner/index.jsx
packages/shared-components/QueueBanner/story.jsx
packages/shared-components/index.js
yarn.lock

- Add Queue Banner to shared-components, to be reused when necessary.
- Add Reminders Banner to queue components, related to our ongoing task Instagram Connection 3.0
- Display Reminders Banner when user has at least one Reminder scheduled in the queue and no push notifications.
- Add `hasPushNotifications` to profileParser and set it temporarily to true while waiting for the backend changes.
[PUB-2265](https://buffer.atlassian.net/browse/PUB-2265)
-   [x] I have performed a self-review of my …

[PUB-2265] Add queue banner 

---

packages/grid/components/GridPosts/index.jsx

Add Posts title and tooltip to Shopgrid.
[PUB-2286](https://buffer.atlassian.net/browse/PUB-2286)

[PUB-2286]Add posts title and tooltip to shop grid

---

packages/grid/components/CustomLinks/EditingLinkForm/index.jsx
packages/grid/components/CustomLinks/LinkPreview/index.jsx
packages/grid/components/CustomLinks/LinksHeader/index.jsx
packages/grid/components/CustomLinks/index.jsx
packages/grid/components/CustomLinks/styles.js
packages/grid/index.js
packages/grid/reducer.js
packages/grid/util/index.jsx

Styling adjustments according to Figma file
JIRA card -> [PUB-2287](https://buffer.atlassian.net/browse/PUB-2287) …

[PUB-2287] Styling adjustments based on figma file.

---

packages/grid/components/CustomLinks/EditingLinkForm/index.jsx
packages/grid/components/CustomLinks/LinkPreview/index.jsx
packages/grid/components/CustomLinks/styles.js
packages/shared-components/ColorPicker/components/ColorSwatches/index.jsx
packages/shared-components/ColorPicker/styles.js

Color picker:
- Changing arrow icon color to contrast color on swatches section.

Color picker: adjusting swatches check color

---

packages/grid/components/CustomLinks/LinksHeader/index.jsx
packages/grid/components/CustomLinks/index.jsx
packages/grid/components/CustomLinks/styles.js

Adding proptypes, key, and fixing style when no custom links.

Adding proptypes, key, and fixing style when no custom links.

---

packages/grid/components/CustomLinks/EditingLinkForm/index.jsx
packages/grid/components/CustomLinks/LinksHeader/index.jsx
packages/grid/components/CustomLinks/index.jsx
packages/grid/components/GridPosts/index.jsx
packages/grid/index.js
packages/grid/middleware.js
packages/grid/reducer.js

Updating addLink functionality to isolate Add logic from edit logic

---

packages/grid/index.js

Fixing issue when editing single link url

Fixing issue when editing single link url

---

packages/grid/middleware.js
packages/grid/reducer.js

Fixes: https://buffer.atlassian.net/browse/PUB-2303

[PUB-2303] Re-fetch `shopGrid` posts when changed, added, or deleted in queue

---

package.json
packages/shared-components/GridList/index.jsx
yarn.lock

Submit shop link url on return key
https://buffer.atlassian.net/browse/PUB-2304
Added the onKeyUp method to the Buffer UI Input component …

[PUB-2304] Submit shop link url on return key

---

packages/shared-components/ColorPicker/components/ColorSelectorPopup/index.jsx

Renaming variable name that was already declared in the upper-scope.

Renaming variable name that was already declared in the upper-scope.

---

packages/grid/components/GridPosts/index.jsx
packages/grid/index.js

Removing shopgrid links feature flip check

Removing shopgrid links feature flip check

---

packages/shop-grid-promo-modal/index.js

Closing promo modal on clicking view plans.

---

packages/shared-components/ColorPicker/components/ColorSelectorPopup/index.jsx

Adding ability to press return key to save colour change

Adding ability to press return key to save colour change

---

packages/queue/index.js
packages/shared-components/PostErrorBanner/index.jsx

Add missing validation in functions.
[PUB-2326](https://buffer.atlassian.net/browse/PUB-2326)
[PUB-2327](https://buffer.atlassian.net/browse/PUB-2327) …

[PUB-2326] Fix missing validation

---

packages/routes/index.js
packages/shop-grid-promo-modal/index.js

Adding tracking parameters to promo modal

[PUB-2273] Adding tracking parameters to promo modal.

---

packages/queue/index.js

Add reminders validation

---

packages/grid/components/GridPosts/index.jsx

Updating empty state message for shop grid.

Empty state for shop grid message.

---

packages/modals/middleware.js

Displaying promo modal if free user has over 2 days signed up in buffer
Message from Mike.e -> https://buffer.slack.com/archives/C151RRDL1/p1576701384167600?thread_ts=1576627267.143000&cid=C151RRDL1 …

Displaying promo modal if free user has over 2 days signed up in buffer

---

packages/i18n/translations/en-us.json

Fix SBP Pricing

---

packages/composer/composer/components/App.jsx
packages/composer/composer/components/Composer.jsx
packages/composer/composer/components/ShopgridComposerBar.jsx
packages/composer/composer/stores/AppStore.js
packages/composer/composer/utils/DataImportUtils.js
packages/server/parsers/src/profileParser.js

Adding shopgrid preview link to users of shopgrid links accounts
https://buffer.atlassian.net/browse/PUB-2315 

Adding shopgrid preview link to users of shopgrid links accounts

---

packages/app-shell/components/AppShell/index.jsx
packages/app-shell/index.js
packages/app-shell/reducer.js
packages/initial-loading/components/InitialLoading/index.jsx
packages/initial-loading/middleware.js
packages/initial-loading/reducer.js
packages/plans/components/PlanColumnWithPremiumSolo/index.jsx
packages/plans/components/PlanColumnWithPremiumSolo/style.jsx
packages/plans/components/Plans/index.jsx
packages/plans/index.js

Remove the code for the Awesome to Pro promotional discount
[JIRA](https://buffer.atlassian.net/browse/PUB-2352) …

[PUB-2352] Remove Awesome to Pro Promo

---

packages/profile-sidebar/components/ProfileListItem/index.jsx

Add handle to Sidebar List Item title.
[PUB-1895](https://buffer.atlassian.net/browse/PUB-1895)
Users benefit from having the ability to hover over the social channel to see the full name of the social channels, especially when the names are long and truncated.
To visit the URL of …

[PUB-1895]Add handle to sidebar item title

---

packages/grid/components/CustomLinks/LinkDragWrapper/index.jsx
packages/grid/components/CustomLinks/LinkPreview/index.jsx
packages/grid/components/CustomLinks/LinksHeader/index.jsx
packages/grid/components/CustomLinks/index.jsx
packages/grid/components/CustomLinks/styles.js
packages/grid/components/GridPosts/index.jsx
packages/grid/components/GridPosts/story.jsx
packages/grid/index.js
packages/grid/index.test.jsx
packages/server/parsers/src/profileParser.js
packages/shared-components/GridList/index.jsx
packages/shared-components/GridList/story.jsx

Team Members that require approval should have read only access to the Shop Grid tab. This removes the ability for the user to make changes. 
https://buffer.atlassian.net/browse/PUB-2314
https://share.buffer.com/6quLvJyZ …

[PUB-2314] Change shop grid tab as read only for team members who require approval

---

packages/server/index.js
packages/server/package.json

Remove a package we don't need anymore after some previous clean up

Remove unneeded package

---

packages/profile-sidebar/middleware.js
packages/profile-sidebar/middleware.test.js

- Fixed bug introduced here: https://github.com/bufferapp/buffer-publish/commit/dc783676da12d4807a19b5360ff051fb4f899a39#diff-299dcac6d9d621f23f79b60ea6540fd3R175 and added test to catch it if it happens in the future.
[PUB-2276](https://buffer.atlassian.net/browse/PUB-2276)
Bugsnag: https://app.bugsnag.com/buffer/publish-dashboard/errors/5dd7019e70320200199c3ab5?filters[event.since][0]=30d&filters[error.status][0]=open
-   [ ] I have tested …

[PUB-2276] Fix drag and drop error in sidebar

---

packages/server/rpc/composerApiProxy/index.js

[PUB-2368](https://buffer.atlassian.net/browse/PUB-2368) - Adding forwarded ip address when working with link shortening client ip addresses so we can use the link shortening and limit on IP address correctly
To visit the URL of the staging deployment, please click "Show all checks" …

Adding forwarded ip address when working with link shortening client ip addresses

---

packages/app-shell/components/AppShell/index.jsx
packages/app-shell/index.js
packages/app-shell/reducer.js
packages/initial-loading/components/InitialLoading/index.jsx
packages/initial-loading/middleware.js
packages/initial-loading/reducer.js
packages/plans/components/Plans/index.jsx
packages/plans/index.js
packages/server/parsers/src/userParser.js

Gives a targeted list of Awesome users access to the payday page in NP.
[https://buffer.atlassian.net/browse/PUB-2381](https://buffer.atlassian.net/browse/PUB-2381)
To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and click …

[PUB-2381] Payday page access for targeted awesome users

---

packages/composer/composer/stores/AppStore.js
packages/composer/composer/stores/ComposerStore.js
packages/composer/composer/tests/stubData.js
packages/composer/composer/utils/DataImportUtils.js
packages/queue/components/QueueItems/index.jsx
packages/queue/components/QueuedPosts/index.jsx
packages/queue/index.js
packages/shared-components/ImagePost/index.jsx
packages/shared-components/LinkPost/index.jsx
packages/shared-components/MultipleImagesPost/index.jsx
packages/shared-components/Post/index.jsx
packages/shared-components/TextPost/index.jsx
packages/shared-components/VideoPost/index.jsx
packages/stories/components/StoryGroups/index.jsx
packages/stories/index.js
packages/temporary-banner/components/TemporaryDashboardBanner/index.jsx
packages/temporary-banner/index.js

- Remove reminders_flow feature from Publish
- Add hasPushNotification prop to Composer mock data.
[PUB-2324](https://buffer.atlassian.net/browse/PUB-2324) …

[PUB-2324] Remove reminders feature flip

---

package.json
yarn.lock

- Update ui version to 5.23.0. 
Now that the PR https://github.com/bufferapp/ui/pull/170 in UI was approved, we no longer need a beta version to access the changes needed for the profile sidebar. …

Update bufferapp/ui version

---

packages/thirdParty/middleware.js
packages/thirdParty/middleware.test.js

* https://buffer.atlassian.net/browse/PUB-2402

[PUB-2402] Flag migrated Awesome to Pro Users and their team members for appcues

---

packages/i18n/translations/en-us.json
packages/plans/components/PlanColumnWithPremiumSolo/index.jsx
packages/plans/components/Plans/index.jsx
packages/plans/index.js
packages/routes/index.js

Adding pro plan upgrade page changes to show correct text
https://buffer.atlassian.net/browse/PUB-2401 …

Adding pro plan upgrade page changes to show correct text

---

packages/modals/reducer.js
packages/thirdParty/index.js
packages/thirdParty/middleware.js

Isolating the logic for AppCues and consolidating it into all places where we initiate appcues …

Isolating the logic for AppCues and consolidating it into all places where we initiate appcues

---

packages/app-shell/components/AppShell/index.jsx
packages/sidebar/package.json
packages/store/package.json
yarn.lock

Updating link for feature requests
To visit the URL of the staging deployment, please click "Show all checks" at the bottom of …

Changing the feature request button to point to the feature-request endpoint

---

packages/campaigns/README.md
packages/campaigns/components/CampaignsPage/index.jsx
packages/campaigns/components/EmptyState/index.jsx
packages/campaigns/components/EmptyState/story.jsx
packages/campaigns/index.js
packages/campaigns/package.json
packages/i18n/translations/en-us.json
packages/shared-components/StepList/index.jsx
packages/shared-components/StepList/story.jsx
packages/shared-components/StepNumber/index.jsx
packages/shared-components/StepNumber/story.jsx
packages/shared-components/index.js
packages/stories/components/StepCard/index.jsx

Add Campaigns Empty State
- Add StepNumber and StepList as shared-components.
- Replace StepNumber in Story's step card.
https://buffer.atlassian.net/browse/PUB-2458
**StepNumber (shared-component)**
**StepList**
**Empty State**
-   [x] I kept accessibility in mind by following the …

[PUB-2458] Campaigns empty state

---

packages/server/rpc/campaigns/create/index.js
packages/server/rpc/campaigns/update/index.js
packages/server/rpc/index.js

Rpc to call endpoints for create and update a campaign. …

Rpc to call endpoints for create and update a campaign.

---

packages/campaigns/components/CampaignsPage/index.jsx
packages/campaigns/components/CampaignsPage/story.jsx
packages/campaigns/components/CreateCampaign/index.jsx
packages/campaigns/components/CreateCampaign/story.jsx
packages/campaigns/components/EmptyState/index.jsx
packages/campaigns/index.js
packages/campaigns/middleware.js
packages/campaigns/reducer.js
packages/constants/index.js
packages/i18n/translations/en-us.json
packages/shared-components/SimpleColorPicker/index.jsx
packages/shared-components/SimpleColorPicker/story.jsx
packages/shared-components/SimpleColorSwatch/index.jsx
packages/shared-components/SimpleColorSwatch/story.jsx
packages/shared-components/index.js
packages/store/middlewares.js
packages/store/reducers.js

- Add Create Campaign Page
Smaller tasks:
- Create a `Simple Color Swatch` and `Simple Color Picker` that can be reused and follow accessibility rules.
- Add logic to display different views on the Campaigns page. If there are no campaigns, it displays the `Empty State`, if click on create campaign, it displays the `Create Campaign`.
https://buffer.atlassian.net/browse/PUB-2459
Tracking and interactions with rpc methods are still temporary and need to be revisited.
Links will be replaced by new BDS Link Component.
**Simple Color Swatch (shared-component)**
**Simple Color Picker (shared-component)**
**Create Campaign Page**
Interaction:
https://share.buffer.com/KouWxYgq
- …

[PUB-2459] Create Campaign Page

---

packages/server/rpc/awesomeToProUpgradeDetails/index.js
packages/server/rpc/index.js
packages/temporary-banner/components/TemporaryDashboardBanner/index.jsx
packages/temporary-banner/index.js
packages/temporary-banner/middleware.js
packages/temporary-banner/middleware.test.js
packages/temporary-banner/reducer.js
packages/temporary-banner/reducer.test.js

Awesome to Pro upgrade banner for users who are being auto-upgraded to the Pro plan with billing changes.
[https://buffer.atlassian.net/browse/PUB-2295](https://buffer.atlassian.net/browse/PUB-2295) …

[PUB-2295] Awesome to Pro upgrade banner

---

packages/app-pages/components/AppPages/index.jsx
packages/campaigns/components/CampaignsPage/index.jsx
packages/campaigns/components/CampaignsPage/story.jsx
packages/campaigns/components/CampaignsWrapper/index.jsx
packages/campaigns/index.js
packages/campaigns/middleware.js
packages/campaigns/reducer.js
packages/initial-loading/index.js
packages/initial-loading/middleware.js
packages/initial-loading/reducer.js
packages/profile-sidebar/components/ProfileSidebar/index.jsx
packages/profile-sidebar/index.js
packages/profile-sidebar/reducer.js
packages/profile-sidebar/reducer.test.js
packages/routes/index.js

Adding **Campaigns** button to sidebar
**Task details PUB-2455**
- Added Campaigns button to sidebar
- Updated ProfileSidebar component to styled components
- Setting **Campaigns** button as active when clicking on it, or accessing it through the url
- Added feature flip to display Campaigns button:
1. Profile Sidebar: to hide Campaigns button
2. Init loading: redirect to dashboard if user try access campaigns through url
3. Campaigns Page: to display loading while it’s being redirected to dashboard when (ii) happens
-   [x] I have identified similar or related features and tested …

PUB-2455 | Add Campaigns button to sidebar

---

package.json
packages/campaigns/components/ViewCampaign/EmptyState/index.jsx
packages/campaigns/components/ViewCampaign/ExamplePost/index.jsx
packages/campaigns/components/ViewCampaign/ExamplePost/style.js
packages/campaigns/components/ViewCampaign/Header/index.jsx
packages/campaigns/components/ViewCampaign/Header/story.jsx
packages/campaigns/components/ViewCampaign/Header/style.js
packages/campaigns/components/ViewCampaign/index.jsx
packages/campaigns/components/ViewCampaign/story.jsx
packages/campaigns/index.js
packages/campaigns/reducer.js
packages/i18n/translations/en-us.json
packages/server/formatters/src/getURL.js
yarn.lock

Create the empty state for View Campaign. 
https://buffer.atlassian.net/browse/PUB-2456
- Add header for view campaign. Header displays different content based on whether they have posts.
- Add empty queue display if user hasn't added posts. 
- Left the method logic (deleteCampaign, editCampaign etc) empty for now until we have more pieces done.
- Adding some accessibility button changes in the ui repo. This can be deployed separately. 
- When running the icon figma script for the ui, the calendar icon wasn't generating correctly. I'm reaching out to figure out why, but feel free to review without it for now. 
-   [x] I have …

[PUB-2456] Add view campaign header and empty state

---

packages/general-settings/components/LinkShortening/LinkShorteningWrapper.jsx
packages/general-settings/middleware.js

_Worked on this for my CQT day with Jess_
We were seeing a number of customers where they had a custom bit.ly domain setup but the settings page was crashing. 
Digging into the backend was honestly more confusing than it was helpful – [our shorteners logic is "ridiculous"](https://github.com/bufferapp/buffer-web/blob/65ddc01361c9a838e1b53ae2a2003573d8bb22fc/api/controllers/profiles_controller.php#L595) 😅 
So yeah, solving this with some optional chaining on the front end, though it does seem like it could be indicative of a broader issue with the data from the backend.
cc @karelm Maybe we can chat on this over Zoom as you've been in this space recently.
-   [ ] All new …

[PUB-1638] Fix crashing settings when no selected shorteners

---

package.json
packages/campaigns/components/CreateCampaign/index.jsx
packages/campaigns/components/ViewCampaign/EmptyState/index.jsx
packages/profile-sidebar/components/ProfileListItem/index.jsx
packages/shared-components/ErrorBanner/index.jsx
packages/shared-components/PostErrorBanner/index.jsx
packages/stories/components/StoryGroups/index.jsx
yarn.lock

- Update bufferapp/ui version to 5.26
- Replace colors by BDS variables
https://buffer.atlassian.net/browse/PUB-2479
To visit the …

[PUB-2479] Update ui version

---

packages/composer/composer/components/Editor.jsx
packages/posting-schedule/utils/transformSchedule.js
packages/profile-sidebar/middleware.js
packages/profile-sidebar/middleware.test.js

Fixing the most frequent user errors in publish
-   [x] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f) …

Fixing the most frequent user errors in publish

---

helm/buffer-publish.dev.yaml
helm/buffer-publish.yaml

There has been an unexpected change of internal address and the old one is failing at the moment.
https://buffer.slack.com/archives/C0KS2S8D7/p1583315906030500
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d …

fix: update Analyze API internal URL

---

packages/shared-components/QueueHeader/index.jsx
packages/shared-components/QueueHeader/story.jsx
packages/shared-components/QueueItems/index.jsx
packages/shared-components/QueueItems/story.jsx
packages/shared-components/index.js

- Create component for the QueueHeader, to simplify the QueueItems component.
**QueueHeader:**
**CodeClimate rating change:**
To …

Refactor queue header

---

packages/server/rpc/campaigns/create/index.test.js
packages/server/rpc/campaigns/delete/index.js
packages/server/rpc/campaigns/delete/index.test.js
packages/server/utils/index.js

Add RPC function to delete a campaign, I also had to add an extra condition to parse the right error message.
- [JIRA ticket](https://buffer.atlassian.net/browse/PUB-2545)

Add RPC for deleting campaigns

---

packages/analytics/components/Notification/index.jsx
packages/composer/composer/components/InstagramFeedback.jsx
packages/composer/composer/components/LinkAttachment.jsx
packages/composer/composer/components/Notifications.story.jsx
packages/composer/composer/components/ShopgridComposerBar.jsx
packages/composer/composer/stores/AppStore.js
packages/composer/composer/stores/ComposerStore.js
packages/composer/composer/tests/__snapshots__/ShopgridComposerBar.test.js.snap
packages/ig-direct-posting-modal/components/InstagramDirectPostingModal/index.jsx
packages/posting-schedule/components/PostingSchedule/index.jsx
packages/queue/components/QueuePausedBar/index.jsx
packages/queue/components/RemindersBanner/index.jsx
packages/shared-components/PostStats/index.jsx
packages/stories/components/StoriesExplanation/index.jsx
packages/stories/components/StoryGroups/index.jsx
packages/two-factor-auth/components/Modal/screens/setupApp.jsx
packages/two-factor-auth/components/PreferencesRow/index.jsx

Update all FAQ links to the new Support site.
PUB-2506
To visit the URL of the staging deployment, please click "Show all checks" …

[PUB-2506] Update all FAQ links

---

packages/analytics/components/Analytics/index.jsx
packages/analytics/components/AnalyticsList/index.jsx
packages/analytics/index.js
packages/cta-banner/components/BillingUpgradeCTABanner/index.jsx
packages/general-settings/components/GeneralSettings/index.jsx
packages/general-settings/components/LinkShortening/index.jsx
packages/general-settings/index.js
packages/general-settings/reducer.js
packages/general-settings/reducer.test.js
packages/past-reminders/reducer.js
packages/product-features/reducer.js
packages/product-features/reducer.test.js
packages/profile-page/components/ProfilePage/index.jsx
packages/profile-sidebar/components/ProfileSidebar/story.jsx
packages/sent/components/SentPosts/index.jsx
packages/sent/components/SentPosts/story.jsx
packages/sent/index.js
packages/sent/reducer.js
packages/sent/reducer.test.js
packages/shared-components/BitlyClickNotification/index.jsx
packages/shared-components/Notification/index.jsx
packages/shared-components/Notification/story.jsx
packages/shared-components/index.js
packages/story-group-composer/components/AddStoryFooter/index.jsx
packages/story-group-composer/index.js

PUB-2573 - bitly messaging

---

packages/queue/middleware.js
packages/queue/reducer.js
packages/server/parsers/src/postParser.js
packages/server/rpc/campaigns/getCampaignsList/index.js
packages/server/rpc/campaigns/getCampaignsList/index.test.js

Updated mockup response with actual endpoint call in RPC and updated the tests. …

RPC | Fetching campaigns list from API

---

packages/analytics/components/Analytics/index.jsx
packages/analytics/components/AnalyticsList/index.jsx
packages/analytics/index.js
packages/sent/components/SentPosts/index.jsx
packages/sent/index.js
packages/shared-components/BitlyClickNotification/index.jsx

Removing click handler for bitly notification message + updating message …

Removing click handler for bitly notification message + updating message

---

packages/server/rpc/campaigns/delete/index.js

Updating parameter to be sent to endpoint

---

packages/composer/composer/components/campaigns/CampaignHeader.jsx

Making sure to display campaigns in composer if at least one campaign is found. …

Making sure to display campaigns in composer if at least one campaign

---

packages/shared-components/CardHeader/index.jsx
packages/shared-components/CardHeader/story.jsx

- Add new card header variation for campaigns
https://buffer.atlassian.net/browse/PUB-2537 …

[PUB-2537] Add new card header variation for campaigns

---

packages/i18n/translations/en-us.json

Updated empty state copy for View Campaign.
Updating copy to match the latest suggestion from Marketing. 
Related JIRA ticket: https://buffer.atlassian.net/browse/PUB-2505 …

Update headline, paragraph, and button copy in View Campaign main CTA

---

packages/campaigns-list/components/ListCampaigns/List/index.jsx
packages/campaigns-list/components/ListCampaigns/ListItem/style.js
packages/campaigns-list/components/ListCampaigns/index.jsx

Adjusting styling of the campaigns list.
- Encapsulating the list in a card
- Adding min and max-width
- Removing even number styling (background color)
- Adding hover state on list item
The existing list felt like it was floating awkwardly on the page, and I think this approach anchors it nicely.
-   [x] I have commented my code, particularly in …

Campaign list style adjustments

---

packages/composer/composer/components/campaigns/CampaignHeader.jsx
packages/composer/composer/components/campaigns/styles.js
packages/past-reminders/reducer.js
packages/queue/reducer.js
packages/sent/reducer.js

Styling campaigns list in the composer.
Jira Card -> PUB-2518 …

PUB-2518  | Styling campaigns dropdown in composer.

---

packages/story-group-composer/utils/AddStory.js
packages/story-group-composer/utils/AddStory.test.js

Fixing bug when scheduling new stories from the composer …

Fixing bug when scheduling new stories from the composer

---

packages/shared-components/PostTag/index.jsx

Changes hover and height styles on the campaign post tag that shows in queued items.
I noticed a blue border appearing on hover, and felt like the height of the tag was a little too tall. This is purely a design change.
- On hover: make border-color match the background color
- On hover: slight change in opacity 
- Height: respect height set by padding/margin/line-height instead of 40px declaration for buttons
Before:
After:
-   [x] I have …

Changing hover styles and reducing height on Campaign post tag

---

packages/campaigns-list/components/ListCampaigns/EmptyState/index.jsx
packages/i18n/translations/en-us.json

Adds subtext to campaigns list empty state. Changes copy for campaigns list and view campaign empty states.
Change made to align with new suggested copy. JIRA task here: https://buffer.atlassian.net/browse/PUB-2505 …

Empty state copy edits

---

package.json
yarn.lock

Bumping buffer-ui version to 5.32.0 for toggle Select component fixes. …

Bumping buffer-ui version to 5.32.0

---

package.json
packages/date-picker/package.json
yarn.lock

Fixes
https://app.bugsnag.com/buffer/publish-dashboard/errors/5e7cccedc6a1130017979d96?event_id=5e7ccced00594f564d1b0000&i=sk&m=nw
See:
https://github.com/wwayne/react-tooltip/pull/389#issuecomment-394715738 …

Upgrade `react-tooltip`

---

packages/campaign/components/ViewCampaign/story.jsx
packages/campaigns-list/components/ListCampaigns/List/index.jsx
packages/campaigns-list/components/ListCampaigns/List/story.jsx
packages/campaigns-list/components/ListCampaigns/ListItem/style.js
packages/campaigns-list/components/ListCampaigns/index.jsx
packages/server/parsers/src/campaignParser.js
packages/server/rpc/campaigns/create/index.test.js
packages/server/rpc/campaigns/getCampaign/index.test.js
packages/server/rpc/campaigns/getCampaignsList/index.test.js
packages/server/rpc/campaigns/update/index.test.js

Small copy and layout adjustments to the Campaigns list. Making the list span the full-width of the available page in most cases, spanning less and centering for very large screens.
I think "Updated" is easier to parse than "Last updated", and thought some small spacing adjustments would improve the design. …

Tweaking 'updated' copy and layout changes

---

helm/buffer-publish.dev.yaml
helm/buffer-publish.yaml
packages/server/index.js

The goal is to change from `bufferapp/publish-server ` to `publish-sever`. 
To visit the URL of the staging deployment, please …

Change the DD APM service name to publish-server

---

packages/composer/composer/components/Editor.jsx

On macOS pressing spacebar twice quickly adds a period and a space —
if left 'undhandled' this change in the input can cause draft-js to crash.
(One example is when this is done immediately after you type a link since
that triggers shortening to happen and draft-js / React gets confused
when trying to mutate the DOM since the sudden '.' is unexpected.) 
To solve this we look for when this 'double' character has been entered
and manually add it to the editorState ourselves - thus preventing the
unfortunate crashing.
-   [x] I have identified similar or related features and tested …

[PUB-2592] Fix double spacebar crash in composer

---

packages/story-group-composer/utils/AddStory.test.js

Fix tests that randomly fail while running in CI, due to timing. …

Fix randomly failing timing test

---

packages/story-group-composer/utils/AddStory.test.js

Fix tests that randomly fail while running in CI, due to date. …

Mocking moment.unix for fixed dates.

---

packages/app-pages/components/PagesWithSidebar/index.jsx
packages/campaign/components/ViewCampaign/Header/index.jsx
packages/campaign/components/ViewCampaign/index.jsx
packages/campaign/index.js

- Handle sent campaign route
**Bonus:** Change "View Report" button to primary type …

[PUB-2570] Handle sent campaign route

---

packages/campaign/reducer.js
packages/campaign/reducer.test.js
packages/shared-components/EmptyState/index.jsx
packages/shared-components/EmptyState/story.jsx

- Update `<EmptyState>` shared component to use BDS components and have new options: primary and secondary buttons.
- Tweak loading state when fetching campaign data: if the campaign is still stored in the state, doesn't show the loader. …

[PUB-2570] Update empty state shared component

---

packages/campaign/components/ViewCampaign/EmptyCampaignBanner/index.jsx
packages/campaign/components/ViewCampaign/EmptyState/index.jsx
packages/campaign/components/ViewCampaign/EmptyState/story.jsx
packages/campaign/components/ViewCampaign/index.jsx
packages/campaign/index.js
packages/i18n/translations/en-us.json
packages/shared-components/EmptyState/index.jsx

- Rename EmptyState to EmptyCampaignBanner
- Create an EmptyState component to handle all the ViewCampaign empty states
- Create different empty states
**Campaign with no posts**
**Campaign with no sent posts**
**Campaign with no scheduled posts, team member**
**Campaign with no scheduled posts, owner**
-   [ ] I …

[PUB-2570] Single campaign empty states

---

packages/profile-sidebar/middleware.js
packages/profile-sidebar/utils/index.js

Fix missing export in utils file

---

packages/shared-components/Post/index.jsx

Updating reminders text to use the word "up" less and be simpler to read / understand …

Updating reminders text

---

packages/shared-components/BitlyClickNotification/index.jsx

Fixing Cyclical Dependency issue with Bitly Notifications …

Fixing Cyclical Dependency issue with Bitly Notifications

---

packages/campaign/components/ViewCampaign/Header/index.jsx
packages/campaign/components/ViewCampaign/Header/story.jsx
packages/campaign/components/ViewCampaign/Header/style.js
packages/campaign/components/ViewCampaign/index.jsx
packages/i18n/translations/en-us.json
packages/shared-components/SkeletonElements/index.jsx
packages/shared-components/SkeletonElements/story.jsx
packages/shared-components/index.js

- Add a campaign header loading skeleton
- Add text, button and styles skeleton to shared-components.
I've created the text and button to extend the BDS components, but I'll suggest we move this in the future to the ui repository as a variation of Text and Button. The advantage of us using the same components with just a skeleton state is that we don't need to create the same structure twice, once the data is loaded we already know it's gonna be placed in the right spot.
-   [x] I have identified similar or related features and tested …

[PUB-2570] Campaign header loading skeleton

---

.github/PULL_REQUEST_TEMPLATE.md

Updating the PR template to add a line item on security and abuse potential of any changes.

Add reminder on security and abuse

---

packages/profile-sidebar/components/ProfileSidebar/index.jsx
packages/tabs/components/TabNavigation/index.jsx

Moving the New Tag from stories, and adding it to Campaigns in the sidebar
I've added it in the badges area of the button as its felt like the right area to place this.
cc/ @letsbleachthis  …

PUB-2634 | Removing the new tag from stories and adding it to campaigns

---

CONTRIBUTING.md
README.md

Update buffer-publish documentation to get started and coding guidelines:
- Update README.md file
- Adding a CONTRIBUTION.md file
In order to provide more context on how to get started and the guidelines you've developed as a team, I updated the documentation for this repo to give more clarity and transparency.
-   [ ] I have commented my code, particularly …

Update buffer-publish documentation

---

packages/campaign-form/components/CampaignForm/index.jsx
packages/campaign/components/ViewCampaign/EmptyCampaignBanner/index.jsx
packages/campaigns-list/components/ListCampaigns/EmptyState/index.jsx

Update to the correct faq link
https://buffer.atlassian.net/browse/PUB-2613
(Needed an easy win to end my day 😂)
The link isn't accessible to the public yet but will be in time for launch. …

[PUB-2613] Update campaign learn more links

---

packages/campaign/index.js
packages/campaign/reducer.js
packages/campaign/reducer.test.js
packages/composer-popover/components/ComposerWrapper/index.jsx
packages/queue/util/index.jsx
packages/server/parsers/src/campaignParser.js
packages/server/parsers/src/index.js
packages/server/rpc/campaigns/getCampaign/index.test.js

- Display campaign header when pusher event (by making the post go through the campaignItemParser)
- Remove content object in campaign parser.
- Pass avatar images and other profile props to each update.
In the future we want to not even receive the campaigns items with a content object from the api, but this seems a good compromise for now.
https://buffer.atlassian.net/browse/PUB-2661
This also fixes: https://buffer.atlassian.net/browse/PUB-2655
-   [ ] I have performed a self-review of my own …

[PUB-2661] Fix campaign header missing

---

packages/campaign/components/ViewCampaign/index.jsx

Remove temporary tag from sent tab in campaign …

[PUB-2570] Remove temporary tag from sent tab

---

packages/queue/middleware.js
packages/queue/middleware.test.js
packages/sent/reducer.js

Fix Bugsnag error for sent count.
Just moved the logic to update the sent counter to its own package: sent
Apparently the error is still happening after the fix done here: https://github.com/bufferapp/buffer-publish/pull/1325. 
Bugsnag: https://app.bugsnag.com/buffer/publish-dashboard/errors/5e95b7b923f4b900178cf7ee?filters%5Bevent.since%5D%5B0%5D=30d&filters%5Berror.status%5D%5B0%5D=open
-   [ ] I have tested my changes/additions in the …

Fix bugsnag error for sent counter

---

packages/server/index.html
packages/web/components/App/index.jsx

Prevent site translation from Google Translate with right click.
- JIRA card: PUB-2675
- The composer crashes when the site is translated via Google browser, so we decide it to disable it to prevent this error, it looks like is a known bug from React.
The fix prevents this popup from opening automatically:
And also prevents the site to be translated when right clicking the page:
-   [ ] I have tested my changes/additions in the latest …

PUB-2675  | Prevent site translation from Google with right click

---

packages/campaign/components/ViewCampaign/SkeletonPosts/index.jsx
packages/campaigns-list/components/ListCampaigns/List/story.jsx
packages/campaigns-list/components/ListCampaigns/ListItem/index.jsx
packages/campaigns-list/components/ListCampaigns/ListItem/story.jsx
packages/campaigns-list/components/ListCampaigns/ListItem/style.js
packages/campaigns-list/components/ListCampaigns/SkeletonList/index.jsx
packages/campaigns-list/components/ListCampaigns/SkeletonList/story.jsx
packages/campaigns-list/components/ListCampaigns/index.jsx
packages/shared-components/AnimatedList/index.jsx
packages/shared-components/AnimatedList/story.jsx
packages/shared-components/index.js

- Add AnimatedList shared-component
- Use AnimatedList in both SkeletonPosts (ViewCampaign) and SkeletonList (ListCampaigns)
- Add Skeleton variation to campaigns List Item
- Transform ListCampaigns loading into skeleton
https://buffer.atlassian.net/browse/PUB-2646
One thing I've noticed when building the skeleton variations here is that we have to end up adding more complexity than we would if the feature was built with skeleton/loading state in mind from the beginning. It's a good learning for future features! 
-   [ ] I have identified similar or related features and tested they …

[PUB-2646] Improve loading experience in Campaigns List

---

packages/shared-components/ImagePost/index.jsx
packages/shared-components/LinkPost/index.jsx
packages/shared-components/MultipleImagesPost/index.jsx
packages/shared-components/TextPost/index.jsx
packages/shared-components/UpdateTextContent/index.jsx
packages/shared-components/UpdateTextContent/story.jsx
packages/shared-components/index.js

- Add Update Text content shared-component and replace it in TextPost, ImagePost, MultipleImagePost, VideoPost and LinkPost.
- Bonus: sorted packages/shared-components/index.js by alphabetical order.
Step 2 of Posts refactoring: https://paper.dropbox.com/doc/Refactor-Posts--AyD9S0MqLq3mO5bw~~BV9TzyAg-rgzLttQL5bKmyBrrlvAgn
-   [ ] I have tested my changes/additions in the latest Chrome, Firefox, …

[PUB-2571] Add Update Text Content

---

packages/past-reminders/reducer.js

Update posts count after sending to mobile for past reminders.
JIRA card: PUB-2676 …

Update posts count after sending to mobile for past reminders

---

packages/shared-components/UpdateAttachmentContent/index.jsx
packages/shared-components/UpdateAttachmentContent/story.jsx
packages/shared-components/UpdateContent/index.jsx
packages/shared-components/UpdateContent/story.jsx
packages/shared-components/UpdateMediaContent/index.jsx
packages/shared-components/UpdateMediaContent/story.jsx

- Add `<UpdateMediaContent>`, `<UpdateAttachmentContent>` and `<UpdateContent>` .
Step 3 of Posts refactoring: https://paper.dropbox.com/doc/Refactor-Posts--AyD9S0MqLq3mO5bw~~BV9TzyAg-rgzLttQL5bKmyBrrlvAgn
We just extracted the content from the 5 types of posts into content components. In the next PR we will replace the old code by these. 
**Media content (image):**
**Media content (video):**
**Media content (multiple image):**
**Attachment content:**
**Content (with media):**
**Content (with attachment):**
-   [x] I have identified …

[PUB-2571] Add update content

---

__snapshots__/snapshot.test.js.snap
packages/shared-components/ImagePost/index.jsx
packages/shared-components/ImagePost/story.jsx
packages/shared-components/LinkPost/index.jsx
packages/shared-components/LinkPost/story.jsx
packages/shared-components/MultipleImagesPost/index.jsx
packages/shared-components/MultipleImagesPost/story.jsx
packages/shared-components/Post/index.jsx
packages/shared-components/Post/story_test.jsx
packages/shared-components/TextPost/index.jsx

- Use `<UpdateContent>` directly in `<Post>`.  I'll handle the props spread/ data structure later, for now it works 😄 
- Remove content from each type of post: TextPost, ImagePost, MultipleImagePost, VideoPost and LinkPost.
Step 4 of Posts refactoring: https://paper.dropbox.com/doc/Refactor-Posts--AyD9S0MqLq3mO5bw~~BV9TzyAg-rgzLttQL5bKmyBrrlvAgn
Next PR: Queues render Post directly, instead of TextPost, ImagePost, MultipleImagePost, VideoPost and LinkPost.
-   [ ] I have identified similar or related features and tested they are still …

[PUB-2571] Post renders update content

---

packages/i18n/translations/en-us.json
packages/i18n/translations/es-es.json

Translate localization file to Spanish (from English).
https://buffer.atlassian.net/browse/PUB-2681 …

Translate localization file to Spanish

---

packages/queue/components/QueueItems/index.jsx
packages/shared-components/PostList/index.jsx
packages/shared-components/QueueItems/index.jsx
packages/shared-components/UpdateMediaContent/index.jsx
packages/shared-components/index.js

- Queues render Post directly
- Fix Lightbox bug
Step 5 of Posts refactoring: https://paper.dropbox.com/doc/Refactor-Posts--AyD9S0MqLq3mO5bw~~BV9TzyAg-rgzLttQL5bKmyBrrlvAgn
Next PR: delete TextPost, ImagePost, MultipleImagePost, VideoPost and LinkPost …

[PUB-2571] Queues render Post directly

---

packages/i18n/translations/en-us.json
packages/i18n/translations/es-es.json

Update campaigns empty state copy
https://buffer.atlassian.net/browse/PUB-2687 …

[PUB-2687] Update campaigns empty state copy

---

packages/campaign-form/components/CampaignForm/index.jsx
packages/campaign-form/components/CampaignForm/story.jsx
packages/campaign-form/index.js
packages/campaign/components/ViewCampaign/index.jsx
packages/campaigns-list/components/ListCampaigns/EmptyState/index.jsx
packages/campaigns-list/components/ListCampaigns/EmptyState/story.jsx
packages/campaigns-list/components/ListCampaigns/List/index.jsx
packages/campaigns-list/components/ListCampaigns/List/story.jsx
packages/campaigns-list/components/ListCampaigns/ListItem/index.jsx
packages/campaigns-list/components/ListCampaigns/ListItem/story.jsx
packages/campaigns-list/components/ListCampaigns/SkeletonList/index.jsx
packages/campaigns-list/components/ListCampaigns/SkeletonList/story.jsx
packages/campaigns-list/components/ListCampaigns/index.jsx
packages/campaigns-list/index.js
packages/i18n/translations/en-us.json
packages/i18n/translations/es-es.json
packages/profile-sidebar/components/ProfileSearch/index.jsx
packages/profile-sidebar/components/ProfileSidebar/index.jsx

Update Campaigns List to use react-i18n instead of translations package.
- Removes translations and uses new react-i18n library for Campaigns List
- Removes translations and uses new react-i18n library for Campaign Form …

Use i18n for campaigns list and form

---

packages/language-preferences/index.js
packages/language-preferences/reducer.js
packages/profile-sidebar/components/ProfileSearch/index.jsx

Fix missing export for reducer in language settings …

Fix missing export for language settings reducer

---

packages/i18n/translations/en-us.json
packages/i18n/translations/es-es.json
packages/server/webpack.config.dev.js

Fixes the incorrect object type in i18n files.
@josem @MayaUribe I'm wondering if worked on / edited this file with some kind of external editor? Just looks like that since only the arrays got mixed up here. Something to watch out for in the future either way. (Maybe we can refactor the front-end so we don't need to use arrays, as it is a bit of weird pattern we have going there.)
-   [ ] I have tested my changes/additions in the latest …

[PUB-2688] Fix /plans page crash

---

__snapshots__/snapshot.test.js.snap
packages/shared-components/Draft/index.jsx
packages/shared-components/Draft/story_test.jsx
packages/shared-components/QueueItems/index.jsx
packages/shared-components/UpdateTextContent/index.jsx
packages/shared-components/index.js

Queues render Draft directly
Step 7 of Posts refactoring: https://paper.dropbox.com/doc/Refactor-Posts--AyD9S0MqLq3mO5bw~~BV9TzyAg-rgzLttQL5bKmyBrrlvAgn
Next PR: delete TextDraft, ImageDraft, MultipleImageDraft, VideoDraft and LinkDraft
- …

[PUB-2571] Queues render Draft directly

---

packages/shared-components/Post/index.jsx
packages/shared-components/UpdateMediaContent/index.jsx
packages/shared-components/UpdateMediaContent/story.jsx
packages/shared-components/package.json
yarn.lock

Handle Lightbox actions with local state.
Step 9 of Posts refactoring: https://paper.dropbox.com/doc/Refactor-Posts--AyD9S0MqLq3mO5bw~~BV9TzyAg-rgzLttQL5bKmyBrrlvAgn
I was trying to replace this component from an external library to the BDS carousel+modal, but there are still some incompatibilities so not worth the work right now.
-   [ ] I have commented …

[PUB-2571] Handle Lightbox actions with state

---

packages/app-shell/components/AppShell/index.jsx
packages/i18n/translations/en-us.json
packages/i18n/translations/es-es.json
packages/tabs/components/TabNavigation/index.jsx

Translations and adding tabs and menus to translations files.
- Replaces translations with react-i18n …

i18n | Tabs and menus

---

packages/server/lib/bugsnag.js
packages/server/lib/embeds/bugsnag.js

Adding missing isStandalone properties to the getBugsnagScript script …

Adding missing isStandalone properties to the getBugsnagScript script

---

packages/server/index.html
packages/server/index.js
packages/server/lib/embeds/bundleReminder.js
packages/server/lib/embeds/fullstory.js
packages/server/lib/generateIndexHtml.js
packages/server/standalone/index.js

Just adding some helpful messaging for standalone mode. …

Small tweaks and fixes to support standalone mode

---

packages/modals/components/AppModals/index.jsx
packages/modals/middleware.js
packages/queue/middleware.js

Removing auto-open modal for direct connect workflow …

PUB-2691 | Removing auto-open modal for direct connect workflow

---

packages/modals/middleware.test.js
packages/queue/middleware.test.js

Fixing failing tests around removal of modal flag …

Fixing failing tests around removal of modal flag

---

packages/account-notifications/components/Notification/index.jsx
packages/account-notifications/components/Notifications/index.jsx
packages/date-time-preferences/components/SelectDayToStartTheWeek/index.jsx
packages/date-time-preferences/components/TimeFormatPreferences/index.jsx
packages/i18n/translations/en-us.json
packages/i18n/translations/es-es.json
packages/manage-apps-extras/components/AppsManager/index.jsx
packages/manage-apps-extras/components/ExtrasLinks/index.jsx
packages/preferences/components/General/index.jsx
packages/preferences/components/Security/index.jsx
packages/two-factor-auth/components/Modal/screens/chooseMethod.jsx
packages/two-factor-auth/components/Modal/screens/recovery.jsx
packages/two-factor-auth/components/PreferencesRow/index.jsx
packages/two-factor-auth/components/TwoFactorAuth/index.jsx
packages/two-factor-auth/components/TwoFactorAuth/story.jsx

Add i18n for preferences
- Replaces translations with react-i18n …

Move preferences to i18n

---

__snapshots__/snapshot.test.js.snap
packages/server/parsers/src/postParser.js
packages/shared-components/Draft/index.jsx
packages/shared-components/Draft/story_test.jsx
packages/shared-components/Post/index.jsx
packages/shared-components/Post/story_test.jsx
packages/shared-components/PostList/index.jsx
packages/shared-components/QueueItems/index.jsx
packages/shared-components/UpdateContent/index.jsx
packages/shared-components/UpdateMediaContent/index.jsx

- Create postContent in postParser, to group data needed for UpdateContent.
- Move RetweetPanel inside UpdateContent
- Simplify PostComponent logic in QueueItems and PostList
- Re-add video tag to video updates
I've decided to add the postContent instead of replacing several properties in the postParser, as a proper parser cleaning requires mores time and have in consideration the data consumed by the composer
-   [ ] I have performed a self-review of …

[PUB-2571] Small improvements in posts

---

CONTRIBUTING.md

Guidelines adjustments
- Add more examples and being more explicit in regards of components usage after conversation in last [PR](https://github.com/bufferapp/buffer-publish/pull/1299) …

Guidelines | Add examples in the guidelines for functional components

---

packages/server/rpc/globalAccount/index.js

Follow up of https://github.com/bufferapp/buffer-publish/pull/1375 since I missed the real error. …

Fix missing metadata value in organization

---

packages/composer/composer/components/DateTimeSlotPicker.jsx
packages/composer/composer/components/shared/Select.jsx

Fixing missing styled component I accidentally deleted …

Fixing missing styled component I accidentally deleted

---

packages/campaigns-list/components/ListCampaigns/ListItem/index.jsx

- Disable View Report in CampaignList when no dateRange
- Make View Campaign the main action in split button
https://buffer.atlassian.net/browse/PUB-2620
**Without data range (no posts):**
**With data range (posts):** …

[PUB-2620] Disable View Report when no dateRange

---

CONTRIBUTING.md

Update guidelines to default to React.i18n when handling strings in our codebase.
This came out after the work for engineering week, since there is a lot of text remaining to move to the translations files, we decided to be more specific on how to work with this and continue this work in a steady way. …

Guidelines | Working with i18n

---

package.json
packages/app-shell/components/AppShell/index.jsx
packages/app-shell/components/AppShell/story.jsx
yarn.lock

Update ui package to 5.35.0 which includes skip to main content change
Related PR: https://github.com/bufferapp/ui/pull/203
-   [ …

Update ui package which includes skip to main content change

---

package.json
packages/campaign-form/components/CampaignForm/index.jsx
packages/i18n/translations/en-us.json
packages/i18n/translations/es-es.json
yarn.lock

Bump @bufferapp/ui version to 5.36.0 …

Bump @bufferapp/ui version to 5.36.0

---

__snapshots__/snapshot.test.js.snap
packages/profile-page/components/ProfilePage/index.jsx
packages/shared-components/CardFooter/index.jsx
packages/shared-components/CardHeader/index.jsx

Fix profile page styles caused by regression 
Fix border styles in card header and card footer
Regression caused here: https://github.com/bufferapp/buffer-publish/commit/84e385836ddaadf33bb7a66d97e0f385e6a97fe4#diff-488db78c68032ee627dde80638d82767R33-L34
-   [ ] I kept …

Fix profile page styles

---

package.json
yarn.lock

Bump buffer-components version to 3.3.0 (fix vulnerabilities + adds classNames to 5 components)
https://buffer.atlassian.net/browse/PUB-2682
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d …

[PUB-2682] Bump buffer-components version

---

CONTRIBUTING.md

- Fix index references (the emojis aren't included in the id 😅 )
- Add BDS guidelines
Very small guidelines about when to use the UI library vs buffer-components.
https://buffer.atlassian.net/browse/PUB-2708 …

[PUB-2708] Add BDS guidelines

---

packages/server/lib/embeds/bufferData.js

PUB-2743 | Removing user data from server generated response …

PUB-2743 | Removing user data from server generated response

---

packages/composer/composer/components/App.jsx
packages/composer/composer/utils/DataImportUtils.js
packages/composer/composer/utils/WebAPIUtils.js
packages/composer/interfaces/buffer-publish.jsx
packages/server/parsers/src/postParser.js

- Update share again pins to use the new save endpoint ([Related PR](https://github.com/bufferapp/buffer-web/pull/17080))
- Fix bug when scheduling a past post from Pinterest
JIRA card -> PUB-1508 …

PUB-1508  | Fix bug for share again on Pinterest.

---

package.json
yarn.lock

Pinning analyze to an explicit version in new publish …

Pinning analyze to an explicit version in new publish

---

packages/server/index.html

Remove scrollbar set width. Use the default browser styling (similar to Analyze)
The other scrollbar styling should be ok (track, thumb). It will be good to have Lauren discuss this with BDS, as I'm not sure where the previous styling came from?
Tested on firefox & chrome. Having trouble testing on safari as I'm having login issues. 
https://buffer.atlassian.net/browse/PUB-2800 …

[PUB-2800] Remove scrollbar set width

---

packages/app-pages/components/AppPages/index.jsx
packages/preferences/index.js
packages/routes/index.js
packages/tabs/index.js

Migrate newConnectionRoute and PlansPage to new routes format
https://buffer.atlassian.net/browse/PUB-2802
-   [ ] I have …

[PUB-2802] Update newConnection and plans routes to new format

---

.github/workflows/cypress.yml

Update Cypress GH Action version

---

CONTRIBUTING.md

Improve the docs to help with running Cypress locally. …

Improve docs for Testing / Cypress

---

packages/app-pages/index.test.js
packages/campaign/index.test.js
packages/queue/index.test.js
packages/test/generate-data/index.js
packages/utils/date/index.js
packages/utils/date/index.test.js
packages/utils/package.json

Add integration test for all our Queues
- Main queue
- Stories
- Past Reminders
- Analytics
- Drafts
- Campaigns
This is the first step for the Multiple Queue refactoring.
JIRA Card -> PUB-2841
N/A …

Queues Refactor | Integration tests for Queues

---

packages/app-pages/index.js
packages/bootstrap/middleware.js
packages/organizations/middleware.js
packages/profile-sidebar/reducer.js
packages/profile-sidebar/utils/index.js
packages/routes/index.js

- Filter profiles by org in routes
- Add org route
- Change how some org actions are being dispatched, to match the diagram
https://buffer.atlassian.net/browse/PUB-2781
What's left to do (in separated PRs): eliminate https://github.com/bufferapp/buffer-publish/blob/master/packages/initial-loading/middleware.js#L37-L63 by refactoring it, as it creates multiple side effects. …

[2781] Filter profiles by org in routes

---

packages/app-pages/index.test.js
packages/campaign/index.test.js

Fix AppPages tests.
With the last merge to master, the tests associated with AppPages broke, because I'm passing an initial state for `user` and `profiles`, so I added the new `publishProfiles` as an initialState.
**A reflection on why this test broke:**
I've been repeating over and over again that we should avoid testing implementation details, and I know this test breaking is kind of that, it broke because there was a change in implementation details, however, I've been thinking of ways to create integration tests without having to go too far back in our component tree, and it's very challenging to do so, because of the way our state management is in place, we don't fetch for posts queued in the Queue component, or for reminders in the PastReminders components, so this makes it very …

Fix AppPages tests, add new initialState publishProfiles.

---

packages/server/parsers/src/orgParser.js

Adding selected param to orgParser

---

packages/app-shell/components/AppShell/index.jsx
packages/app-shell/index.js
packages/app-shell/reducer.js
packages/app-shell/reducer.test.js
packages/server/index.js
packages/server/rpc/globalAccount/index.js

Pass new app shell impersonation prop as true during an impersonation session
This change helps support our new Global Impersonations functionality.
To be deployed after the [buffer-web](https://github.com/bufferapp/buffer-web/pull/17127) and [global admin](https://github.com/bufferapp/buffer-admin-next/pull/70) changes. See [roll out doc](https://paper.dropbox.com/doc/Global-Impersonations-Roll-Out--A2Zikkwd8BnWoKE8ydy6rP74Ag-LTgwJrkiMk5m2R8c45xHP) for full deployment plan
Jira - [INT-23](https://buffer.atlassian.net/browse/INT-23)
-   [x] I have identified similar or related …

Impersonation support in App Shell

---

packages/shared-components/Arrow/index.jsx
packages/shared-components/ColorPicker/styles.js
packages/story-group-composer/components/AddStoryFooter/index.jsx
packages/story-group-composer/components/AddStoryFooter/style.jsx

Adding fixes for CSS issues with buttons to UI …

Adding fixes for CSS issues with buttons to UI

---

packages/server/lib/embeds/datadogRum.js

Let's collect only 5% of all samples to cut the cost of Datadog RUM and see if this is enough to understand and evaluate the performance of Publish Frontend.
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86 …

Reduce Datadog RUM sample size to 5%

---

packages/profile-sidebar/reducer.js

https://buffer.atlassian.net/browse/PUB-2874 …

[PUB-2874 ]Fix profiles loading

---

packages/shared-components/QueueItems/index.jsx

Team Member is no longer able to access Analytics for Owner's Social Accounts.
https://buffer.atlassian.net/browse/PUB-2888
-   [ …

[PUB-2888] Add isBusiness missing prop

---

packages/composer-user-tags/components/UserTags/index.jsx
packages/composer-user-tags/utils/Tags.js
packages/composer-user-tags/utils/Tags.test.js

Add a default coordinate if a user tag coordinate is not an eligible number.
There have been cases with users where their user tag coordinates are `Infinity`. I haven't been able to replicate this, as a user should only be able to click on the image. My hunch is it's happening when users have a slow connection and potentially clicking on the form before image is fully loaded. Regardless, their update should no longer fail with default coordinates. 
I've confirmed that two tags can have the same coordinates. 
https://buffer.atlassian.net/browse/PUB-2466
-   [ ] I have identified …

[PUB-2466] Add a default user tag coordinate if number is not valid

---

.github/workflows/cypress-cleanup.yml

Create Cypress Cleanup Action (Scheduled)

---

packages/app-shell/index.js
packages/organizations/utils/index.js
packages/organizations/utils/index.test.js

Sort orgs in Org Switcher by alphabetical order
https://buffer.atlassian.net/browse/PUB-2917 …

Sort orgs in Org Switcher by alphabetical order

---

packages/server/rpc/analytics/average/index.js
packages/server/rpc/analytics/compare/index.js
packages/server/rpc/analytics/postsSummary/index.js
packages/server/rpc/analytics/summary/index.js

To update analytics RPC endpoints in Analyze to read the data from organic if that field is present
As part of the upcoming work to provide paid metrics, we are going to change some of the APIs responses format.
This updates Analyze's RPCs so that they will work with both current and upcoming versions of the APIs.
- [related PR in Analyze](https://github.com/bufferapp/buffer-analyze/pull/764)
- [Analyze APIs changes](https://github.com/bufferapp/buffer-analytics/pull/793)
- [Jira task](https://buffer.atlassian.net/jira/software/projects/AT/boards/69?selectedIssue=AT-662)
-   [x] I …

prepare Analyze RPCs to deal with organic metrics

---

packages/server/index.js

Fix https://buffer.slack.com/archives/C151RRDL1/p1595268710255500 …

Fix issue where parser is not available

---

package.json
yarn.lock

Bump bufferapp/ui version to 5.42.0
The latest version has OrgSwitcher styling adjustment. …

Bump bufferapp/ui version to 5.42.0

---

helm/buffer-publish.dev.yaml
packages/server/rpc/analytics/average/index.js
packages/server/rpc/analytics/compare/index.js
packages/server/rpc/analytics/postsSummary/index.js
packages/server/rpc/analytics/summary/index.js

Clean up temporary changes introduced in #1460 
This are not needed anymore because we are always returning `organic` in the responses.
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e …

cleanup analytics RPCs data access

---

packages/server/parsers/src/userParser.js

Fix share next conditions

---

packages/server/parsers/src/userParser.js

Fix share next condition. If only I could get it right the first time 🤦  …

Fix share next condition

---

packages/composer/composer/components/campaigns/CampaignHeader.jsx

The tag for a campaign was being removed whenever a user edited the update.
PUB-2897
[https://share.buffer.com/5zuXQLqL](https://share.buffer.com/5zuXQLqL)
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb …

[PUB-2897] Prevent Campaign Tag Disappearance

---

packages/server/formatters/src/getURL.js

Use new route to redirect to current organization in org admin.
- JIRA card -> PUB-2914
- Related PR -> https://github.com/bufferapp/buffer-web/pull/17173
https://share.getcloudapp.com/eDu1GkmB …

PUB-2914 | Use new route to redirect to current organization in org admin.

---

packages/queue/components/QueuedPosts/index.jsx
packages/queue/index.js
packages/queue/util/index.jsx
packages/queue/util/index.test.js
packages/shared-components/PostEmptySlot/index.jsx
packages/shared-components/QueueItems/EmptySlot/index.jsx
packages/shared-components/QueueItems/index.jsx
packages/stories/index.js

- If a posting schedule has no times, show one queue slot per day. Instead of the label showing a time (like 7:48 AM), show “Schedule a Tweet/Post” (the copy we currently show on hover).
- We shouldn’t apply these single queue slots across the board whenever a day is toggled off, because some customers have specifically chosen to skip over days of the week, and we’d be adding unnecessary clutter to their queues.
I treated the queue slots similarly to how we've handled the ig stories slots without a posting schedule.
https://share.buffer.com/4gu9AoDv
-   [ ] I have identified similar …

[PUB-2830] Simplify the posting schedule with queue adjustments

---

packages/thirdParty/middleware.js

- Add prop to appcues instead of iterate 🤦 
https://buffer.atlassian.net/browse/PUB-2936 …

[PUB-2936] Fix canSeeOrgSwitcher prop

---

packages/server/parsers/src/userParser.js

- Fix team condition
-   [ ] I have considered [security, abuse & compliance](https://www.notion.so/buffer/Engineering-Wiki-f34142 …

Fix condition for appshell team

---

package.json
yarn.lock

Update bufferapp/ui version to 5.44.1 to solve scrolling issue in the org switcher
https://buffer.atlassian.net/browse/PUB-2916
- …

Update ui to version 5.44.1

---

packages/locked-profile-notification/components/LockedProfileNotification/index.jsx
packages/locked-profile-notification/components/LockedProfileNotification/story.jsx
packages/locked-profile-notification/index.js
packages/locked-profile-notification/index.test.jsx

Add owner email address in to locked profile state 
https://buffer.atlassian.net/browse/PUB-2980 …

[PUB-2980] Add owner email address in to locked profile state 

---

packages/i18n/translations/en-us.json
packages/profile-sidebar/components/ProfileSidebar/index.jsx
packages/profile-sidebar/index.js
yarn.lock

- Disable Manage Social Accounts button for non-admin users and add a tooltip with the explanation
Extra: Fix 2 Factor Authentication translation
With the org switcher we weren't display the social account buttons for non admin users. The missing button is causing confusion to the users, so we are disabling it instead and providing an explanation
-   [ ] I …

Add tooltip to manage social accounts button

---

packages/onboarding/components/OnboardingPage/index.jsx
packages/profile-sidebar/components/ProfileSidebar/index.jsx

- Remove the ability for customers to connect IG personal profiles by:
- Changing oauth url to `choose_business`
- Add ctas for profile connection on onboarding page
https://buffer.atlassian.net/browse/PUB-3008
https://buffer.atlassian.net/browse/PUB-3009
I'm not able to test these in staging 🤔 It just redirects to the queue. I tried on a different staging url and saw the same thing, so it seems it's unrelated to my changes. Not ideal though. I did test locally. 
-   [x] I have performed a …

[PUB-3008] Remove the ability for customers to connect Instagram personal profiles

---

packages/i18n/translations/en-us.json

Update retiring instagram profile banner copy
https://buffer.atlassian.net/browse/PUB-3036
I'll deploy this today since it's non-breaking and went help with clarification over the weekend …

[PUB-3036] Update retiring instagram profile banner copy

---

package.json
yarn.lock

Update ui package which includes social button copy change of "Connect an Instagram profile" to "Connect an Instagram business account" 
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72 …

Update ui package which includes social button copy change

---

packages/server/package.json

Update `@bufferapp/buffer-rpc` to the latest version which will send handled RPC errors to Bugsnag so we can keep an eye on things.
I couldn't reproduce the error from **[PUB-3042](https://buffer.atlassian.net/browse/PUB-3042)** (may have been another API issue that was fixed or self-resolved) so [I added Bugsnag tracking to buffer-rpc](https://github.com/bufferapp/buffer-rpc/commit/60a8be6784575d7c1e05445945d3a8c95abf9e57) so we can get more visibility on errors like this.
-   [ ] I have …

Update RPC package for bugsnag error reporting

---

packages/queue/middleware.js

Update the direct scheduling error message to give more details and to account for cases where a user did convert their account to business but missed other steps. 
https://buffer.atlassian.net/browse/PUB-3059  …

[PUB-3059] Update direct scheduling error message to give more details. 

---

packages/web/components/LoadingGate/index.jsx

Reduce the jarring blankness of the `LoadingGate` by rendering the BufferLoading animation. …

Add `BufferLoader` animation to loading gate

---

packages/onboarding/components/DisabledQueue/index.jsx
packages/onboarding/components/OnboardingManager/index.jsx
packages/onboarding/index.js
packages/onboarding/index.test.jsx

- Fix social connect buttons for business trialists in disabled queue
https://buffer.atlassian.net/browse/PUB-3067
-   [ ] I have …

Fix social connect buttons for business trialists in disabled queue

---

packages/campaign-form/index.test.js

Improvements in assertions for campaign form tests.
I was making a knowledge sharing session in Core's team about React Testing Library, and while going through the campaign form tests, I realized some small improvements to make in these tests, so I thought of committing them 😊
- …

Improvements in campaigns form tests.

---

packages/composer/composer/components/AppStateless.jsx
packages/composer/composer/components/ComposerSection.jsx
packages/composer/composer/components/ProfileSection.jsx

Add validation to composer

---

.travis.yml
nginx-config/production.conf

* iframe protection; see https://github.com/bufferapp/buffer-analyze/pull/863
* also disabling codecov, we use codeclimate now (🗑️!)
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573 …

Add iframe protection, disable codecov

---

packages/composer/composer/utils/WebAPIUtils.js

Reported in Slack: https://buffer.slack.com/archives/C0258B5CR/p1601438533129400 …

hotfix: fix campaigns saving in composer

---

packages/app-pages/index.js
packages/campaign/index.test.js
packages/default-page/index.js
packages/default-page/index.test.js
packages/profile-sidebar/reducer.js
packages/profile-sidebar/reducer.test.js
packages/profile-sidebar/utils/index.js
packages/profile-sidebar/utils/index.test.js
packages/profiles-disconnected-modal/index.js
packages/server/parsers/src/userParser.js
packages/server/rpc/user/index.js

- Remove org switcher references in frontend
https://buffer.atlassian.net/browse/PUB-3003 …

[PUB-3003] Remove org switcher feature

---

packages/composer/composer/AppConstants.js
packages/composer/composer/action-creators/AppInitActionCreators.js
packages/composer/composer/stores/AppStore.js
packages/composer/composer/utils/LifecycleHooks.js
packages/composer/interfaces/buffer-publish.jsx
packages/modals/middleware.js
packages/modals/middleware.test.js
packages/server/index.ejs
packages/thirdParty/middleware.js
packages/thirdParty/middleware.test.js
packages/thirdParty/reducer.js
packages/trial-complete-modal/reducer.js
packages/trial-complete-modal/reducer.test.js
packages/trial/middleware.js
packages/trial/middleware.test.js

Replace user by org references:
- In trials
- in third party apps
Bonus: Remove iterate
Bonus 2: Bug fix in composer trial path https://buffer.atlassian.net/browse/PUB-2205
https://buffer.atlassian.net/browse/PUB-3000 …

[PUB-3000] Replace user by org references

---

packages/composer/composer/action-creators/AppActionCreators.js
packages/composer/composer/stores/ComposerStore.js

- Fix org composer store validation errors …

Fix org composer store validation errors

---

packages/shared-components/BitlyClickNotification/index.jsx

* https://buffer.atlassian.net/browse/PUB-3051 …

[PUB-3051] Update copy for bit.ly notification

---

packages/organizations/middleware.js
packages/profile-sidebar/index.js
packages/server/parsers/src/orgParser.js
packages/server/parsers/src/userParser.js
packages/server/rpc/user/index.js

- Delete no longer used userParser props and org rpc injection
- Delete INIT_USER on setCurrentOrganization in organizations middleware
https://buffer.atlassian.net/browse/PUB-3001
https://buffer.atlassian.net/browse/PUB-3002
-   [ ] I kept accessibility in mind by following the …

[PUB-3001/3002] Remove org injection in users

---

packages/i18n/translations/en-us.json
packages/ig-personal-profile-notification/components/InstagramPersonalProfileNotification/index.jsx

https://buffer.atlassian.net/browse/PUB-3100
Add an additional link to a step-by-step video to the IG retirement notification
- …

[PUB-3100] Add video link to IG retirement notification

---

packages/app-pages/components/PageWithSidebarWrapper/index.jsx
packages/web/components/App/index.jsx

- Fix scrolling issue - no longer see grey bar at the bottom, caused by temporary banners or sidebars with many channels.
https://buffer.atlassian.net/browse/PUB-2863 …

[PUB-2863] Fix scrolling issues in dashboard

---

packages/thirdParty/zendesk-widget/index.js

Fixing a typo, which resulted in incorrect article suggestions in the Zendesk Widget …

fix incorrect suggestion in Zendesk Widget when on Shop Grid page

---

packages/analytics/components/Analytics/index.jsx
packages/analytics/index.js
packages/constants/index.js
packages/drafts/components/DraftList/index.jsx
packages/drafts/index.js
packages/server/parsers/src/orgParser.js
packages/tabs/components/TabNavigation/index.jsx
packages/tabs/index.js
packages/tabs/utils/index.js

- Delete Analytics Overview Paywall.
- Make Drafts Paywall more clear by adding a dedicated org prop. (drafts is a business feature, but pro users see the tab as they get a paywall to upgrade to business)
Since October 2019, new users are not seeing the Advanced Analytics. The method also hides it to all pro users. We have a Paywall in the frontend for Analytics, as pro users would be prompt to upgrade to business to get access to it. Since that's no longer the case, this code is not being used and should be deleted.
https://github.com/bufferapp/buffer-web/blob/master/shared/models/user_model.php#L8649-L8651
Drafts Paywall: 
- …

Clean analytics paywall

---

packages/app-shell/components/AppShell/index.jsx
packages/app-shell/package.json
webpack.config.dev.js
yarn.lock

Swap out our AppShell for the new [standalone npm package](https://github.com/bufferapp/app-shell). 
-   [x] I have considered …

Use standalone app shell

---

.github/workflows/test.yml
.travis.yml

Use GitHub actions for CI testing instead of Travis. …

Use GitHub Actions for Tests

---

packages/composer/composer/utils/WebAPIUtils.js

- When user creates a Pinterest post with links on the description and no source url, we pick the first link as the source url
Pinterest doesn't post the text description if it contains links and no source url is defined
I'm using twitter-text to get urls, as it's the same we use to highlight links in the composer text
https://buffer.atlassian.net/browse/PUB-2477
-   [ ] I have tested my changes/additions in the latest Chrome, Firefox, and …

[PUB-2477] Add pinterest link as source url

---

packages/general-settings/components/LinkShortening/index.jsx

As of October 21st, we're no longer restricted to only using bit.ly links on LinkedIn. As such, the previous text was no longer relevant.
As of October 21st, we're no longer restricted to only using bit.ly links on LinkedIn. As such, the previous text was no longer relevant.
Helps to resolve any potential confusion as we now publish both Bit.ly and Buff.ly links to LinkedIn.
Previous Appearance: https://share.buffer.com/YEuye5vq
New Appearance: https://share.buffer.com/OAuJopRb
-   [ ] I have …

Remove text about LinkedIn Linkshortening

---

packages/app-shell/package.json
yarn.lock

Upgrade AppShell version to get copy change in Org Switcher (replace "No social accounts connected" by "No channels connected" )
https://buffer.atlassian.net/browse/PUB-3032 …

[PUB-3032] Upgrade appshell version

---

packages/queue/components/QueuedPosts/index.jsx
packages/queue/index.js
packages/shared-components/QueueItems/Header/index.jsx
packages/shared-components/QueueItems/index.jsx

Add timezone to queue and button to redirect to posting schedule.
https://buffer.atlassian.net/browse/PUB-3101
-   [x] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f)
-   [ ] I have …

[PUB-3101] Add timezone to queue

---

packages/composer/composer/components/LocationComposerBar.jsx

https://buffer.atlassian.net/browse/PUB-3144 …

[PUB-3144] Update "Learn More" link URL

---

packages/composer-editor/components/Editor/index.jsx
packages/composer-editor/components/Editor/story.jsx
packages/composer-editor/index.jsx
packages/composer-editor/package.json
yarn.lock

- Add slate plain text editor
I'm adding the text editor to a new package in buffer-publish so it's easier to test and use storybook.
This is separated in small PRs, with probably one per plugin so it's easier to follow what is being done.
https://buffer.atlassian.net/browse/PUB-3159
-   [x] I have commented my code, particularly in hard-to-understand …

[PUB-3159] Add slate plain text editor

---

packages/composer-editor/components/Editor/index.jsx
packages/composer-editor/components/Editor/styles.js
packages/composer-editor/components/Element/index.jsx
packages/composer-editor/components/Leaf/index.jsx

Add overCharLimit decorator and highlight decorator for mentions, hashtags and links.
~~Updating our testing libraries next so we can add tests~~  With react testing-library I'm only able to render the component, but not to interact with it properly. After a lot of digging and adding myself to their Slack channel, it seems interactions only work with Cypress. @hamstu, how are we with it? 
https://buffer.atlassian.net/browse/PUB-3166
https://share.buffer.com/eDuw9O95
-   [x] I have performed a …

[PUB-3166] Add overCharLimit decorator

---

packages/analytics-middleware/middleware.js
packages/analytics-middleware/middleware.test.js

This change adds check for organization selected to analytics middleware to ensure that org IDs are tracked in all events.
PUB-3118
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f …

[PUB-3118] Add org id check to analytics middleware

---

Dockerfile
Dockerfile.development

https://paper.dropbox.com/doc/Node-version-upgrade-Jan-2021-security-update--BCzF6s8jj5pG__nGh75pPb9YAg-c2lbNvFd39idTsKpuzIk3
- …

Node 2021-01 security updates

---

packages/i18n/translations/en-us.json
packages/i18n/translations/es-es.json
packages/profile-sidebar/components/ProfileSidebar/index.jsx

- Remove new tag from campaigns
https://buffer.atlassian.net/browse/PUB-3152
**No "New" tag in Campaigns:**
-   [ ] I have …

[PUB-3152] Remove new tag from campaigns

---

packages/engagement-promo-modal/components/EngagementPromoModal/index.jsx
packages/engagement-promo-modal/components/EngagementPromoModal/story.jsx
packages/engagement-promo-modal/index.js
packages/engagement-promo-modal/package.json
packages/modals/components/AppModals/index.jsx
packages/modals/middleware.js
packages/modals/reducer.js
packages/server/parsers/src/orgParser.js

- Add Engagement Promo Modal to Publish, to be shown to Free orgs from January 26 2021 to February 16 2021.
**Needs a code review until January 25**
https://buffer.atlassian.net/browse/PUB-3196 …

[PUB-3196] Add engagement promo modal

---

packages/modals/middleware.js

- Remove release date from engagement modal. …

Remove date

---

__snapshots__/snapshot.test.js.snap
package.json
packages/shared-components/GlobalEmptyState/index.jsx
packages/shared-components/GlobalEmptyState/story.jsx
packages/shared-components/index.js
yarn.lock

https://buffer.atlassian.net/browse/PUB-3202
Add shared-component for our global empty states. Separate PR will include business logic with new package.
- We were behind on snapshots so I went ahead and updated them. 
- Using beta UI version for now to fix react mismatch issues
[https://buffer.atlassian.net/browse/PUB-3202](url)
-   [ ] I have commented my …

[PUB-3202] Add global empty state component

---

packages/app-pages/components/AppPages/index.jsx
packages/app-pages/index.js
packages/i18n/translations/en-us.json
packages/missing-access-page/components/MissingAccessPage/index.jsx
packages/missing-access-page/components/MissingAccessPage/story.jsx
packages/missing-access-page/index.js
packages/missing-access-page/index.test.js
packages/missing-access-page/utils/index.js
packages/routes/index.js

Create missing access pages. (waiting to render them)
https://buffer.atlassian.net/browse/PUB-3203
- Create four different missing access states (admin, non-admin, admin who is a part of an org with access, non-admin who is a part of an org with access)
- Add new `no-access` route (Lauren preferred a new route for these changes)
We are blocked on rendering these pages until the global org switcher changes are deployed. In the meantime, I've commented out the route logic so this package can't be rendered. I'd like to go ahead and deploy these changes and will create another PR to render and update the state logic once global org switcher is deployed.
Admin: https://share.buffer.com/qGuXJrqL
Admin who is part of an org with access: https://share.buffer.com/xQun6zj1
Non-admin: …

Create missing access pages

---

packages/app-shell/reducer.js
packages/web/components/App/index.jsx

Adds a banner to notify users that they might need to reconnect their channels to fix recent issues they could be experiencing. 
[Slack thread for context](https://buffer.slack.com/archives/C01K9FWJVBJ/p1613761801088300?thread_ts=1613760313.070400&cid=C01K9FWJVBJ)
-   [ ] I kept …

Add reconnect channel banner

---

packages/app-shell/reducer.js

Reverts bufferapp/buffer-publish#1702 We don't need this anymore :)

Revert "Add reconnect channel banner"

---

packages/app-shell/reducer.js

Add error message for twitter

---

packages/app-shell/reducer.js

Reverts bufferapp/buffer-publish#1709

Revert "Add error message for twitter"

---

packages/app-shell/index.js
packages/shared-components/NavLink/index.jsx
packages/shared-components/NavTag/index.jsx

- Add a new paywall type of `<NavTag>`, to be used in the upgrade paths.
- CSS tweaks on NavLinks.
https://buffer.atlassian.net/browse/PUB-3419
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc …

[PUB-3419] Add Paywall NavTag

---

packages/campaigns-list/components/ListCampaigns/EmptyState/index.jsx
packages/campaigns-list/components/ListCampaigns/index.jsx
packages/campaigns-list/index.js
packages/campaigns-list/index.test.js
packages/campaigns-list/reducer.test.js
packages/constants/index.js
packages/i18n/translations/en-us.json
packages/plans/components/PlanColumn/style.jsx
packages/plans/components/PlanColumnWithPremiumSolo/style.jsx
packages/profile-sidebar/components/ProfileSidebar/index.jsx

- Add campaigns paywall: users without campaigns will see the Empty Page with a CTA to upgrade their plan
- Tracking for the free plan paywall action
- While working on it I realized there's no mention to campaigns in the plans page nor the [pricing page](https://buffer.com/pricing/publish#compare-features). After talking to Lauren I decided to add it to our plans page.
https://buffer.atlassian.net/browse/PUB-3423
-   [ ] I have tested my …

[PUB-3423] Add campaigns paywall

---

packages/app-pages/components/AppPages/index.jsx
packages/missing-access-page/components/MissingAccessPage/index.jsx
packages/missing-access-page/index.js
packages/missing-access-page/utils/index.js
packages/routes/index.js
packages/store/middlewares.js

Render missing access pages. 
https://buffer.atlassian.net/browse/PUB-3203
I decided to close the other PR and create a new one, as the old one had the wrong logic in the diff because of changes after I branched off the org switcher. 
These changes will not display yet until we change our [redirect-middleware](https://github.com/bufferapp/buffer-js-unauthorized-redirect/blob/master/src/middleware.js) logic. My original approach didn't cover all the cases, so I'm going to extract the redirect refactor into its own PR and look at other options. 
-   [ ] I have identified similar or …

[PUB-3203] Render missing access pages

---

package.json
packages/constants/index.js
packages/i18n/translations/en-us.json
packages/profile-sidebar/components/AddChannelButton/index.jsx
packages/profile-sidebar/components/AddChannelButton/style.js
packages/profile-sidebar/components/ProfileConnectShortcut/index.jsx
packages/profile-sidebar/components/ProfileSidebar/index.jsx
packages/profile-sidebar/index.js
packages/profile-sidebar/index.test.jsx
packages/shared-components/NavTag/index.jsx
yarn.lock

- Add "Add Channels" button as a paywall when user reaches channels limit
- Hide Connect Shortcut buttons when user reaches channels limit
**Edit:** also changed the NavTag paywall icon color to purple!
https://buffer.atlassian.net/browse/PUB-3422
**Regular button**
**On hover**
- …

[PUB-3422] Channels limit paywall

---

packages/app-pages/components/AppPages/index.jsx

Remove missing access page

---

packages/app-pages/components/AppPages/index.jsx
packages/app-pages/index.js

Redirect business trialist users to the new connection page while we find a solution for the user app-shell data. 
-   [ ] I have …

Use new connection page for business trialists

---

packages/drafts/index.js

Add the correct name for the segment event
I had refactored the segment name in a previous PR but hadn't actually changed it in the drafts package. 
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140b …

Fix drafts tracking name
