packages/example/.storybook/config.js
packages/web/.storybook/config.js

I was seeing the [same errors/issues mentioned here](https://github.com/webpack/webpack/issues/2356) when trying to run `npm run start` (i.e., Storybook) on my WIP `profile-sidebar` package, which was just a copy of the `example` package with minor tweaks.
It looks like because our Storybook config file passes the entire directory to `require.context`, which includes `node_modules`, there is some massive recursion of file watching that happens and ends up causing all kinds of bugs/errors. This doesn't apply to `components`/`shared-components` since they have no internally lerna-linked dependencies.
This PR changes the regex in the `context` call to only watch the `components` folder inside a package. Everything should work the same as before, just be sure you keep your components in that …

Prevent FSWatch errors by limiting the scope of `require.context`

---

packages/components/LinkStateless/index.jsx

This PR removes the outline from unstyled links! Some sort of indicator that the link has focus should be custom built in on our end, in this case for Tabs, we've got the lovely blue underline! :D 
@hharnisc 

remove outline from tabs

---

packages/profile-sidebar/reducer.js
packages/profile-sidebar/reducer.test.js
packages/queue/components/QueuedPosts/index.jsx
packages/queue/index.js
packages/queue/index.test.jsx
packages/queue/reducer.js
packages/queue/reducer.test.js
packages/sent/__snapshots__/snapshot.test.js.snap
packages/sent/components/SentPosts/index.jsx
packages/sent/index.js
packages/sent/index.test.jsx
packages/sent/reducer.js
packages/sent/reducer.test.js
packages/web/components/ProfilePage/index.jsx

To make things easier down the road I've shifted to storing profile data separately, keyed by ID. The biggest change here is in the queue and sent reducers, and then to the components so things are all handled correctly.
Essentially our state goes from this:
(⚠️ Note that the key was changed to `byProfileId` instead of `profilesById`)
To this:
At this point we're still forcing a fetch every time you change profiles, but in a future PR we can prevent that from happening when the data is already present.
👉  https://store-profile-data-by-id.publish.buffer.com

Store profile data by ID

---

buffer-publish/values.yaml

Use the new ssl crt that covers more domain (`analyze.buffer.com`)

Use the new ssl CRT that includes analyze.buffer.com

---

package.json
packages/queue/reducer.js
test.sh

We're seeing issues with `lerna run` (hanging, locking with no errors), so this PR adds a shell script (based on an older branch: https://github.com/bufferapp/buffer-publish/blob/task/add-test-script/test.sh) to make the test running process more simple.

Add new test bash script

---

packages/components/style/color.js

Add instagram `#e53c5f ` color to be used with social icons.

add Instagram color to @bufferapp/components

---

packages/components/lib/a11yTestHelper.js

Removes the color contrast tests from our axe-core tests, which were slowing things down a bit :) Should help solve the timeout issues we were seeing. For now, let's test color contrast with the axe extension! https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US

remove color contrast test from axe-core tests

---

packages/composer/action-creators/AppActionCreators.js
packages/composer/components/App.jsx
packages/composer/stores/AppStore.js
packages/composer/utils/DataImportUtils.js
packages/composer/utils/WebAPIUtils.js
packages/composer/utils/lifecycle-hooks/WebDashboardHooks.js
packages/profile-sidebar/reducer.js
packages/profile-sidebar/reducer.test.js
packages/queue/components/ComposerPopover/index.jsx
packages/queue/components/ComposerWrapper/index.jsx
packages/queue/components/QueuedPosts/index.jsx
packages/queue/index.js
packages/queue/reducer.js
packages/queue/reducer.test.js
packages/utils/postParser.js

https://app.getflow.com/organizations/369191/teams/339227/tasks/25406941
- open composer in edit mode when 'Edit' is clicked
- show data of post that was selected for editing
- save post edits
TODO:
Many thanks to @pioul, who will be tackling the final TODO's listed above while I'm out.

WIP: add editClickHandler to queue

---

packages/server/rpc/sharePostNow/index.js

This PR massages the error data a bit before passing it to the front end so it can be properly displayed as a notification toast! 🍞 
@hharnisc I'm wondering how this feels, this is a bit of a pattern now, [similar to how I handled errors in the `composerApiProxy`](https://github.com/bufferapp/buffer-publish/pull/168/files#diff-da43fc2dca049c032da20252e45b8981) and I wonder if we should think a bit more about how errors bubble up. A lot of it's still quite unknown to me, from what I can tell, somewhere along the line the error gets prefixed with the response code ("500 - ", "400 - ") followed by the JSON response from the Buffer API... the prefixed part is key since it makes it unparseable. Happy to chat more/pair if this doesn't make sense.
Oh, and fwiw the debugging support I dropped in …

Fix error notifications when 'Share Now' fails

---

packages/components/Notification/index.jsx
packages/components/__snapshots__/snapshot.test.js.snap
packages/notifications/__snapshots__/snapshot.test.js.snap
packages/queue/middleware.js

Show a success notification when your posts are successfully 'Share Now'd.
Also includes some minor tweaks to the design of the notifications; adjusted spacing and font size to [better match the mockups](https://buffer.wake.com/set/3/31)
cc @hharnisc Wake made the notification look bigger because of the @2x source image.

Share now success notification ✅ 🗯

---

packages/queue/components/ComposerWrapper/index.jsx
packages/utils/postParser.js

Import a few schedule-related pieces of data for MC to display them and allow their editing.
Flow: https://app.getflow.com/organizations/369191/teams/339227/tasks/25406941#activities/83949742
Publish doesn't support custom-time updates or pinned updates yet (i.e. there are no empty slots to click on, no calendar, etc), but by tweaking the MC store I was able to save pinned and custom-timed updates anyway, so those three pieces of data should be future-proof whenever such functionality lands in Publish
Hey @alvarezmelissa87, should be a quick one to review 😄 
Two things to note:
- I tested those changes with the main field (`due_at`), it was working great, and then added the two others but for some reason my dev env is broken in a new way now – I'm confident they work too though, there's …

Import schedule-related data for posts

---

Dockerfile.development
package.json
packages/async-data-fetch/middleware.js
packages/profile-sidebar/components/ProfileSidebar/index.jsx
packages/server/index.js
packages/server/package.json
packages/server/webpack.config.dev.js
packages/server/webpack.config.js
packages/server/yarn.lock
packages/web/index.jsx
yarn.lock

We've had a number of issues with buffer-publish (most of which are related to running webpack inside the Docker container); specifically:
1. 👀  Webpack would frequently stop picking up file changes, requiring a **painfully slow** restart of the entire publish container to get things working again. The precise cause here is unknown but this is likely a Docker issue specific to macOS.
2. ♻️ Any changes to `packages/server/**` would cause `nodemon` to restart the server (which is great and expected) but would _also_ unnecessarily restart the webpack bundling (since that was a child process of the node server). This meant **waiting upwards of 30-45 seconds before you could view the page again.**
3. 🔥 HMR was not working correctly (except for a very limited set of components) nor were …

✨ Better Dev Environment 🙏

---

Dockerfile.development

Recently `nodemon` has stopped restarting the server when things change. I suspect this is due to changes in Docker. As such I've switched nodemon to use the 'legacy' watching mode. This mode is slower as it uses polling, but that should make little to no difference in our case as we're only watching ~30 files in the server package.
Hey @emily-plummer, sounds like this was happening to you too. Would love for you to test this out. I'll merge it into master and you'll just have to run `./dev rebuild publish`.
cc @alvarezmelissa87 as well.

Use legacy watch mode with nodemon

---

packages/composer/package-lock.json
packages/server/package.json
packages/server/rpc/index.js
packages/server/rpc/performanceTracking/index.js
packages/server/webpack.config.js
packages/store/index.js
packages/store/package.json
yarn.lock

To add front-end performance tracking on Datadog.
I hope this is useful :smile:.
The middleware is just a wrapper around @bufferapp/chronos APIs and exposes Chronos methods via action creators.
The basic functionality is to automatically track all async data fetch requests. 
Also you can easily use it to track any kind of events you are interested in with:
```
store.dispatch(performanceActions.startMeasure({ name: 'foo' }));
store.dispatch(performanceActions.stopMeasure({ name: 'foo' }));
```
or measuring any event from navigation start  with:
```
dispatch(performanceActions.measureFromNavigationStart({ name: 'foo' }));
```
The data sent to Datadog has the following structure:
```
{
"duration":745.6550000000007,
"name":"buffer.perf.queuedPostsFetch",
"navigationStart":1512788235288, …
```

Add front-end performance tracking

---

packages/server/package.json
packages/utils/package.json
packages/utils/postParser.js
packages/utils/postParser.test.js

To fix cases where `LinkifiedText` would go into an endless loop because for retweets with comments we would pass the retweet's links as the retweet comments' links when in reality they're two different entities.

Extract retweet comment links from retweet comment - not from retweet

---

package.json
yarn.lock

To patch a potential [security vulnerability](https://nvd.nist.gov/vuln/detail/CVE-2017-18214) with versions of moment.js prior to 2.19.3.

Upgrade to moment v2.19.3

---

packages/app-switcher/middleware.js
packages/app-switcher/package.json
packages/server/rpc/upgradeToPro/index.js
packages/server/rpc/upgradeToPro/test.js
packages/stripe/middleware.js
packages/stripe/middleware.test.js
packages/stripe/package.json
packages/utils/getClassicBufferURL/index.js
packages/utils/index.js

Uses the new Account Management upgrade endpoint specified on
https://github.com/bufferapp/README/blob/master/billing/api-endpoints.md
and released on https://github.com/bufferapp/buffer-web/pull/15173.
The RPC endpoint encapsulates the config details that the user can't
choose (product is "publish" and the plan is "pro").

Use new Account Management upgrade endpoint

---

packages/app-switcher/package.json

While fixing a conflict on #296 I forgot to change the version number for `publish-utils` on the app switcher package 🙊

Fix app switcher

---

packages/profile-sidebar/middleware.js

Use new URL for going directly to own org. (https://github.com/bufferapp/buffer-web/pull/15221)

Use new URL to go to own org

---

packages/queue/package.json
yarn.lock

Update buffer-composer version to 1.10.4 to get custom scheduled posts on buffer-publish and to fix  media elements' stack order.
Task: [PUB-613](https://buffer.atlassian.net/browse/PUB-613)
Task: [PUB-573](https://buffer.atlassian.net/browse/PUB-573)

Update composer package

---

packages/beta-redirect/middleware.js
packages/beta-redirect/middleware.test.js
packages/beta-redirect/reducer.js

…Buffer Free Users” to Buffer Classic if they have the “new_publish_new_buffer_free_users” feature flip.
Adding a condition in new Publish, so that it doesn’t redirect “New to Buffer Free Users” to Buffer Classic if they have the “new_publish_new_buffer_free_users” feature flip.
Verify that the condition is placed correctly.

[PUB-632] Adding condition in new Publish for new feature flip

---

packages/queue/package.json
yarn.lock

Update buffer-composer version to 1.10.5 to get custom scheduled posts on buffer-publish and to fix media elements' stack order.
Task: [PUB-613](https://buffer.atlassian.net/browse/PUB-613)
Task: [PUB-573](https://buffer.atlassian.net/browse/PUB-573)

Update buffer-composer version to 1.10.5

---

packages/shared-components/PostFooter/index.jsx
packages/shared-components/PostFooter/story.jsx
packages/utils/postParser.js
packages/utils/postParser.test.js

Add a dedicated footer message in the queue for custom scheduled posts.
[PUB-539](https://buffer.atlassian.net/browse/PUB-539)
We will only be able to see this properly with buffer-composer on 1.10.4 or higher (adds ability to custom schedule posts)

Add distinction for custom scheduled posts in the queue

---

packages/upgrade-modal/components/UpgradeModal/index.jsx

Fix Upgrade Modal stack order so it stays on top of the composer
Task: [PUB-648](https://buffer.atlassian.net/browse/PUB-648)

[PUB-648] Composer stacks on top of upgrade modal

---

packages/app-switcher/package.json
packages/app-switcher/reducer.js
packages/app-switcher/reducer.test.js

When feature ‘new_publish_new_buffer_free_users’ is present prevent showing the app switcher in New Publish.
Verify that the app switcher doesn't display for New Buffer Free Users.

[PUB-623] Don't show app switcher for NTB-F Users

---

package.json
packages/queue/components/ComposerPopover/index.jsx
yarn.lock

Popover component comes with width: 100vw causing an horizontal scroll when someone opens the composer. Updated the components package to allow `width: auto` for popover. 
https://buffer.atlassian.net/browse/PUB-658

[PUB-658] Remove horizontal scroll when the composer is opened in publish

---

packages/queue/components/ComposerPopover/index.jsx

Change composer popover width from auto to 100% to allow users to click outside the composer to close it. 
This is from a bug fix I made earlier today regarding the horizontal scroll. Width set to auto causes the user to not have the option to close out of the composer. https://buffer.atlassian.net/browse/PUB-658

Change composer popover width from auto to 100%

---

packages/profile-page/components/ProfilePage/index.jsx
packages/queue/middleware.js
packages/queue/middleware.test.js

We are now reloading the post list in the queue when the scheduled times get modified in the settings panel, to ensure that we are always have the right schedule post times for the posts, and the Drag and Drop works as expected as a consequence

[PUB-500] Addressing issue with Drag and Drop not working when intended

---

packages/product-features/components/FeatureLoader/index.jsx
packages/product-features/components/FeatureLoader/story.jsx

Falling back component to null when no fallback component is passed into the parent... otherwise it can cause an error
@anafilipadealmeida this should mean you don't need to do the `fallback={null}` thing

Adding null fallback for FeatureLoader component to handle failure more gracefully when no fallback is supplied

---

packages/app-sidebar/components/AppSidebar/index.jsx
packages/app-sidebar/components/AppSidebar/story.jsx

To hide the '(Coming soon)' string when we are on Analyze, as in that case we know the user has access to Analyze.
Hey @hamstu super small one :smile:, just want to make sure I'm not missing any cases where we could have that icon active and not being an Analyze customer.
Also tried to run `jest -u` to update the snapshots but I'm getting lots of errors parsing files from node_modules. Any reason for that?
Thanks!

hide (coming soon) on analyze in the sidebar

---

packages/profile-page/components/ProfilePage/index.jsx
packages/store/index.js
packages/store/package.json
packages/store/reducers.js
packages/tabs/components/TabNavigation/index.jsx
packages/tabs/index.js

Add Drafts Tabs for B4B (under feature flip drafts_new_publish). The content inside the drafts is still a WIP, but since it's under the feature flip that's ok :)
https://paper.dropbox.com/doc/Scoping-Drafts-for-B4B-in-New-Publish--APgxFyo0k4hehN9AhXk05A~GAg-lhOmSwceGa305exIkk3Ml

Add Drafts Tabs

---

packages/queue/package.json
yarn.lock

Update composer version to 2.1.8 in fix of publish listening to classic web interfaces file. 
https://buffer.atlassian.net/browse/PUB-869

Update composer version to 2.1.8

---

packages/modals/middleware.js
packages/modals/middleware.test.js
packages/modals/package.json
packages/modals/reducer.js
packages/modals/reducer.test.js
packages/modals/util/window-hash.js
packages/server/rpc/upgradeToPro/index.js
packages/server/rpc/upgradeToPro/test.js
packages/stripe/middleware.js
packages/stripe/middleware.test.js
packages/tabs/index.js
packages/upgrade-modal/middleware.js
packages/upgrade-modal/middleware.test.js
packages/upgrade-modal/reducer.js
packages/upgrade-modal/reducer.test.js

Adds source tracking to the upgrade modal so we can get a better idea of where upgrades are coming from.
https://buffer.atlassian.net/browse/PUB-888

[PUB-888] Add source tracking to upgrade modals

---

packages/composer-popover/components/ComposerWrapper/index.jsx
packages/composer-popover/package.json
yarn.lock

Composer fix helps with flashing states in composer bug. We are now reselecting profiles only after a profile is selected from profile sidebar.
https://github.com/bufferapp/buffer-composer/pull/111

Update composer version to 2.2.5

---

packages/server/webpack.config.common.js

Add analyze packages to exclusion rule in webpack. Add analyze less loader for loading and bundling the .less files that Analyze uses.
Hey @hamstu . Went ahead and added this logic so I could start importing packages. Are you happy with this or were you wanting to make changes to the logic? I'm going to branch off of this for now until I hear from you next week 😄 

Add Analyze packages to exclusion rule and add less loader

---

packages/composer-popover/package.json
yarn.lock

Updating composer to same version as classic.
(Change was for a bugfix only in classic.)

Update composer to v2.2.6

---

packages/server/index.html

Adding a class to fix the calendar style bug when editing a post on queued tab.
I realize this isn't the best approach, it's a temporary quick one, so when we find out how to exclude the styles that are actually affecting here we should remove this line

Fixing styles for broken calendar on edit

---

packages/server/rpc/upgradeToPro/index.js
packages/server/rpc/upgradeToPro/test.js

Change the `cta` we're sending to the upgrade endpoint to pass a string matching the [guidelines from data](https://github.com/bufferapp/README/blob/master/runbooks/data-tracking/cta-parameters.md).
@mallen5311 Tagging you for your thoughts on these strings 😄 — let me know if anything is confusing.

Follow guidelines for upgrade/Stripe `cta` tracking

---

packages/composer-popover/package.json

Upgrade the composer to 2.2.7.
The Redux DevTools integration inside the composer is causing New Publish to crash and preventing the composer to load in Classic (only for people with the Redux DevTools extension installed).
This change disables the integration for now.

Disable Redux DevTools in Composer to Prevent Crash

---

packages/analytics/index.js
packages/server/rpc/index.js
packages/store/index.js
packages/store/reducers.js
yarn.lock

Remove average-table and profile-selector from analytics because of analyze package conflicts with store

Remove average-table and profile-selector from analytics

---

packages/general-settings/components/GeneralSettings/index.jsx
packages/general-settings/components/GeneralSettings/story.jsx
packages/general-settings/index.js
packages/general-settings/reducer.js
packages/general-settings/reducer.test.js
packages/pusher-sync/package.json
packages/queue/components/InstagramDirectPostingBanner/index.jsx
packages/queue/components/QueuedPosts/index.jsx
packages/queue/index.js
packages/queue/package.json
packages/queue/reducer.js
packages/server/package.json
yarn.lock

Ensure we use the correct field when deciding to show the IG Direct banners/settings. The previous one looked right, but wasn't (See email sent to publish team for background on that 😉 )
I also cleaned up some of the logic in the queue packages's `mapStateToProps` code. Should be a little more clear now.

[PUB-867] Use new correct field for showing IG direct prompts ✅✨

---

packages/queue/components/QueuedPosts/index.jsx

Making small adjustments to the Show/Hide Calendar button styles to fix box-shadow.

Fixing Show/hide calendar box shadow looking off.

---

packages/notifications-provider/utils/notifications.json

When a user authenticates / disconnect with bitly we need to display some success/error messages, so I've added the messages to the notifications implementation

PUB-793 | Adding notification messages for bitly auth success and faiure

---

analyze.config.js
packages/analytics/index.js
packages/analytics/package.json
packages/server/rpc/index.js
packages/store/index.js
packages/store/package.json
packages/store/reducers.js
yarn.lock

As a B4B user, I am able to view and interact with the Top Posts analytics.
https://buffer.atlassian.net/browse/PUB-921
The rpc call for this component doesn't work locally, only in production. I talked to Federico, and it's because of the way the data is synced locally. Just a heads up if you're viewing locally.  
Also, the width of the publish container is affecting the styling of the posts-table. There's a `max-width: 49rem;` It would need to be at least `54rem` to appear correctly. Was there a reason `49rem` was chosen? Is it ok to change it for this?

[PUB-921] Add posts-table component to analytics

---

packages/pusher-sync/package.json
packages/server/package.json
yarn.lock

Updating publish-parsers to latest version with additional schedule slots included so that we can schedule content from slots in the ui in new publish

PUB-686 | Updating publish-parsers to latest version with additional schedule slot parameters

---

packages/composer-popover/components/ComposerWrapper/index.jsx
packages/sent/components/SentPosts/index.jsx
packages/sent/index.js
packages/sent/reducer.js
packages/sent/reducer.test.js
packages/server/rpc/sentPosts/index.js

Allow a user to click and expand an image in sent posts. 
Through bugsnag, we were able to see that many users tried to click on images in Sent Posts, and the image wouldn't expand.
https://app.bugsnag.com/buffer/buffer-publish/errors/5c05d8c0223e2d0019ffff81?filters[event.since][0]=30d&filters[error.status][0]=open

Add image click logic to sent posts

---

packages/sent/index.js

Handle error for forEach if orderedPosts is not an array
https://app.bugsnag.com/buffer/buffer-publish/errors/5c2cccf7851927001c792b0d?filters[event.since][0]=30d&filters[error.status][0]=open
Noticed this error in bugsnag after merging the imageClick PR for sent posts this morning. `TypeError · e.forEach is not a function` I wasn't able to replicate the error while impersonating the users, but I'm assuming orderedPosts must be undefined or not an array.  

Handle forEach error if orderedPosts is not an array

---

packages/shared-components/Post/InstagramPostMetaBar/index.jsx
packages/shared-components/Post/PinterestPostMetaBar/index.jsx
packages/shared-components/Post/RenderPostMetaBar/index.jsx
packages/shared-components/Post/index.jsx
packages/shared-components/PostMetaBar/index.jsx

Added a couple of small tweaks for the PostMetaBar component.
- Add a change to handle subprofiles & subprofile being undefined.  
- Check if a post is sent or in the queue, and assign bottom-margin based on it
- Check if locationBar is true instead of null (to catch undefined)
https://buffer.slack.com/archives/C151RRDL1/p1545424352041200

Small tweaks to handle errors and styling in PostMetaBar

---

packages/composer-popover/package.json
yarn.lock

Update composer version to 2.5.0 to include webpack upgrade

Update composer version to 2.5.0 to include webpack upgrade

---

packages/composer-popover/package.json
packages/pusher-sync/package.json
packages/server/package.json
yarn.lock

This PR includes an updated version of the composer and also the user parser.
* Composer: See the [CHANGELOG](https://github.com/bufferapp/buffer-composer/blob/master/CHANGELOG.md) for details. It's almost entirely to support IG direct video.
* Parsers: See [this commit](https://github.com/bufferapp/buffer-js-publish-parsers/commit/ecb6720efee786934fef665939afbdf30b18a123)

Upgrade Composer to v2.6.6

---

packages/server/lib/composerAjaxBuffermetrics.js

Based on chat and Zoom with @michael-erasmus I'm going to pause the composer tracking for now until we can fix some of the issues.
Issues appear to be:
* The `action` is coming through as null in the pipelie
* The user id is not getting sent

[Hotfix] Temporarily pause tracking for composer

---

packages/sent/reducer.js

Clearing default scheduled date and time when sharing a post again (re-buffer), because currently it marks as is set in a past date.

[PUB-1027] Clearing default scheduled time when sharing a post again (re-buffer).

---

packages/queue/reducer.js

When the user does not have a IG Business Profile but converts to it with the modal opened, this fix prevents to render content after the request is successful, 1s before redirecting the user.

Fix IG modal flashing wrong content

---

packages/server/index.js

There is a fair amount of unnecessary requests to the `buffer-login` services generated from the publish `health-check` route.
This route was registered after the `validateSessionMiddleware` which redirects to `login.buffer.com` if the session is not valid, which is always the case for the healthcheck.

Move /health-check before the validateSessionMiddleware

---

packages/composer-popover/package.json
yarn.lock

Update composer version to remove reference to ig thumbnail feature flip and change button copy from Thumbnail to Cover

Update composer version to 2.6.13

---

packages/notifications-provider/utils/notifications.json

This should cover all the connection error messages passed from buffer-web.

Add new error key for connection error messages

---

helm/values.yaml
package.json
packages/server/index.js
packages/server/package.json
yarn.lock

Following some unexpected downtime we've decided to add the DD APM for better monitoring in New Publish.
@erickhun Let me know if this looks good to you!
@kiriappeee / @erickhun I'm also wondering if either of you know a way we can know whether the `env` is staging vs production? I'm not sure if we have an env variable exposed to the publish server for this. (See below image)

Add `dd-agent` for better monitoring

---

helm/values.yaml

This PR should prevent the pod restarts by raising the memory limit
Details: https://buffer.slack.com/archives/C151RRDL1/p1549932022055800

Raise the memory limit to avoid pod restarts

---

helm/values.yaml

Raise the number of pods to 10, so when restart happens in every 2 hours our users wont feel that much of an impact.

Raise the replica count to reduce the impact of application memory leak

---

packages/pusher-sync/package.json
packages/server/package.json
packages/server/rpc/sharePostNow/index.js
packages/shared-components/Post/index.jsx
packages/shared-components/PostErrorBanner/index.jsx
yarn.lock

To allow links to be separate from error messages, the post errors are getting sent from api as an object with text and link fields. This way, messages with links will not show up in the top right notification and the link will be used as a Learn More button in the queue card. 

Receive post error as an object with link from api

---

packages/profile-sidebar/components/ProfileSidebar/index.jsx
packages/pusher-sync/package.json
packages/server/package.json
yarn.lock

Change copy so business users see Publish Business in the Sidebar.
This also required changes in featureParser.js on buffer-js-publish-parsers
Enterprise plans are being considered free, I'm gonna leave a note in Jira, as it seems a different issue. For the remaining plans this works well.

[PUB-1121] Change product copy for business users

---

packages/past-reminders/reducer.js
packages/sent/reducer.js

Reseting due_at and scheduled_at dates to prevent displaying a previous date when re-buffering a post.

Reseting due_at and scheduled_at dates on re-buffer

---

packages/profile-sidebar/components/ProfileDragWrapper/index.jsx
packages/profile-sidebar/components/ProfileList/index.jsx
packages/profile-sidebar/components/ProfileList/story.jsx
packages/profile-sidebar/components/ProfileListItem/index.jsx
packages/profile-sidebar/components/ProfileLockedHeader/index.jsx
packages/profile-sidebar/components/ProfileLockedHeader/story.jsx
packages/profile-sidebar/components/ProfileSidebar/index.jsx
packages/profile-sidebar/components/ProfileSidebar/story.jsx
packages/profile-sidebar/index.js
packages/profile-sidebar/middleware.js
packages/profile-sidebar/reducer.js
packages/profile-sidebar/reducer.test.js
packages/server/rpc/index.js
packages/server/rpc/reorderProfiles/index.js

Give the option for users to drag and reorder their sidebar profiles
https://buffer.atlassian.net/browse/PUB-1115
Refactored locked and unlocked profiles into one list so that drag and drop would work for all. 
@hamstu Currently getting a storybook error when running tests for `Could not find the drag and drop manager in the context of DragSource(ProfileDragWrapper)`. Will look more into it. Curious if you ran into this error when you were working on queue drag and drop

[PUB-1115] Allow a user to drag and reorder their sidebar profiles

---

packages/pusher-sync/package.json
packages/sent/components/SentPosts/index.jsx
packages/sent/index.js
packages/sent/package.json
packages/server/package.json
packages/shared-components/BDSButton/index.jsx
packages/shared-components/BDSButton/story.jsx
packages/shared-components/BusinessTrialOrUpgradeBanner/index.jsx
packages/shared-components/BusinessTrialOrUpgradeBanner/story.jsx
packages/shared-components/index.js
yarn.lock

Show analytics upgrade path CTA banner in Sent Posts tab
https://buffer.atlassian.net/browse/PUB-1169

[PUB-1169] Show upgrade path CTA banner in Sent Posts

---

packages/composer-popover/package.json
yarn.lock

This composer change allows team members of business plans to have access to Instagram Cover. There's also a change that hides the edit cover button if a user doesn't have direct posting enabled.
https://buffer.atlassian.net/browse/PUB-1171

Upgrade Composer to v2.6.17

---

packages/queue/components/QueuedPosts/index.jsx

Changes the name of the mini calendar in the UI to "Show Overview" to avoid confusion with large iframe calendar. 

Changes name of mini calendar in UI.

---

packages/pusher-sync/package.json
packages/server/package.json
yarn.lock

User is seeing their New Publish dashboard crashing to a white screen when clicking on "Sent Posts". When checking the console, an error appears for "RangeError: Maximum call stack size exceeded."
Fixed by filtering facebook links with incorrect indices in publish-parsers package
https://buffer.atlassian.net/browse/PUB-1015

Bump publish-parsers package to 1.13.4

---

packages/tabs/components/TabNavigation/index.jsx
packages/tabs/index.js

Removing past reminders feature flip from the code so it's accessible to all users.

Removing past reminders feature flip

---

packages/queue/middleware.js
packages/queue/middleware.test.js

When a user updates the schedule time on Settings, it doesn't automatically update the posts time in the queue, until page reload.
https://buffer.atlassian.net/browse/PUB-1136

[PUB-1136] Updating schedule time for queue posts.

---

packages/queue/components/QueueItems/index.jsx

On the queue tab, when there is a very long post, it overlaps the other posts below it.

[PUB-1181] Styling adjustment for UI bug on the queue with long posts.

---

packages/pusher-sync/package.json
packages/server/package.json
yarn.lock

Update publish-parsers package to 1.14.1
Fixes this error: https://buffer.atlassian.net/browse/PUB-1151
When switching from custom scheduled time to time slot, queue item isn't updated 

Update publish-parsers package to 1.14.1

---

packages/general-settings/components/GeneralSettings/index.jsx
packages/general-settings/components/GoogleAnalytics/index.jsx
packages/general-settings/components/GoogleAnalytics/story.jsx
packages/general-settings/components/LinkShortening/LinkShorteningWrapper.jsx
packages/general-settings/components/LinkShortening/index.jsx
packages/general-settings/components/LinkShortening/story.jsx

Contributors should see Link Shortening settings disable, and not be able to perform any action.
- Disable Link shortening select for Contributors
- Align Link shortening select when connect bit.ly button is not displayed (Contributors and Free plan)
- Disable Google Analytics toggle for Contributors
[PUB-1246](https://buffer.atlassian.net/browse/PUB-1246)

[PUB-1246] Contributors should see Link Shortening Settings disabled

---

packages/tabs/components/TabNavigation/index.jsx

- Ensure that "Settings" always appear last in the navbar. Sometimes it would appear before calendar (for Pro + B4B customers)

Ensure settings is always the last tab in the nav bar.

---

packages/composer-popover/package.json
packages/drafts/reducer.test.js
yarn.lock

Update composer version to 2.6.19 to hide Edit Group and Create Group buttons in New Publish

Update composer version to hide Group buttons in New Publish

---

packages/sidebar/package.json
packages/store/package.json
yarn.lock

Updating app-sidebar package version to 1.10.5 to reverse validation to track less free users for FS.

Updating app-sidebar package version to 1.10.5.

---

packages/preferences/components/Preferences/index.jsx
packages/profile-page/components/ProfilePage/index.jsx
packages/server/index.html

Fixing sidebar styling position when user scrolls on Firefox, specifically the profile sidebar component.

[PUB-1239] Fixing sidebar styling position when user scrolls on Firefox.

---

packages/tabs/components/TabNavigation/index.jsx
packages/tabs/components/TabNavigation/story.jsx

Make sure both Contributors and Managers of Business Profiles (Teams) see drafts and analytics tabs.
[PUB-1250](https://buffer.atlassian.net/browse/PUB-1250)
[PUB-1251](https://buffer.atlassian.net/browse/PUB-1250)
There was a regression caused by this [PR](https://github.com/bufferapp/buffer-publish/commit/d3441e740125c6076afe1883c27a3a6c9f5a542b#diff-bbd13035738703c150624fc45a666579):
`isBusinessAccount` condition was replaced by `!features.isFreeUser()`. I believe the intention of the change was to include Pro Users. However, since `isBusinessAccount` is related to a specific profile (a Free User who is part of a team has profiles that are `isBusinessAccount`) and not the Business Plan, Team Members were excluded with the change.
I've added a couple of stories on Storybook so in the …

Show analytics and drafts tab for team members

---

packages/composer-popover/package.json
yarn.lock

Split composer version into two different branches. Publish composer is updated to 3.0.0 and will keep using the master branch. 
https://buffer.atlassian.net/browse/PUB-1262

Update composer version to 3.0.0 for composer split

---

packages/app-switcher/components/AppSwitcher/index.jsx
packages/preferences/components/Preferences/index.jsx
packages/profile-page/components/ProfilePage/index.jsx
packages/tabs/components/TabNavigation/index.jsx

En Firefox the top menu is not staying visible like it is on Chrome, while the user scrolls through the update.

[PUB-1239] Fixes top menu scrolling on FF instead of staying visible

---

packages/profile-page/components/ProfilePage/index.jsx
packages/shared-components/Tabs/index.jsx
packages/tabs/components/TabNavigation/index.jsx

Team Members should see the Calendar Tab. Used `isBusinessAccount` prop to flag profiles from team members (includes all Managers and Contributors of team accounts).
[PUB-1242](https://buffer.atlassian.net/browse/PUB-1242)
Me and @karelm had talked about what to do in those cases where we have a FeatureLoader and we also want to make the feature available for team members. The solution would be to put the Team Member condition in the Fallback, which in this case would be something like this:
However, after confirming with Super that the Calendar tab is going to be available for all Pro users and up, and looking at how the validation on the other tabs was done in the code, I decided to remove the FeatureLoader, to keep consistency and readability and to optimize the code.

[PUB-1242] Show calendar tab to team members

---

packages/pusher-sync/package.json
packages/server/package.json
yarn.lock

Updating parsers version to 1.14.3, to include new fields commentEnabled and commentText

Updating parsers version to 1.14.3

---

packages/queue/components/QueuedPosts/index.jsx

- Fixes a visual bug in Safari which causes the faux composer input to look disabled: 

Fixes styling issue with faux cmoposer input on Safari.

---

packages/profile-sidebar/components/ProfileConnectShortcut/index.jsx

Add tracking to Profile Connect buttons (Instagram, Twitter, Facebook)
https://buffer.atlassian.net/browse/PUB-1302

Add tracking to Profile Connect buttons 

---

packages/composer-popover/package.json
yarn.lock

Update composer version to 3.0.2 to include changes of removing notification permanently by clicking checkbox instead of checkbox and close button. 
https://buffer.atlassian.net/browse/PUB-1024

Update composer version to 3.0.2

---

helm/values.yaml

Since there isn't an easy way to send a part of the traffic to the PHP 7.1 API and we're already using it in many places, this PR should start sending all the traffic there too from New Publish.
I'd love to have your eyes on it @erickhun since I'm not fully sure if I need to change something else. 

Update API env. variable to use new PHP 7 api

---

packages/bookmarklets/index.js
packages/bookmarklets/middleware.js
packages/bookmarklets/package.json
packages/server/rpc/bookmarklets/profileQuickAnalytics/index.js
packages/server/rpc/bookmarklets/updateRecheck/index.js
packages/server/rpc/index.js
packages/store/index.js

Creating rpc calls for update recheck and profile quick analytics to user Bookmarklets in New Publish as it is on Buffer web. (http://hi.buffer.com/090600e18142)

[PUB-1193] Creating rpc calls for update recheck and profile quick analytics

---

packages/composer-popover/package.json
yarn.lock

Update composer-popover package from version 3.0.2 to 3.0.3
Context: https://buffer.atlassian.net/browse/PUB-1143

Update composer from 3.0.2 to 3.0.3

---

packages/profile-sidebar/components/ProfileConnectShortcut/index.jsx
packages/profile-sidebar/components/ProfileSidebar/index.jsx
packages/profile-sidebar/components/ProfileSidebar/story.jsx
packages/profile-sidebar/index.js
packages/profile-sidebar/middleware.js
packages/profile-sidebar/reducer.js

If a free user is at their profile limit and clicks one of these sidebar prompts, we launch a modal that asks them to upgrade
If it's a pro user, redirect them to Org Admin's connect account page. This page already has CTAs built in if the user is at the profile limit and so is a more direct call to action.
https://buffer.atlassian.net/browse/PUB-1258

[PUB-1258] Create clearer CTAs if profile limit is reached on sidebar prompt click

---

packages/change-password/package.json
packages/edit-email/package.json

Updating buffer ui version to the latest one, since the onBlur option for Buffer Grid save URL is in that last version.

Updating buffer ui version to the latest one.

---

jest.config.js

The problem was that jest was trying to execute the tests in node_modules. I think this PR can solve that. 

Updated jest config so the test pass again

---

packages/grid/index.js
packages/grid/middleware.js
packages/grid/reducer.js
packages/shared-components/GridList/index.jsx

Saving link only when has changed, prepending protocol for urls without it.

Grid fixes in link saving

---

packages/general-settings/components/GeneralSettings/index.jsx
packages/general-settings/index.js
packages/general-settings/middleware.js
packages/general-settings/reducer.js
packages/ig-direct-posting-modal/index.js
packages/ig-direct-posting-modal/index.test.jsx
packages/ig-direct-posting-modal/middleware.js
packages/ig-direct-posting-modal/package.json
packages/ig-direct-posting-modal/reducer.js
packages/ig-direct-posting-modal/reducer.test.js
packages/queue/components/QueuedPosts/index.jsx
packages/queue/index.js
packages/store/index.js
packages/store/reducers.js

Remove IG new Authentication Flow Feature Flip.
Move Direct Posting actions from general-settings to ig-direct-posting-modal
[PUB-1354](https://buffer.atlassian.net/browse/PUB-1354)

[PUB-1354] Remove ig new authentication feature flip

---

packages/analytics/components/AnalyticsList/index.jsx
packages/analytics/components/Notification/index.jsx

Updates the notification for non-business Instagram accounts to prompt them to update their account to an Instagram business account in order to view analytics and set up direct scheduling. 

[PUB-1405] Update Analytics notification for non-business Instagram accounts

---

packages/tabs/components/TabNavigation/index.jsx
packages/tabs/components/TabNavigation/story.jsx
packages/tabs/index.js

Remove the 'Learn about Buffer for Business' option when users are trialing Pro Publish. 

[PUB-1408] Remove Business upgrade path from Pro trialists

---

packages/profile-page/components/ProfilePage/story.jsx
packages/tabs/components/TabNavigation/story.jsx
packages/tabs/index.js

Profile Page stories were failing because of a check for a user being on a trial. The value was undefined at the time of the check. 

Fix profile page story

---

packages/analytics/components/Notification/index.jsx
packages/tabs/components/TabNavigation/index.jsx
packages/tabs/index.js

Hides the Overview tab under Analytics for Pinterest and LinkedIn accounts for Business trialists new to New Publish only. 

[PUB-1414] Hide Analytics Overview tab for Business Trialists using Pinterest/LinkedIn

---

packages/analytics/index.js
packages/i18n/translations/en-us.json
packages/modals/middleware.js
packages/modals/reducer.js
packages/pusher-sync/package.json
packages/server/package.json
packages/server/rpc/cancelTrial/index.js
packages/server/rpc/changeDateTimePreferences/test.js
packages/server/rpc/index.js
packages/server/rpc/upgradeToPro/index.js
packages/stripe/middleware.test.js
packages/upgrade-modal/components/UpgradeModal/index.jsx
packages/upgrade-modal/index.js
packages/upgrade-modal/middleware.js
packages/upgrade-modal/middleware.test.js
packages/upgrade-modal/reducer.js
yarn.lock

https://buffer.atlassian.net/browse/PUB-1399
If the user gets to the end of the trial and doesn't have any credit card information entered, they should see an upgrade modal prompting them to upgrade to Pro upon next time they load up Buffer, refresh, etc (or as a secondary, minor CTA of downgrade to Free) 
We may need to confirm that a user is automatically enrolled if they've entered credit card information. Currently not checking the logic to see if user has already entered credit card information before showing modal.

Display upgrade modal when user reaches end of pro trial

---

packages/composer-popover/package.json
packages/server/rpc/composerApiProxy/index.js
yarn.lock

This fixes this issue: https://buffer.atlassian.net/browse/PUB-1017 by accepting an HTTP method param that we get from the composer.

Add HTTP method to composer API proxy requests

---

packages/composer-popover/package.json
yarn.lock

Changing composer version to 3.4.4.

[PUB-1392] Changing composer version to 3.4.4.

---

packages/composer-popover/package.json
yarn.lock

Adjust composer tooltip for comment enabled component
The composer tooltip was in place, but wasn't popping up, so I've upgraded to use the components library ArrowIconPopover so it should be okay now

Adjust composer tooltip for comment enabled component

---

packages/i18n/translations/en-us.json
packages/ig-new-first-comment-user-modal/README.md
packages/ig-new-first-comment-user-modal/components/InstagramNewFirstCommentUserModal/InstagramNewFirstCommentUserModal.css
packages/ig-new-first-comment-user-modal/components/InstagramNewFirstCommentUserModal/index.jsx
packages/ig-new-first-comment-user-modal/components/InstagramNewFirstCommentUserModal/story.jsx
packages/ig-new-first-comment-user-modal/index.js
packages/ig-new-first-comment-user-modal/package.json
packages/modals/components/AppModals/index.jsx
packages/modals/middleware.js
packages/modals/reducer.js
packages/modals/util/showModal.js

[PUB-1365](https://buffer.atlassian.net/browse/PUB-1365) -  Implementing Welcome to Instagram first comment modal
Users should see this modal if they have the first_comment feature and don't have the readmessage `paid_users_to_new_publish_ig_first_comment`
or can be triggered via the ?mk=instagram-new-first-comment-user-modal query param
the readmessage is automatically triggered when they see this, so dismiss / not it will disappear after first viewing to ensure its not overbearing on the end user

Instagram first comment modal for New Publish users

---

package.json
packages/profile-sidebar/components/ProfileListItem/index.jsx
packages/profile-sidebar/components/ProfileSearch/index.jsx
packages/profile-sidebar/components/ProfileSearch/styles.css
packages/shared-components/ConfirmModal/index.jsx
yarn.lock

When using the Avatar component, when the image is broken the current approach to handle these scenarios (a mask) isn't always working resulting in something like this:
This PR adds a prop to send a `fallbackUrl` in case the image fails, and returning something like this instead:
I also decided to replace the `ProfileBadge` component to use `Avatar` instead and fix the same bug for the sidebar profile images.

Adding a fallback url to sidebar avatars

---

packages/cta-banner/components/BillingUpgradeCTABanner/index.jsx
packages/cta-banner/components/BillingUpgradeCTABanner/story.jsx
packages/cta-banner/index.js
packages/cta-banner/reducer.js
packages/modals/middleware.js
packages/modals/middleware.test.js
packages/store/reducers.js

As described in the title: a user should not see the Business Trial Modal or Billing CTA unless they have at least one social account connected.

[PUB-1467] Show Business Trial Modal and Billing CTA after social account is connected

---

packages/modals/middleware.js

As stated above, this PR makes it so the IG first comment modal is not shown until after the user has connected a social account. 

[PUB-1487] Do not show IG first comment modal until social account is connected

---

packages/queue/components/QueueItems/index.jsx
packages/queue/components/QueuedPosts/index.jsx
packages/queue/components/QueuedPosts/story.jsx

Team members should be seeing different Calendar views on the Queue.
Right now the ability to switch the Queue to Day, Week and Month view is only available to Pro users and up. However, team members in a team social account should be able to see the option too, as they are equivalent to business users.
[PUB-1493](https://buffer.atlassian.net/browse/PUB-1493)

[PUB-1493] Team members should be seeing different Calendar views on the Queue

---

packages/profile-sidebar/components/ProfileSidebar/index.jsx

**What?** Change Profile Sidebar height.
**Why?** When the list of profiles in the sidebar exceeds the space available the "Manage Social Accounts" button is pushed out of view.
[PUB-1478](https://buffer.atlassian.net/browse/PUB-1478)

[PUB-1478] Fix sidebar height to display bottom buttons

---

packages/app-shell/components/AppShell/index.jsx
packages/app-shell/index.js
packages/app-shell/reducer.js
packages/server/formatters/src/getURL.js

**What?** Add Users menu item to the AppShell, redirecting to the Users section in Org Admin.
**Why** Paid users need a way to easily access the Users section in Org Admin.
[PUB-1504](https://buffer.atlassian.net/browse/PUB-1504)
Depends on the deployment of this PR in buffer-web: https://github.com/bufferapp/buffer-web/pull/16188, which adds a new route to access manage/team-members directly.

[PUB-1504] Add Users menu to Appshell

---

packages/app-shell/components/AppShell/index.jsx

Change menu order so that menu items redirecting to Org Admin (like `Team`) are displayed immediately after the `Account` item.

Place org Admin menu items before NP in AppShell

---

packages/profile-sidebar/components/ProfileSidebar/index.jsx
packages/web/components/App/index.jsx

**What?** Change app container height to percentage instead of vh.
**Why?** With the new AppShell, the app content no longer fills the entire view. This will solve the problem of users with trial banners not seeing the sidebar buttons.
[PUB-1478](https://buffer.atlassian.net/browse/PUB-1478)

[PUB-1478]Change vh height to percentage

---

packages/composer-popover/package.json
yarn.lock

Updating composer version to the latest one (fixes bug with first comment section closing up).
Prevents first comment section to close up when clicking on toggle or comment click.
Related task -> [PUB-1451](https://buffer.atlassian.net/browse/PUB-1451)
N/A …

Updating composer version to the latest one

---

packages/thirdParty/middleware.js
packages/thirdParty/middleware.test.js

Adding a check to the third party middleware to ensure we don't collect data for Fullstory from free users. 
This change is required because Fullstory quota is limited, so we want to only collect data from paid user interactions.
JIRA card: https://buffer.atlassian.net/browse/PUB-1496?atlOrigin=eyJpIjoiYWQ5ZWNkMzYzNTA0NGU2OGIwZThlNDIzNTY3ZDVhMjkiLCJwIjoiaiJ9
-   [ ] I have tested my changes/additions in the latest Chrome, Firefox, and …

[PUB-1496] Exclude free users in Fullstory data collection

---

packages/shared-components/PostFooter/index.jsx

This change makes it so Free users can see a comment icon in their sent posts and queued posts which have a comment, even though the feature is no longer available to them.
This change is required because at the moment, Free users who had a Pro and up status in the past, cannot visually determine if their post was sent with a comment. 
https://buffer.atlassian.net/browse/PUB-1439?atlOrigin=eyJpIjoiMzZlN2JkNGE5Mzc2NGIwNGE5ZGVkZTU1ODZiMzdjNWQiLCJwIjoiaiJ9
-   [ ] Be able to see the first comment for a post already scheduled
-   [ ] See first comment for posts already sent
-   [ ] Be able to remove the first comment from an existing post
-   [ ] Not be able to re-enable the first comment for a post after they have removed it
-   [ ] Still send a post out with the first comment if it already …

[PUB-1439] IG First Comment changes for Free users

---

package.json

Using MUSL instead of glibc for grpc binary

Using musl instead of glibc for grpc binary

---

packages/composer/composer/components/DateTimeSlotPicker.jsx
packages/composer/composer/components/SlotPicker.jsx

Set the default time as "Select a slot" on switch from schedule to slo
In the composer, when switching from custom schedule to slot schedule, the time doesn't update in the composer's footer, [JIRA Related task](https://buffer.atlassian.net/browse/PUB-1369) …

[PUB-1369] Set the default time as "Select a slot" on switch from schedule to slot

---

packages/queue/middleware.js
packages/queue/middleware.test.js
packages/server/rpc/index.js
packages/server/rpc/swapPosts/index.js

Adding missing call in the middleware to save the swapped posts in the backend.
When drag and swapping posts, it's not being saved in the backend, so I included the rpc call to the backend.
To visit the URL of the staging deployment, please click "Show all checks" at the bottom of …

[PUB-1456] Adds missing call in the middleware to save the swapped posts

---

packages/notifications-provider/utils/notifications.json

Add trial extension notifications to notifications.json.
When NP users click on https://buffer.com/billing/renew-trial and renew their trial, they are redirected to NP with 3 parameters to show a success or error message. This PR allows to display those messages.
Related PR: https://github.com/bufferapp/buffer-web/pull/16223
Task: [PUB-1345](https://buffer.atlassian.net/browse/PUB-1345)
-   [X] I have tested different user stories. 
-   [X] I have identified similar or related features and tested they are still working.
-   [X] I have tested my changes/additions in the …

[PUB-1345] Add notifications for trial extension

---

packages/profile-page/components/ProfilePage/index.jsx
packages/profile-page/index.js
packages/profile-sidebar/index.js
packages/store/index.js
packages/tabs/components/TabNavigation/index.jsx
packages/tabs/index.js
packages/tabs/middleware.js
packages/tabs/reducer.js
packages/tabs/utils/index.js

Currently, we only have a validation for a user to be able to access a tab, in the Tab itself, and not in the Tab Content, which leads to certain issues, for example, if the user changes a profile, is capable of seeing a "new" set of valid tabs, but still see the content even if it's invalid (examples of this behavior are grid and past reminders tabs)
**Example Gif**
With these changes, we are validating both the Tab and the Content in a single file, which will make it easier for us in the future if we decide to add a new tab.
When a user has an Instagram profile selected and is wether in Past Reminders or Grid tab, when switching profile to a non-instagram account they should see the queue by default instead.
-   [ ] …

[PUB-1402] Making the queue the default view if it's not a valid tab

---

packages/notifications-provider/utils/notifications.json

Tweak copy of trial extension error notifications.
The goal is to standardize error messages
[PUB-1345](https://buffer.atlassian.net/browse/PUB-1345)
-   [X] I have tested different user stories. 
-   [X] I have identified similar or related features and tested they are still working.
-   [X] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [X] I have commented my code, particularly in hard-to-understand areas. …

[PUB-1345] Tweak trial extension notifications

---

packages/composer/composer/entities/Draft.js
packages/composer/composer/lib/validation/HashtagCounter.js
packages/composer/composer/tests/lib/validation/HashtagCounter.test.js
packages/composer/package.json
yarn.lock

Fix https://buffer.atlassian.net/browse/PUB-374 by using an external package to count the hashtags in the comment and caption of a draft in the composer.
http://hi.buffer.com/b96d95d013bf
To visit the URL of the staging deployment, please click "Show all checks" at the bottom of …

Fix issue: If there isn't a space between two hashtags, Buffer doesn't count them properly.

---

packages/preferences/index.js

Fix "Back to Dashboard" button route in Preferences when user has no profiles. In that case, instead of being redirected to a profile, gets redirected to the homepage.
With the new AppShell component, every user has access to the Preferences page. When users without any social account connected tried to click on "Back to Dashboard" they would get an error.
[PUB-1615](https://buffer.atlassian.net/browse/PUB-1615)
-   [x] I have tested my …

[PUB-1615] Fix "Back to Dashboard" button route in Preferences when user has no profiles

---

packages/shared-components/PostStats/index.jsx

Replace "Repins" by "Shares" in our Pinterest posts stats.
Pinterest requested us to make the change:
https://buffer.slack.com/archives/C151RRDL1/p1561735236056800
To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and click "details" …

Rename Repins to Shares in Pinterest stats

---

packages/modals/middleware.js
packages/modals/middleware.test.js

Second attempt at fixing https://buffer.atlassian.net/browse/PUB-1607 by hiding the modal if the AppCues tour starts later. …

Added new case when we should hide IG direct posting modal

---

packages/composer/composer/components/AppStateless.jsx
packages/composer/composer/components/Composer.jsx
packages/composer/composer/components/ComposerSection.jsx
packages/composer/composer/stores/AppStore.js
packages/composer/composer/utils/DataImportUtils.js

Remove ig first comment feature flip condition from composer. It's no longer needed now that free users can see toggle.  …

Remove firstComment flip condition from composer

---

packages/server/parsers/src/profileParser.js

Add hasOrganizationMembers prop to profile parser
We need the `hasOrganizationMembers` prop to check if a locked profile belongs to a team account.
[PUB-1390](https://buffer.atlassian.net/browse/PUB-1390)
buffer-web PR: https://github.com/bufferapp/buffer-web/pull/16306/
To visit …

[PUB-1390] Add hasOrganizationMembers prop to profile parser

---

packages/profile-sidebar/reducer.js
packages/profile-sidebar/reducer.test.js

Prevent users from unlocking blocked team accounts by dragging them.
If a profile is locked and the user is not its owner (it means the owner downgraded the plan), by dragging the profile it will not get unlocked. These types of profiles will never be able to be moved to the top of unlocked profiles, because we have a profile order in the sidebar: first unlocked, then locked profiles.
[PUB-1390](https://buffer.atlassian.net/browse/PUB-1390) …

[PUB-1390] Change logic drag locked team profiles

---

packages/composer-popover/components/ComposerWrapper/index.jsx
packages/composer/composer/components/App.jsx
packages/composer/composer/components/AppStateless.jsx
packages/composer/composer/components/UpdateSaver.jsx
packages/composer/composer/stores/AppStore.js
packages/composer/composer/stores/ComposerStore.js
packages/composer/interfaces/buffer-publish.jsx
packages/past-reminders/reducer.js
packages/sent/reducer.js

Fixing scheduled_at time when sharing a post again, since it's messing the posts order on clicking Share Again.
[[PUB-1482](https://buffer.atlassian.net/browse/PUB-1482)] On Sent posts tab or Past Reminders, when the user clicks on "Share Again", the post immediately drops to the bottom of the post list.
-   [x] I have commented my code, particularly in …

[PUB-1482] Fixing sent posts order on Share Again

---

packages/tabs/components/TabNavigation/story.jsx
packages/tabs/index.js
packages/tabs/index.test.js

Hide Analytics "Overview" tab for LinkedIn and Pinterest profiles, as we don't support their analytics.
Users are seeing the Overview tab for LinkedIn when coming from Classic dashboard. They believe this is the same as the Analysis tab they previously could access and are wanting to see their Data.
[PUB-1635](https://buffer.atlassian.net/browse/PUB-1635)
- …

[PUB-1635] Hide analytics overview tab if profile is linkedin or pinterest

---

helm/buffer-publish.dev.yaml
helm/buffer-publish.yaml
packages/server/lib/bugsnag.js

Fix stage set in Bugsnag by adding a new env. variable.
This is required because we were setting always staging as the env in production.

Fix Bugsnag integration environment

---

packages/server/rpc/analytics/posts/index.js
packages/server/rpc/analytics/posts/index.test.js
packages/server/rpc/analytics/postsAnalyzeApi/index.js
packages/server/rpc/analytics/postsAnalyzeApi/index.test.js
packages/server/rpc/analytics/utils/postParser.js

This updates Analyze `rpc/posts` so that it uses the new endpoint for Facebook posts.
This fixes https://buffer.atlassian.net/browse/PUB-1673 and missing metrics in the posts
To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and …

fix Analyze Facebook posts

---

packages/thirdParty/middleware.js

This change is specifically being made for Appcues tours for new business trialists. We want to hide the Beacon as to not confuse folx regarding their next steps.
https://buffer.atlassian.net/browse/PUB-1653
To visit the URL of the staging deployment, please click "Show all checks" …

[PUB-1653] Hide HelpScout Beacon during Appcues tour

---

packages/composer/composer/stores/ComposerStore.js

[PUB-1660](https://buffer.atlassian.net/browse/PUB-1660) - Adding check for images existence before running updateUploadedImageDimensions
If image doesn't exist because a user has deleted it before it completes uploading, or a use switches to another social network, we dont want it to throw an error anymore when setting the width and height as the image is no longer there …

Adding check for images existence before running updateUploadedImageDimensions

---

packages/server/rpc/sentPosts/index.js

Fix https://buffer.atlassian.net/browse/PUB-1662.
Since there's a lot of indirection on where the page param comes from, I thought it's easier and more effective to be more defensive about this value so if we have something different than a number we set it to 1.

Avoid sending something different than a number as a page for pagination

---

packages/profile-sidebar/middleware.js

Remove initialLoading case from the appSidebar
Sometimes, users with profiles are redirected first to `/new-connection-business-trialists` or `/new-connection` for a bit, and then they are redirected to their queue. That means that at the time the `(!isPreferencePage && profiles.length === 0)` condition is first checked, the profiles request response hasn't happened yet. We believe making sure this code only runs in the case `profiles_${dataFetchActionTypes.FETCH_SUCCESS}` will do the trigger.
- …

Remove initial loading case from profile sidebar

---

packages/server/index.js
packages/thirdParty/middleware.js
packages/thirdParty/reducer.js

The previous user id that was being used to identify the user was actually a session foreign key, not the user's actual user id. 
This change is required so that we can continue doing Qualaroo surveys/research in New Publish. …

Fix for incorrect userId being used in Qualaroo script

---

packages/app-shell/components/AppShell/index.jsx
packages/composer/composer/action-creators/AppActionCreators.js
packages/tabs/components/TabNavigation/index.jsx

Reverting PRO trial starts back to be direct upgrades.
Related JIRA task: [PUB-1732](https://buffer.atlassian.net/browse/PUB-1732)
**App header menu CTA button**
**Queue limit in Composer**
**App shell menu button** …

[PUB-1732] Reverting pro trials starts to direct pro upgrades

---

packages/composer/composer/components/Composer.jsx

Displaying first comment section only for Instagram accounts.
**JIRA card:** [PUB-1614](https://buffer.atlassian.net/browse/PUB-1614)
When a user has Instagram and other social profiles selected in the composer, and switches from customizing an Instagram post with a first comment to another social profile, the first comment toggle persists. Since first comment is an Instagram-only feature, we should hide it when a user is customizing a post for other profiles. 
-   [ ] I have performed a …

[PUB-1614] Displaying first comment section only for Instagram accounts

---

packages/server/rpc/analytics/posts/index.js

Fix posts breakdown table for Twitter profiles in the overview tab.
To make sure we are properly fetching twitter updates in the Overview tab.
This fixes a bug I accidentally introduced with #828, which was causing RPC to fetch posts on the wrong API address for twitter.
-   [X] I have identified similar or related features and tested they are still working.
To visit …

fix twitter posts rpc

---

packages/server/formatters/src/getURL.js
packages/server/formatters/test/getURL.test.js
packages/server/rpc/startTrial/index.js
packages/server/rpc/startTrial/test.js

There are unknown ctas coming through on mixpanel from tracking. I'm temporarily adding these test ctas to rule out if the unknown ctas are coming from new publish. Will monitor over next two days and will then revert back to the original code. …

Temp adding test ctas for null values

---

packages/hashtag-group-manager/middleware.js
packages/hashtag-group-manager/reducer.js
packages/server/rpc/getHashtagGroups/index.js

Removing unnecessary endpoint call after hashtag creation, changed the rpc from hashtagGroup to getHashtagGroup, so it's easier to understand.
We are calling get hashtag groups once a new group is created, which is unnecessary and is causing a delay in the UI.
To visit the URL of …

[PUB-1485] Removing unnecessary endpoint call after hashtag creation

---

packages/composer/composer/components/css/LocationComposerBar.css

Giving the location composer bar autocompleter a fixed width

Giving the location composer bar autocompleter a fixed width

---

packages/close-composer-confirmation-modal/components/CloseComposerConfirmationModal/index.jsx
packages/close-composer-confirmation-modal/components/CloseComposerConfirmationModal/story.jsx
packages/close-composer-confirmation-modal/components/CloseComposerConfirmationModal/style.js
packages/close-composer-confirmation-modal/index.js
packages/close-composer-confirmation-modal/middleware.js
packages/close-composer-confirmation-modal/package.json
packages/close-composer-confirmation-modal/reducer.js
packages/composer-popover/index.js
packages/drafts/components/DraftList/index.jsx
packages/drafts/index.js
packages/i18n/translations/en-us.json
packages/modals/components/AppModals/index.jsx
packages/modals/package.json
packages/modals/reducer.js
packages/modals/reducer.test.js
packages/profile-sidebar/middleware.js
packages/queue/components/QueuedPosts/index.jsx
packages/queue/index.js
packages/store/index.js
packages/store/reducers.js

Creating a confirmation to make sure users don't lose progress when clicking outside of the composer.
Currently to edit a post already in your queue, you click the "Edit" button on that post and then make your changes in the Composer that pops up. If you click out of this composer at any time, you lose all your progress immediately and without warning. 
**Jira card:** [PUB-1601](https://buffer.atlassian.net/browse/PUB-1601)
-   [x] I have …

[PUB-1601] Composer close confirmation modal

---

packages/composer/composer/components/InstagramThumbnailSlider.jsx

Fixing Bugsnag issue: Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite.
Jira card [[PUB-1659]](https://buffer.atlassian.net/browse/PUB-1659) …

[PUB-1659] Fixing Bugsnag issue Failed to set the currentTime

---

packages/cta-banner/middleware.js

When users are on business trialists, and click the Upgrade button, are being able to see the upgrade to pro modal. …

Preventing business users to see the upgrade to pro modal.

---

packages/drafts/middleware.js
packages/drafts/middleware.test.js
packages/drafts/reducer.js
packages/profile-page/index.js
packages/server/rpc/draftPosts/index.js

Fixing the way we load drafts, awaiting approval and pending approval tabs.
We are currently experiencing a bug in which users can't load more drafts when reaching to the bottom of the page, the reason was the way we were fetching and displaying the drafts in our UI.
The solution was to load the drafts data on tab change, instead on profile change only, and also "reseting" the drafts state when this change takes place, so that we can see the actual content for the selected tab.
-   [ ] I have …

[PUB-1701] Draft tabs content loading

---

packages/story-group-composer/components/StoryGroupPopover/index.jsx
packages/story-group-composer/components/StoryGroupWrapper/index.jsx
packages/story-group-composer/components/StoryGroupWrapper/story.jsx
packages/story-group-composer/index.js
packages/story-group-composer/package.json

Add popover and storyGroup wrapper with two view modes. 
https://buffer.atlassian.net/browse/PUB-1907
- Added dummy text for where the SG composer components will go to get us started.
- I tried out using hook state, however we can go back to using `this.state` if there's any added complexity with hook state. 
- I'll leave a comment in the sg queue cards around adding the composer_close logic. 
-   [ ] I have tested my changes/additions in …

[PUB-1907] Add storygroup composer wrapper with popover

---

packages/close-composer-confirmation-modal/middleware.js
packages/stories/components/StoryGroups/index.jsx
packages/stories/index.js
packages/stories/reducer.js
packages/story-group-composer/index.js

Added remaining features for Stories Groups tab.
- Included StoryGroupPopover and close logic.
- Added reminder label.
**Reminder Label** …

[PUB-1905] Reminder label and closing composer logic

---

packages/server/rpc/createSetupIntent/index.js
packages/server/rpc/index.js
packages/server/rpc/switchPlan/index.js
packages/server/rpc/switchPlan/test.js

This is part of the PSD2 requirements for Strong Customer Authentication via Stripe payments. **It requires front end changes before it can be merged**
Changes to the RPC endpoints are included in this PR:
* new PRC method `createSetupIntent` to be called before the user can add/update the credit card
* update `switchPlan` RPC endpoint to use a payment method id instead of the card token used before
* JIRA: https://buffer.atlassian.net/browse/CORE-768
* General paper with context is [here](https://paper.dropbox.com/doc/CORE-642-PSD2-Technical-Breakdown--AjMKrvwtz3r4dRmB658IFsV9Ag-jUXdDkVIhFJRWPOALLAut)
-   [ ] I have tested …

CORE-768 stripe SCA required changes to RPC

---

packages/profile-sidebar/middleware.js
packages/store/index.js

Currently, profiles from api is getting fetched twice in new publish because a call gets triggered in the analyze profile-loader middleware. Removing the profile-loader middleware seems to fix it and analytics data seems to be coming in correctly.  …

Prevent Analyze 'profiles' api fetch from firing aswell as publish's

---

packages/close-composer-confirmation-modal/middleware.js
packages/stories/index.js
packages/story-group-composer/components/AddStoryFooter/index.jsx
packages/story-group-composer/components/Carousel/CarouselCardHover/style.js
packages/story-group-composer/components/Carousel/CarouselCardWrapper/index.jsx
packages/story-group-composer/components/StoryGroupPopover/index.jsx
packages/story-group-composer/components/StoryGroupWrapper/index.jsx
packages/story-group-composer/index.js
packages/story-group-composer/middleware.js
packages/story-group-composer/reducer.js
packages/story-group-composer/utils/AddStory.js
packages/story-group-composer/utils/Carousel.js

- Reset story group state on composer close
- Remove ... for on hover note string if under 20 characters
- Set `showDatePicker` locally instead of in redux
- Center align add note button
To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this …

Reset story group data on composer close and other small refactors

---

packages/shared-components/DiscontinuousProgressBar/index.jsx
packages/story-group-composer/components/AddStoryFooter/index.jsx
packages/story-group-composer/components/StoryGroupPopover/index.jsx
packages/story-group-composer/components/StoryGroupWrapper/index.jsx
packages/story-group-composer/index.js
packages/story-group-composer/reducer.js
packages/story-preview/components/EditNote/index.jsx
packages/story-preview/components/NoteWrapper/index.jsx
packages/story-preview/components/PreviewMedia/index.jsx
packages/story-preview/components/PreviewPopover/index.jsx
packages/story-preview/components/ViewNote/index.jsx

- Open Preview in Story Composer
**Extras:**
- Change Proptypes validation for order (it's type number now instead of string)
- Add unique key to Discontinuous Progress Bar array
[PUB-1920](https://buffer.atlassian.net/browse/PUB-1920)
Next PR: disable Preview button when resources are still loading or no stories.
-   [x] I have commented my code, …

[PUB-1920] Open Preview in Story Composer

---

packages/shared-components/Story/index.jsx
packages/story-group-composer/components/Carousel/CardItem/index.jsx
packages/story-group-composer/components/Carousel/CardItem/styles.jsx

Displaying play icon when media type is a video in the queue and the composer.
With the changes in the images positioning, the PlayIcon wasn't being displayed, it was below the image, this PR fixes that.
Also, we didn't have the PlayIcon in the composer. …

Displaying play icon when media type is a video

---

.storybook/config.js

Add regex to exclude analytics node_modules from Storybook.
We were excluding `root/node_modules` from Storybook. However, we were only excluding `root/packages/[somepackage]/node_modules` in the `config.js` file of `.storybookStoryshot` and not `.storybook`. What happened is that files `story.jsx` coming from analytics node_modules were being displayed in publish storybook. …

Add regex to exclude analytics node_modules from Storybook

---

packages/server/parsers/src/storyGroupParser.js
packages/story-group-composer/reducer.js
packages/story-group-composer/utils/Carousel.js

When fetching the stories order from API is being handled as a string, which has been causing several problems for sorting the stories (on delete, drag and drop).
So I'm parsing the order to be an integer when fetching from the API to prevent adding parseInt everywhere.
To visit the …

Parsing stories order to int to prevent parseInt all over the code.

---

packages/plans/index.js
yarn.lock

The profile-sidebar actions were recently refactored which broke how we were importing them in the plans page.  …

Replace sidebar actions import as not default

---

packages/UploadZone/utils/Uploader.js
packages/UploadZone/utils/WebSocket.js
packages/composer/composer/action-creators/AppActionCreators.js
packages/composer/composer/components/ComposerSection.jsx
packages/queue/components/QueuedPosts/index.jsx

Providing support for multiple composers with different uploading / downloading behaviour.
Providing support for multiple composers with different uploading / downloading behaviour, as there was an issue when using the websocket library, that if you tried to configure new pusher events, it wouldn't set them up correctly because the pusher events would take the initial creator value, and so further events bound later would never re-bind new events to the composer.
This means that when uploading files in the composer, then switching to the stories composer, progress for uploading a video would never result in a new video asset being completed, or vice versa.
This changes that
-   [ ] I have added tests to cover my …

Supporting multiple uploaders

---

packages/pusher-sync/middleware.js
packages/pusher-sync/middleware.test.js
packages/stories/middleware.js
packages/stories/reducer.js

Dispatch `STORY_SENT` actionType when we receive a `sent_story_group` event from Pusher, that will update the stories queue.
[PUB-2016](https://buffer.atlassian.net/browse/PUB-2016)
To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR …

[PUB-2016] Add STORY_SENT action from Pusher event

---

packages/shared-components/CardHeader/index.jsx
packages/shared-components/Story/index.jsx
packages/story-group-composer/components/AddStoryFooter/index.jsx

- Fix issue with 24 hour format in datepicker not showing
- Remove creatorName temp in story cardHeader because we're not saving creator for storyGroup
https://paper.dropbox.com/doc/Instagram-Stories-Internal-Testing--Al2bqve31_6ZnPSwEWyvBvQfAg-pLbGPRYnOTqbiVUVGAZtC
To visit the URL …

Fix issue with 24 hour format in datepicker and remove creatorName in story header

---

packages/shared-components/CardHeader/index.jsx
packages/stories/components/StoryGroups/index.jsx
packages/story-group-composer/components/AddNote/index.jsx
packages/story-group-composer/components/AddStoryFooter/index.jsx
packages/story-group-composer/components/Carousel/CardItem/index.jsx
packages/story-group-composer/components/Carousel/CarouselCardHover/index.jsx
packages/story-group-composer/components/HeaderBar/index.jsx
packages/story-group-composer/components/NoteSection/index.jsx
packages/story-group-composer/components/StoryGroupPopover/index.jsx
packages/story-group-composer/components/StoryGroupWrapper/index.jsx
packages/story-group-composer/middleware.js
packages/story-group-composer/reducer.js
packages/story-group-composer/utils/commonPropTypes.js
packages/story-group-composer/utils/commonPropTypes.test.js

- Disable schedule button if user is editing story-group with a past reminder. (This case could happen if story-group share failed and still in queue). 
- Clean up prop-types in story-group composer …

Disable schedule button if story-group is a past reminder

---

packages/thirdParty/middleware.js

Added a check to make sure we don't record users on free plans in FullStory.
Change is required because if free users are recorded, our quota is filled up quickly.
To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and click "details" …

Add redundant check to ensure free users are not recorded in FullStory

---

packages/shared-components/Carousel/index.jsx
packages/story-group-composer/components/Carousel/CardItem/index.jsx
packages/story-group-composer/index.js
packages/story-group-composer/reducer.js

Handle batches of updates loading at the same time, and making the dom re-render and the ui non-interactive
I believe that this should fix the issues we are seeing around delayed interaction
We are batching updates to the ui, and processing as many as we can at the same time
To …

Handle batches of updates loading at the same time

---

packages/analytics-middleware/transformers/publish/story.js
packages/composer/composer/utils/TrackingUtils.js
packages/constants/index.js
packages/story-group-composer/index.js
packages/story-group-composer/middleware.js
packages/story-group-composer/reducer.js
packages/story-group-composer/utils/aspectRatioFinder.js
packages/story-group-composer/utils/aspectRatioFinder.test.js

PUB-2042 | Adding tracking for non conforming images (with aspect ratios not 9:16 or 16:9)
Adding tracking for segment.io for when composer uploads an image, to check whether users images are already in the expected aspect ratio or not. …

PUB-2042 | Adding tracking for non conforming images (with aspect ratios not 9:16 or 16:9)

---

packages/globalAccount/middleware.js
packages/globalAccount/middleware.test.js
packages/globalAccount/reducer.js
packages/server/rpc/globalAccount/index.js
packages/server/services/authenticationService.js

To be able to know if a given user on Publish is on the Analyze + Publish bundle experiment, we want to send `multiProductBundleName` with `analyze_publish_eid_19` to Segment.
To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and …

Track if a Publish user is on the Analyze + Publish bundle

---

packages/server/parsers/src/userParser.js
packages/temporary-banner/components/TemporaryDashboardBanner/index.jsx
packages/temporary-banner/index.js

This is a temporary and hacky solution to show a banner to the users who have LI profiles. 
Related ticket: https://buffer.atlassian.net/browse/PUB-1996.
I'll add a JIRA ticket to remove it in 2 weeks. …

Add LinkedIn banner for new permissions

---

packages/analytics-middleware/utils/CtaStrings.test.js
packages/constants/index.js
packages/cta-banner/index.test.js
packages/cta-banner/middleware.js
packages/cta-banner/middleware.test.js
packages/cta-banner/reducer.test.js
packages/modals/middleware.js
packages/modals/middleware.test.js
packages/plans/index.js
packages/server/rpc/switchPlan/index.js
packages/server/rpc/switchPlan/test.js
packages/stripe/middleware.js
packages/stripe/middleware.test.js
packages/switch-plan-modal/components/PlanCycleSelect/index.jsx
packages/switch-plan-modal/components/SwitchPlanModal/index.jsx
packages/switch-plan-modal/index.js
packages/switch-plan-modal/middleware.js
packages/switch-plan-modal/middleware.test.js
packages/switch-plan-modal/reducer.js
packages/switch-plan-modal/utils/tracking.js
packages/switch-plan-modal/utils/tracking.test.js

Reverts bufferapp/buffer-publish#1027
Remove the import of switch-modal tracking utils from the switchModal rpc method, to avoid having to copy the package through the server.
Apply the parsing logic to stripe middleware instead, which fetches the switchModal rpc method.

Revert "Revert "[PUB-2085] Open payment modal in Premium trialist banner CTA""

---

packages/modals/middleware.js
yarn.lock

https://buffer.atlassian.net/browse/PUB-2055
When composer closes on pusher event, also close the confirmation modal if it's open. 
I found a potential bug around how the composer closes on STORY_SENT pusher event. This could cause issues around data getting lost if a user was creating a story/post during a pusher event. This happens also with posts in the queue. Curious @MayaUribe whether this could be related to the issues with users losing state https://threads.com/34371642266
It didn't seem like a quick fix so I added a jira and tagged super & dianne to prioritize. 
https://buffer.atlassian.net/browse/PUB-2114 
-   [ ] I …

[PUB-2055] Remove close confirmation modal on pusher event

---

package.json
packages/server/package.json
yarn.lock

Updating moment-timezone to use the latest version from npm and updating to use the caret version number to support newer versions more automatically / systematically in future.
Had to run `yarn cache clean` to get this version to work with semantic versioning, this should be backwards compatible with previous changes.

Updating moment-timezone to latest version

---

packages/composer/composer/utils/WebAPIUtils.js

Temporarily change the fb tagging error message based on us trying to get back tagging permissions. 
https://buffer.slack.com/archives/C151RRDL1/p1571253132318200
Will want to revert changes once permissions is figured out.  …

Change fb page tagging error message temporarily

---

packages/composer-popover/components/ComposerWrapper/index.jsx

Removing scheduled_at times for sent posts, so that they can be rescheduled later.
https://buffer.atlassian.net/browse/PUB-1709 …

PUB-1709 | Adding fix for sent posts re-posting

---

packages/constants/index.js
packages/switch-plan-modal/utils/tracking.js

Adding premium solo plan upgrade and downgrade CTA
more context here: https://buffer.slack.com/archives/C151RRDL1/p1571700260049100
Looks like we missed adding the CTA for the premiun35 plan, this should fix the issue in live …

Adding premium solo plan upgrade and downgrade CTA

---

helm/buffer-publish.yaml

This PR should prevent all publish pods from being scheduled on the same node due to the low request. Then getting terminated because of the high usage and high limit.
It's intended to solve the kubelet issue when a node CPU is overloaded  …

make-cpu-request-limit-more-balanced

---

packages/profile-page/components/ProfilePage/index.jsx
packages/profile-page/index.js
packages/sent/components/SentPosts/index.jsx
packages/sent/index.js
packages/server/parsers/src/profileParser.js
packages/server/parsers/src/userParser.js
packages/shared-components/BannerAdvancedAnalytics/analyzeLogo.jsx
packages/shared-components/BannerAdvancedAnalytics/index.jsx
packages/shared-components/BannerAdvancedAnalytics/story.jsx
packages/shared-components/BannerAdvancedAnalytics/style.js
packages/shared-components/PostList/index.jsx
packages/shared-components/PostLists/index.jsx
packages/shared-components/index.js
packages/tabs/components/TabNavigation/index.jsx
packages/tabs/index.js
packages/tabs/utils/index.js

- Hide overview analytics tab if user has signed up after certain date (coming from API).
- This also shows a banner in the sent posts to promote Analyze.
https://buffer.atlassian.net/browse/PUB-2147 …

Hide advance analytics tab if user has signed up after today

---

packages/composer/composer/components/Composer.jsx
packages/composer/composer/components/MediaAttachmentThumbnail.jsx

- Allow tag option if more than one ig profile is selected and atleast one profile has direct scheduling enabled and image meets ig direct conditions. 
- Add spacing between tag thumbnail icon and text
https://buffer.atlassian.net/browse/PUB-2164 …

[PUB-2164] Display tag option if at least one ig profle has direct enabled

---

packages/composer-user-tags/components/TagInput/index.jsx
packages/composer-user-tags/components/TagInput/style.js
packages/i18n/translations/en-us.json

Allow user to cancel out of the max limit pop-up by adding a cancel button
https://buffer.atlassian.net/browse/PUB-2172
http://hi.buffer.com/4981e2b02238
Slightly refactored the max limit message, as it looked a bit funny with the message on two lines. …

[PUB-2172]Allow user to cancel out of the max limit pop-up

---

packages/story-group-composer/reducer.js

Bugsnag error is happening where cases of `processedErrors` is undefined
https://buffer.slack.com/archives/CEJMCLB37/p1572894531000700/
Not able to replicate, but adding an error handler to prevent crash
To visit the URL of the staging deployment, please click "Show all checks" at …

Add handler if processedErrors is undefined

---

packages/plans/components/PlanColumn/index.jsx
packages/plans/components/PlanColumnWithPremiumSolo/index.jsx

Users currently on a trial should be able to finish trial and pay on Payday page
JIRA card -> [PUB-2086](https://buffer.atlassian.net/browse/PUB-2086) …

[PUB-2086] Enabling button for current trial plan on payday page.

---

packages/server/parsers/src/profileParser.js
packages/server/rpc/getCounts/index.js
packages/server/rpc/getCounts/index.test.js
packages/server/rpc/index.js
packages/tabs/components/TabNavigation/index.jsx
packages/tabs/middleware.js
packages/tabs/middleware.test.js
packages/tabs/reducer.js
packages/tabs/reducer.test.js

- Get drafts count through a dedicated getCounts rpc method
- Make the counts request both when a profile is selected and a drafts pusher event occurs
- Hide counter from tabs while the request is happening (fetch start)
https://buffer.atlassian.net/browse/PUB-1869
Counts endpoint created here: https://github.com/bufferapp/buffer-web/pull/16679
-   [x] I …

[PUB-1869] Replace manual count by dedicated endpoint

---

packages/shared-components/BannerAdvancedAnalytics/index.jsx

To fix publish-analytics-posts-analyzeTrial-1 CTA
We are directly directing non Analyze users to https://account.buffer.com/analyze?cta=publish-analytics-posts-analyzeTrial-1 instead of https://analyze.buffer.com/?cta=publish-analytics-posts-analyzeTrial-1, to avoid a series of nested redirects that end up
removing the original CTA.
Here is the Slack convo https://buffer.slack.com/archives/C0DLE125Q/p1573594739255400
-   [x] I have tested my …

fix publish-analytics-posts-analyzeTrial-1 CTA

---

packages/bootstrap/middleware.js
packages/bootstrap/package.json
packages/server/index.html
packages/server/index.js
packages/store/index.js

Boostrapping the user on the initial request (in the backend)
This should allow us to speed up perceived loading time, as the menu will be ready immediately for users as the user "should" always be present.
This version prevents FullStory from being loaded for free users as per https://buffer.atlassian.net/browse/PUB-2207
More streamlining to come around external script loading optimizations, but fullstory is the start of this
-   [ ] I have …

Stop free user tracking fullstory

---

packages/analytics-middleware/middleware.js
packages/analytics-middleware/middleware.test.js
packages/analytics-middleware/readme.md
packages/constants/index.js
packages/drafts/middleware.js
packages/drafts/middleware.test.js
packages/grid/index.js
packages/grid/middleware.js
packages/grid/middleware.test.js
packages/server/index.js
packages/stories/index.js
packages/story-group-composer/index.js
packages/story-group-composer/middleware.js
packages/story-group-composer/utils/Tracking.js

- Add clientName to analytics-middleware package. 
- Remove references of clientName in tracking data
- Update analytics-middleware readme to include clientName (will notify publish team once changes are merged)
After chatting with Julian, it seems the `clientName` property will be present on all tracking events going forward. This refactor means we won't need to explicitly pass it each time. 
https://buffer.slack.com/archives/C151RRDL1/p1573766865276800
-   [x] I have performed a self-review of …

Refactor client name to analytics-middleware for tracking

---

packages/server/index.html

Moving scripts out of the document head to prevent them from blocking rendering and loading

Moving scripts out of the document head to prevent them from blocking rendering and loading

---

packages/past-reminders/components/PastRemindersWrapper/index.jsx
packages/past-reminders/middleware.js
packages/sent/components/SentPosts/index.jsx
packages/sent/components/SentPosts/story.jsx
packages/sent/index.js
packages/sent/middleware.js
packages/sent/middleware.test.js
packages/sent/reducer.js

- Fetch sentPosts inside the `SentPosts` component, instead of users' SELECT_PROFILE.
- Fetch pastReminders inside the `PastRemindersWrapper` component, instead of users' SELECT_PROFILE.
Used the effect hook instead of componentDidMount.
This change allows us to only fetch data when we need it.
[PUB-2193](https://buffer.atlassian.net/browse/PUB-2193)
- …

[PUB-2193] Change sentPosts fetch

---

.gitignore
Dockerfile
babel.config.js
package.json
packages/server/index.html
packages/server/index.js
packages/server/webpack.config.common.js
packages/server/webpack.config.prod.js
pre-build.sh
yarn.lock

* Fixed code splitting that broke in https://github.com/bufferapp/buffer-publish/commit/a90f9216acf7eef0bef8f2c4d6cb8036bca9d679
* Fix hashing of CSS so that it's not linked to changes in JS
* Split out the runtime/manifest chunk and inline that into the HTML (production only) -- this should prevent hashes changing in the main bundles. [[ref]](https://survivejs.com/webpack/optimizing/separating-manifest/)
* Added new `ManifestPlugin` which outputs a JSON file that we're using now instead of `staticAssets.json` since it is keyed by non-hashed filenames. (cc @msanroman in case that might be helpful for Analzye, it simplified some of the server code.) [[ref]](https://github.com/bufferapp/buffer-publish/compare/task/code-splitting-improvements?expand=1#diff-068e7c6acbb89d55e9fa2192f813a6d8R66- …

Fixes and improvements to code splitting

---

package.json
yarn.lock

Updating @bufferapp/ui version to "5.18.1-beta.bd7ed5d" for Tooltip fix not being displayed.

Update ui version

---

packages/switch-plan-modal/reducer.js

In the switch plan modal, the only Pro option for Awesome users who are receiving the promotional discount will be the monthly plan. To reflect this, we're changing the default behavior for the switch plan modal for these users so that the monthly option is auto selected, instead of the yearly payment option.
https://buffer.atlassian.net/browse/PUB-2249
- …

[PUB-2249] Auto select monthly option for Awesome promo users

---

packages/app-switcher/reducer.js
packages/app-switcher/reducer.test.js

Remove outdated app switcher modal.
Change is required so that Awesome customers who visit the Payday page are unencumbered by any other CTAs.
https://buffer.atlassian.net/browse/PUB-2275
To visit the URL of the staging deployment, please click "Show all checks" at the bottom of …

[PUB-2275] Remove app switcher modal

---

packages/analytics/components/AnalyticsList/index.jsx

Fix the way I was fetching with hooks after lazy-loading the analyze components. Should fix the dropdown not working after switching profiles.
I think I just needed to pass the profile in as a dependency of the effect so that it updated correctly. …

[PUB-2267] Fix analyze date picker

---

packages/constants/index.js
packages/i18n/translations/en-us.json
packages/modals/reducer.js
packages/modals/reducer.test.js
packages/queue/components/QueuedPosts/index.jsx
packages/queue/index.js
packages/server/formatters/src/getURL.js
packages/set-reminders-modal/components/SetRemindersModal/index.jsx
packages/set-reminders-modal/components/SetRemindersModal/story.jsx
packages/set-reminders-modal/index.js
packages/set-reminders-modal/index.test.js
packages/set-reminders-modal/package.json

- Add Set Reminders Modal;
- Add modal actions to show and hide;
- Add CTA actions:
`publish-app-setRemindersModal-setReminders-1` and `publish-queue-remindersBanner-setReminders-1`.
- Create `getRemindersURL` in formatters, with a temporary link (no problem, it's not being used by users)
- Set `onSetRemindersClick` action, in both the RemindersModal and the Queue Banner.
[PUB-2263](https://buffer.atlassian.net/browse/PUB-2263)
-   [ ] I …

[PUB-2263] Add set reminders modal

---

packages/server/rpc/getStoryGroups/index.js

Change the stories queue limit to 100. The default is 20, so we need to be explicit and send 100 as count. 
https://buffer.atlassian.net/browse/PUB-2277 …

[PUB-2277] Increase stories queue count to 100

---

packages/grid/components/CustomLinks/index.jsx
packages/grid/components/GridPosts/index.jsx
packages/grid/index.js
packages/grid/middleware.js
packages/grid/reducer.js
packages/server/rpc/index.js
packages/server/rpc/shopGrid/customLinks/update/single.js

Add ability to isolate link editing, and call the single update endpoint

Add ability to isolate link editing, and call the single update endpoint

---

package.json
packages/grid/components/CustomLinks/EditingLinkForm/index.jsx
packages/grid/components/CustomLinks/styles.js
yarn.lock

- Add maxLength for shopgrid link text input. 
- Change the width to input so that it's not wider than the max text. 
https://buffer.atlassian.net/browse/PUB-2305
Waiting on UI update https://github.com/bufferapp/ui/pull/168
I've noticed we've used maxLength a few times in Publish with the Input component. I don't think this was ever working though 
-   [ ] …

[PUB-2305] Add maxLength and set width to shopgrid link input

---

packages/constants/index.js
packages/i18n/translations/en-us.json
packages/stories/components/StepCard/index.jsx
packages/stories/components/StepCard/story.jsx
packages/stories/components/StoriesExplanation/index.jsx
packages/stories/components/StoriesExplanation/story.jsx
packages/stories/components/StoryGroups/index.jsx
packages/stories/components/StoryGroups/story.jsx
packages/stories/index.js

- Add reminders prompt for Stories tab, with explanation of how it works when users don't have push notifications set
[PUB-2264](https://buffer.atlassian.net/browse/PUB-2264)
To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and …

[PUB-2264] Add Stories Explanation when no reminders

---

packages/shared-components/ColorPicker/components/ColorSwatches/index.jsx
packages/shared-components/ColorPicker/styles.js

Change color picker elements to buttons to allow user to tab through and select color with keyboard.
I decided to change the elements to buttons as submit works a bit easier on keyboard. (If we kept div, we'd have to add a keyboard listener to submit on enter). 
To visit the URL of …

Change color picker divs to buttons to make more accessible

---

packages/constants/index.js
packages/queue/components/QueueItems/index.jsx
packages/queue/components/QueuedPosts/index.jsx
packages/queue/components/RemindersBanner/index.jsx
packages/queue/index.js
packages/server/formatters/src/getURL.js
packages/server/parsers/src/profileParser.js
packages/shared-components/ImagePost/index.jsx
packages/shared-components/LinkPost/index.jsx
packages/shared-components/MultipleImagesPost/index.jsx
packages/shared-components/Post/index.jsx
packages/shared-components/PostErrorBanner/index.jsx
packages/shared-components/TextPost/index.jsx
packages/shared-components/VideoPost/index.jsx
packages/stories/components/StoryGroups/index.jsx
packages/stories/index.js

- Add Reminders Warning at the top of an IG reminder post, if the profile has no push notifications enabled.
- Add cta `publish-queue-remindersPost-setReminders-1`, related to the click on "Set Up Reminders" in the Post.
- Add `hasRemindersFlip` feature flip to the Reminders flow.
- Complete getRemindersURL with final url and add a nextUrl param so the user can be redirected again to the same tab in the dashboard.
[PUB-2255](https://buffer.atlassian.net/browse/PUB-2255)
I'm not a fan of the prop drilling we have happening in the posts (Post, ImagePost, TextPost, ...) but it requires some refactoring and thinking.
-   [ ] I have …

[PUB-2255] Add post reminder warning

---

packages/analytics/index.js
packages/analytics/middleware.js
packages/server/rpc/analytics/analyticsStartDate/index.js
packages/server/rpc/analytics/posts/index.js
packages/server/rpc/index.js

In some browsers / systems the analyze export is failing (See https://buffer.atlassian.net/browse/PUB-2323). I was able to reproduce the issue in Safari and then debug and go deeper to learn that the profiles weren't being populated properly in the Analyze store. This had something do with how I was trying to 'hide' the `profiles_FETCH_SUCCESS` event from the rest of Publish when it's triggered by the lazy-loading of the analyze page (otherwise going to Overview would always re-trigger all the modals, etc.)
After fixing the logic it appears that the exports are now working again.
- …

[PUB-2323] Fix Analytics Overview CSV export + clean up

---

packages/grid/components/CustomLinks/LinksHeader/index.jsx
packages/grid/components/CustomLinks/index.jsx
packages/shared-components/ColorPicker/components/ColorSelectorPopup/index.jsx

Simplifying call stack for colour picker and fixing return key validation for link color
I tried a number of methods to make the colour picker work, and in the end I realised that the validation was "always" failing, and it turned out we were validating for the presence of the # symbol, so I've edited the function to add a # at the start of the string, so the validation now works.
This has allowed me to simplify how we validate, and when we press return, we just check for the presence of a valid field in the UI, and this means I can blur / not based on validity of the field.
I think it would be good to support "transparent" buttons somehow too... then in dark mode, vs light mode, we can support the display more appropriately for each scenario, but that is definitely a different problem. …

Simplifying call stack for colour picker and fixing return key validation for link color

---

packages/app-shell/index.js
packages/app-shell/reducer.js

Change data source for hideAppShell, to get the state from onboarding instead of the user request.
AppShell was not displayed for the first time for business trialists. During the Onboarding of a Business Trialist, when a user skips the step, we store a message in the user - `user_saw_onboarding_page`. The AppShell is listening to user_sucess to check if the message exists, but the user request was made prior to us storing the message.
It's safer to get the info from the onboarding state - it sets the value manually when the user skips the step, and the remaining times it gets it from the user request.
https://buffer.atlassian.net/browse/PUB-2387
-   [x] All new and …

[PUB-2387] Change data source for hideAppShell

---

packages/drafts/components/DraftList/index.jsx
packages/drafts/index.js
packages/i18n/translations/en-us.json
packages/profiles-disconnected-banner/components/ProfilesDisconnectedBanner/index.jsx
packages/profiles-disconnected-banner/components/ProfilesDisconnectedBanner/story.jsx
packages/profiles-disconnected-banner/index.js
packages/profiles-disconnected-banner/index.test.jsx
packages/profiles-disconnected-banner/package.json
packages/profiles-disconnected-modal/components/ProfilesDisconnectedModal/index.jsx
packages/profiles-disconnected-modal/index.js
packages/profiles-disconnected-modal/reducer.js
packages/profiles-disconnected-modal/reducer.test.js
packages/queue/components/QueuedPosts/index.jsx
packages/queue/index.js
packages/shared-components/ErrorBanner/index.jsx
packages/shared-components/ErrorBanner/story.jsx
packages/shared-components/index.js
yarn.lock

- Create `<ErrorBanner>` in `shared-components`, so it can be reused.
- Create `<ProfilesDisconnectedBanner>` and dedicated package.
- Add Profiles Disconnected Banner to Reconnect to ~~all tabs (Analytics, Drafts, General Settings, Grid, Past Reminders, Queue, Sent Posts and Stories)~~ the Queue, while we decide what do to in other tabs
[PUB-2385](https://buffer.atlassian.net/browse/PUB-2385)
-   [ ] I have tested my changes/additions in …

[PUB-2385] Add Profiles Disconnected Banner

---

packages/switch-plan-modal/components/SwitchPlanModal/index.jsx
packages/trial-complete-modal/middleware.js

https://buffer.atlassian.net/browse/PUB-2396
This PR shows the upgrade/switch plan modal instead of taking the Pro trialists to the billing page (since it's promoting B4B and not the Pro upgrade.) …

[PUB-2396] Show upgrade / switch plan  modal at end of pro trial

---

packages/server/parsers/src/userParser.js

Changes the user parser to parse Awesome users who are being migrated to the Pro plan as Pro users, so that they receive Pro features in NP.
[https://buffer.atlassian.net/browse/PUB-2345](https://buffer.atlassian.net/browse/PUB-2345) …

[PUB-2345] User parser treats Awesome migrating users as Pro

---

packages/app-shell/reducer.js

This change allows users who have the 'awesome_user_can_view_payday_page' feature flip access to the missing menu items, as long as they are not on the Awesome plan.
This change is required because Awesome users who upgrade their account are not able to access certain menu items, such as the 'Preferences' menu, blocking them from accessing several settings, including TFA settings.
-   [ ] I have tested my changes/additions in the latest …

[PUB-2474] Give users access to menu options

---

packages/server/parsers/src/userParser.js

Add check to userParser to ensure Awesome customers who are migrating to Pro can see all of New Publish's menu options.
[https://buffer.atlassian.net/browse/PUB-2474](https://buffer.atlassian.net/browse/PUB-2474) …

[PUB-2474] Menu items for migrated Awesome users

---

packages/server/package.json
packages/server/rpc/globalAccount/index.js
packages/server/services/authenticationService.js
yarn.lock

Rebased version of #1193 
When an admin impersonates a user, the session.global part of
the session remains pointing to the impersonating user
This change loads the global account for the impersonated user instead.
This is being fixed as part of an issue with Mixpanel tracking
The getAccount RPC enpoint will now use the publishId to fetch the user from the Core Authentication Service.
It also adds an `isImpersonation` property to the user, that can be useful to show a message to advocates while impersonating.
* change how we fetch the global account using the publish userId
* update `@bufferapp/session-manager` to use the new impersonation helpers
* add `.isImpersonating` to the returned value
-   [ ] I have added …

CORE-916 fix tracking during impersonation

---

packages/campaigns/components/CampaignsPage/index.jsx
packages/campaigns/components/CreateCampaign/index.jsx
packages/campaigns/index.js
packages/campaigns/middleware.js
packages/campaigns/reducer.js
packages/server/parsers/src/userParser.js
packages/server/rpc/campaigns/getMainOrganization/index.js
packages/server/rpc/index.js

When creating a new Campaign, it should be associated to one organization, this would mean, the user should be able to choose the organization and assign it to a Campaign.
These changes are to automatically fetch that organization_id from the user endpoint.
Jira tickets:
- PUB-2504
- PUB-2511
Related [PR](https://github.com/bufferapp/buffer-web/pull/16890) …

PUB-2511 | Fetching user's main organization, that will be valid for Campaigns V1

---

packages/server/index.html
packages/server/index.js
packages/server/parsers/src/userParser.js
packages/thirdParty/components/Loader/index.jsx
packages/thirdParty/components/RouteMonitor/index.jsx
packages/thirdParty/constants.js
packages/thirdParty/index.js
packages/thirdParty/middleware.js
packages/thirdParty/middleware.test.js
packages/thirdParty/reducer.js

Advocacy are moving our FAQ articles over to Zendesk. This is one of the last stages involved in removing our Help Scout integration. For this reason, we will no longer need the Help Scout Beacon widget in the publish dashboard. This PR removes all code associated with Beacon and Help Scout in Publish …

Remove Help Scout Beacon from Publish dashboard

---

packages/globalAccount/middleware.js
packages/globalAccount/middleware.test.js
packages/globalAccount/reducer.js
packages/server/rpc/globalAccount/index.js

To track `productSolutionName` for Publish sessions.
This replaces `multiProductBundleName` with `productSolutionName `, as required by [Product Solutions 2.0](https://paper.dropbox.com/doc/Product-Solutions-V2-technical-spec--AvCkobCYR6M5Z_DQ7lDkZXuLAg-EFKMXVgAPWJ6SMmJ6CL6Q).
-   [X] I have added tests to cover my changes.
-   [X] I have tested different user stories. 
-   [ …

add productSolutionName tracking  (AT-502)

---

packages/server/parsers/src/postParser.js

Fixing ui state for non errored posts being shown as errored
Users with previously errored posts are still seeing errors in the UI, even though the status has been cleared from errored to not. We need to reflect this in the UI state correctly …

Fixing ui state for non errored posts being shown as errored

---

package.json
packages/campaigns/components/CampaignForm/index.jsx
packages/campaigns/components/CampaignForm/story.jsx
packages/campaigns/components/ListCampaigns/EmptyState/index.jsx
packages/campaigns/components/ViewCampaign/EmptyState/index.jsx
yarn.lock

- Update bufferapp/ui to version 5.27.0, to get the new Link Component.
- Replace Campaign Link Buttons by Link Components.
https://buffer.atlassian.net/browse/PUB-2478
-   [x] I kept accessibility in mind by following the [a11y …

[PUB-2478] Upgrade ui version

---

packages/app-shell/components/AppShell/index.jsx

Update FAQ link under Help dropdown menu. Also removes Support option and renames FAQ to 'Help Center'. 
PUB-2568
To visit the …

[PUB-2568] Update FAQ link in dropdown

---

packages/campaigns/middleware.js
packages/server/parsers/src/campaignParser.js
packages/server/rpc/campaigns/getCampaign/index.js
packages/server/rpc/campaigns/getCampaign/index.test.js

Updating changes from endpoint:
- Changing param from `basic_items` to `full_items`
- Parsing full items response for update types
Jira Card -> PUB-2540
Related PR -> [API changes PR](https://github.com/bufferapp/buffer-web/pull/16939) …

PUB-2540  | RPC Parsing full items response for update types

---

packages/past-reminders/components/PastRemindersPosts/index.jsx
packages/past-reminders/index.js
packages/past-reminders/reducer.js
packages/queue/components/QueuedPosts/index.jsx
packages/queue/index.js
packages/queue/middleware.js
packages/queue/reducer.js

Refactor fetching the campaigns to happen only in the queue and past reminders
Related Jira Card PUB-2518 …

Refactor fetching the campaigns in the queue

---

packages/campaign/components/ViewCampaign/Header/index.jsx
packages/campaign/components/ViewCampaign/Header/story.jsx
packages/campaign/components/ViewCampaign/index.jsx
packages/campaign/components/ViewCampaign/story.jsx
packages/campaign/index.js
packages/campaign/middleware.js
packages/campaign/middleware.test.js
packages/campaign/reducer.js
packages/campaign/reducer.test.js
packages/campaigns-list/components/ListCampaigns/List/index.jsx
packages/campaigns-list/components/ListCampaigns/List/story.jsx
packages/campaigns-list/components/ListCampaigns/ListItem/index.jsx
packages/campaigns-list/components/ListCampaigns/ListItem/story.jsx
packages/campaigns-list/components/ListCampaigns/index.jsx
packages/campaigns-list/index.js

- Add tracking when a user clicks on on view analyze report in campaigns.
- Refactor `isTeamMemberUsingPublish` to `hideAnalyzeReport`
- In campaign view header, disable view report if dateRange is null.
- Display sent & scheduled in campaign view header even if value is 0.
https://buffer.atlassian.net/browse/PUB-2560
- Made some changes to campaign view header after working on a similar component with list campaigns. I was able to clarify a few things with Lauren, and we do want to show sent & scheduled even it's zero. 
- Date range is a better indicator on whether view report should be disabled. Even if a campaign has no posts, they may still have sent posts for the report. I confirmed with Maya that dateRange will be null if there have been 0 posts added to a campaign. 
-   [x] My code …

[PUB-2560] Add analyze report view tracking and small refactors

---

.gitignore
packages/UploadZone/components/UploadZone/index.jsx

If we don't do this, file drops may propagate up from Dropzone to `react-dnd` and throw errors in the console (see https://github.com/react-dnd/react-dnd/issues/457)
This was happening with the story groups composer when dropping a file on one of the cards. (Though the error wasn't crashing the app; it just added noise to our Bugsnag reporting.)

Fix `react-dnd` error by not propagating Dropzone drop

---

packages/app-pages/components/PagesWithSidebar/index.jsx
packages/campaigns-list/components/ListCampaigns/index.jsx

- Fix campaigns scrollable page.  
- Add padding to the loading container to center loading.
I noticed the queue had a height of `1px` and realized campaigns also needed that height for the scroll to work correctly. Honestly, it feels a bit hacky, and I tried to figure out a better refactor for the queue & campaigns. [It's a bit tricky](https://media.giphy.com/media/13FrpeVH09Zrb2/giphy.gif) and I wasn't able to figure it out yesterday afternoon. As this change fixes the issue, I left it as is. Could be a good one to revisit in the future though! :) 
https://buffer.atlassian.net/browse/PUB-2589
https://share.buffer.com/8LuJeZEx …

[PUB-2589] Fix campaigns scrollable page

---

packages/campaigns-list/components/ListCampaigns/EmptyState/index.jsx
packages/campaigns-list/components/ListCampaigns/List/index.jsx
packages/campaigns-list/components/ListCampaigns/List/story.jsx
packages/campaigns-list/components/ListCampaigns/ListItem/index.jsx
packages/campaigns-list/components/ListCampaigns/ListItem/story.jsx
packages/campaigns-list/components/ListCampaigns/ListItem/style.js
packages/routes/index.js

- Add a link to the campaign title in the campaign list. If clicked, redirect to the view campaign page.
- Remove references to `isEvenItem` (no longer being used)
Hey Ana, I added a getRoute method to routes. Is the campaignScheduled.routes property mainly for documentation? 
https://buffer.atlassian.net/browse/PUB-2609 …

[PUB-2609] Change campaign title to link in list item

---

packages/campaign/components/ViewCampaign/index.jsx
packages/campaign/components/ViewCampaign/story.jsx
packages/campaign/index.js
packages/campaign/middleware.js
packages/campaign/reducer.js
packages/composer-popover/components/ComposerWrapper/index.jsx
packages/composer/composer/utils/DataImportUtils.js
packages/composer/interfaces/buffer-publish.jsx
packages/story-group-composer/utils/AddStory.test.js

In Campaign View:
- On create post list all campaigns and auto-select the campaign
- On create post selects the first profile by default and schedules a new post.
- On edit post opens composer with the selected post (profile selected and post details)
JIRA card: PUB-2611
**Create post**
**Update post** …

PUB-2611  | Adding logic for composer within list campaigns view

---

packages/campaign-form/components/CampaignForm/index.jsx
packages/campaign-form/index.js
packages/campaigns-list/components/ListCampaigns/ListItem/style.js

- Check if user is in edit mode to decide whether to dispatch edit campaign action. This prevents campaigns getting overwritten.
- Fix campaign color position on scroll. 
https://buffer.atlassian.net/browse/PUB-2612 …

[PUB-2612] Check editMode prop when dispatching edit campaign action

---

packages/composer/composer/components/App.jsx
packages/composer/interfaces/buffer-publish.jsx

* See Slack thread: https://buffer.slack.com/archives/C0258B5CR/p1585691371180100
* The way I came to this fix was by an error that was showing locally (it is silenced in prod) about not calling setState in a render function. By using chrome debugger, I saw that calling `AppInitActionCreators.resetData();` in the `buffer-publish.jsx`'s ComposerWrapper we were basically doing that.
* To solve I moved the resetting of state inside the composer. In fact logic for that was already there, but it needed to look at a different prop to reset correctly. (This probably worked for buffer-web, when this composer code was used there.)
What confuses me is why this seemed to only show up now? 🤔 
-   [ ] I have added tests to cover …

Change way we reset state to prevent react rendering crash

---

packages/campaign/index.js
packages/campaign/middleware.js
packages/close-composer-confirmation-modal/middleware.js
packages/drafts/index.js
packages/modals/reducer.js
packages/modals/reducer.test.js
packages/queue/index.js
packages/story-group-composer/index.js

Fixes closing the composer in campaigns page, sending a param instead of the tabId.
JIRA card -> PUB-2616 …

PUB-2616  | Fix close composer in campaigns page

---

packages/composer-popover/components/ComposerWrapper/index.jsx

User's encounter an "Invalid timeslot" message when using "Share Again" from Analytics or Past Reminders when a the original update had a 'scheduled_at' or 'pinned' set.
This makes sure that pinned is 'null' from Analytics and both 'scheduled_at' and 'pinned' are null from pastReminders.
Based on this change: https://buffer.atlassian.net/browse/PUB-1709
Related to:
- https://buffer.atlassian.net/browse/PUB-2476
- https://buffer.atlassian.net/browse/PUB-2163
-   [ ] I have performed a self-review …

Fix "Invalid Timeslot" on "Share Again"

---

packages/profile-sidebar/index.js
packages/profile-sidebar/utils/index.js

Since now campaigns is another link at the same level than the rest of
social profiles, we need to take into account the case where the last
selected profile and tab are not available.
JIRA ticket: https://buffer.atlassian.net/browse/PUB-2617 …

Use default tabId when we don't have previous props

---

packages/app-pages/components/PagesWithSidebar/index.jsx
packages/campaign/components/ViewCampaign/index.jsx
packages/campaign/index.js
packages/campaign/reducer.js
packages/campaign/reducer.test.js
packages/routes/index.js
packages/routes/index.test.js

- Get single campaign page through the router change.
- Update campaign state after post pusher events only when user is in single campaign pages. …

[PUB-2570] Adapt pusher events for sent campaign

---

packages/campaign/components/ViewCampaign/index.jsx
packages/delete-campaign-modal/middleware.js
packages/profile-sidebar/index.js
packages/routes/index.js
packages/routes/index.test.js

Keep campaigns button selected in all campaigns pages
Using matchPath from react-router instead of a method just for campaigns
https://buffer.atlassian.net/browse/PUB-2642 …

[PUB-2642] Keep campaigns button selected in all campaigns pages

---

packages/campaign/components/ViewCampaign/ExamplePost/index.jsx
packages/campaign/components/ViewCampaign/ExamplePost/story.jsx
packages/campaign/components/ViewCampaign/ExamplePost/style.js
packages/campaign/components/ViewCampaign/SkeletonPosts/index.jsx
packages/campaign/components/ViewCampaign/SkeletonPosts/story.jsx
packages/campaign/components/ViewCampaign/index.jsx
packages/campaign/index.js
packages/campaign/reducer.js
packages/campaign/reducer.test.js

- Add posts skeleton
- Not load header skeleton when current campaign is still the one stored in state.
In the future we might want to make the example post just the empty state of a `<Post>`, instead of having a separated and made from scratch component, or at least move this to shared-components.
**Skeleton Posts:** 
https://share.buffer.com/o0uDrrAX
**How loading looks like in Publish:**
https://share.buffer.com/rRu688D6
-   [x] I have performed a …

[PUB-2570] Add posts skeleton

---

packages/campaign-form/middleware.js
packages/campaign-form/middleware.test.js

Fix campaign tracking events for edit and create campaign. The organizationId wasn't getting passed correctly. Added some additional tests.  
https://buffer.atlassian.net/browse/PUB-2656
To test segment events, 
- Log into segment
- Go to sources
- Click on Publish - Dev or Publish - Production (depending where you're testing)
- Click Debugger and check out event
-   [ ] I have tested my changes/additions in the latest Chrome, Firefox, and …

[PUB-2656] Fix campaign tracking for edit and create campaign

---

packages/campaign/index.js
packages/server/parsers/src/campaignParser.js
packages/server/parsers/src/postParser.js
packages/shared-components/CardHeader/index.jsx
packages/shared-components/CardHeader/story.jsx

- Add profile props to campaigns updates so `<Post>` renders with the right info.
- Replace `sent` by `isSent` in postParser, as the frontend seems to always expect isSent to display things like stats and errors.
- Add new card header variation for sent campaign posts. …

[PUB-2570] Add profile props to campaign posts

---

packages/pusher-sync/middleware.js
packages/pusher-sync/middleware.test.js

Move post pusher events to bindOrganizationEvents.
https://buffer.atlassian.net/browse/PUB-2644
-   [x] I have considered …

[PUB-2644] Move posts pusher events

---

packages/composer/composer/utils/TrackingUtils.js
packages/composer/composer/utils/WebAPIUtils.js

Add Segment tracking for when a user adds a post to a campaign.
PUB-2657
[https://share.buffer.com/v1uDoDld](https://share.buffer.com/v1uDoDld)
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc …

[PUB-2657] Tracking for Campaign Post Added

---

packages/queue/middleware.js

When post events come through Pusher we're attempting to update state that might not be defined, which is the `state.sent.byProfileId[...].total`. I added some optional chaining to default to `0` in that case.
I'm not actually sure if/where we use the total number of sent posts. 🤔  I know we use the 'pending' count in the sidebar.
-   [ ] I have commented …

Use optional chaining to avoid undefined sent counts

---

packages/campaigns-list/reducer.js

Fixes [this Bugsnag](https://app.bugsnag.com/buffer/publish-dashboard/errors/5e962bf0cf62db001777acc9?event_id=5e962bf0005993b70ec70000&i=sk&m=nw) which happens when campaigns are `null`. …

Fix spreading null campaigns

---

packages/campaign/components/ViewCampaign/Header/index.jsx
packages/campaigns-list/components/ListCampaigns/ListItem/index.jsx

Fix view campaign header state by passing the campaign directly into the button select methods
https://buffer.atlassian.net/browse/PUB-2668
It looks like the campaign state wasn't updating immediately inside the select items on getCampaign success. This caused the wrong campaign getting passed into the delete campaign modal and the wrong campaign id getting passed into the edit form (which caused the wrong campaign getting fetched in `fetchCampaign` on render.) 
The campaign state is updating immediately with the button `onClick`, so it seems to be specific to the Select component. After opening the delete modal a second time, the state is updated correctly. I took some time looking into the ui Select component, but couldn't find a simple solution. Let me know if you can think of any …

[PUB-2668] Fix view campaign header state

---

packages/hashtag-group-manager/components/HashtagGroupItem/index.jsx
packages/hashtag-group-manager/components/HashtagGroupList/index.jsx
packages/hashtag-group-manager/components/HashtagGroupManager/index.jsx
packages/hashtag-group-manager/components/HashtagGroupWrapper/index.jsx

When deleting a hashtag group in the composer, is not taking any action.
- JIRA card: PUB-2625
- The issue is related to the changes in the Select component in buffer-ui, the onClick wasn't being triggered. …

PUB-2625  | Fix delete a hashtag group

---

packages/server/parsers/src/postParser.js

Add is past reminder in post parser
When a post in sent tab is a past reminder is displaying the footer as if it were in the queue, by setting the post in the parser when is a reminder we ensure displaying the footer properly.
This is the way it's being displayed on Sent tab
This is how it looks like with isPastReminder in post parser
-   [ ] I have …

PUB-2672  | Add is past reminder in post parser

---

packages/campaign/components/ViewCampaign/EmptyState/index.jsx

Fixing campaigns empty sent post state message issue
All posts sent message was appearing in the sent tab, as it was missing a check for which tab it was presently in. …

PUB-2677 | Fixing campaigns empty sent post state message issue

---

packages/campaign/components/ViewCampaign/EmptyState/index.jsx
packages/server/formatters/src/getURL.js

Pass campaign into view report method in the scheduled empty state
https://buffer.atlassian.net/browse/PUB-2685
(we weren't passing the campaign previously, which was causing a redirect to a blank page)
Hey @hamstu I'm having trouble getting set up with analyze in production (and I've already used my free trial 😂 ). Do you mind checking if analyze.buffer.com/campaigns is a valid route?
Slack thread: https://buffer.slack.com/archives/C151RRDL1/p1587503321198300
-   [ ] I have performed a …

[PUB-2685] Pass campaign into view report method in scheduled empty state

---

packages/cta-banner/components/BillingUpgradeCTABanner/index.jsx
packages/cta-banner/components/BillingUpgradeCTABanner/story.jsx
packages/cta-banner/index.js
packages/cta-banner/index.test.js
packages/i18n/translations/en-us.json
packages/i18n/translations/es-es.json
packages/web/components/i18n/index.js

Update CTA Billing upgrade banner to use react-i18n instead of translations package.
- Removes translations and uses new react-i18n library
- Made a refactor for this component since if was a bit tricky to use and translate …

Use i18n for billing upgrade banner

---

packages/server/rpc/globalAccount/index.js

Fix issue where account is not present to get the product name.
This issue is part of #PUB-2697 and has been observed in the logs: 
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f …

Check account is present when fetching product name

---

packages/campaign/reducer.js
packages/campaign/reducer.test.js

- Update pusher event campaign updated to receive channels from response.
- Removing count from reducer when post created, updated or deleted, since new count comes from pusher event.
JIRA card -> PUB-2679
Related PR -> https://github.com/bufferapp/buffer-web/pull/17046
-   [ ] I …

PUB-2679 | Update pusher event campaign updated to receive channels

---

packages/modals/middleware.js
packages/modals/middleware.test.js

Prevent showing direct scheduling modal when completing appcues flow. …

PUB-2691  | Prevent showing direct scheduling modal when completing appcues flow

---

packages/composer/composer/utils/WebAPIUtils.js

Removing post created event from being sent from the front-end …

Removing post created event from being sent from the front-end

---

packages/composer/composer/utils/TrackingUtils.js
packages/composer/composer/utils/WebAPIUtils.js

Cleanup files left from segment event tracking removal when updates are created …

Removing leftovers from removal of segment metadata event work

---

packages/thirdParty/middleware.js
packages/thirdParty/middleware.test.js

Add appcues for legacy awesome to pro (batch 2) and small business migrated users
https://buffer.atlassian.net/browse/PUB-2701
@hamstu This is the first time I've added appcues logic. Let me know if I missed something! …

[PUB-2701] Add appcues for legacy awesome migrated users

---

packages/server/lib/embeds/bufferData.js

Reverts bufferapp/buffer-publish#1394
caching issue is fixed by preventing cloudflare caching on publish.buffer.com

Revert "PUB-2743 | Removing user data from server generated response"

---

package.json
packages/campaign-form/components/CampaignForm/index.jsx
packages/campaign-form/index.test.js
yarn.lock

- Fix bug: users without the campaign feature flip are able to view the campaign form and make changes.
- Small refactor in the test to remove redundant tests.
JIRA card -> PUB-2727 …

PUB-2727  | Fix for users accessing campaign form without feature flip

---

packages/queue/components/QueueItems/index.jsx
packages/shared-components/CardFooter/index.jsx
packages/shared-components/Post/index.jsx
packages/shared-components/PostFooter/index.jsx

Since the behavior of editing a native retweet without a custom comment is to copy the content of the RT to the composer, this change disables that action to fix the issue.
Fix https://buffer.atlassian.net/browse/PUB-1217 …

Remove Edit button from RTs without comments

---

packages/server/rpc/composerApiProxy/index.js
packages/server/rpc/composerApiProxy/utils/sanitize.js
packages/server/rpc/composerApiProxy/utils/sanitize.test.js

https://buffer.atlassian.net/browse/PUB-2785
Sanitize the api url to end with a slash and the url param to start without a slash
Hey @karelm let me know if there's anything I misunderstood, as there were several comments in the jira.  😄  …

[PUB-2785] Sanitize composerApiProxy urls to prevent ssrf

---

packages/modals/components/AppModals/index.jsx
packages/queue/middleware.js

Currently, when switching profiles, a brief dark gray overlay shows in the queue. This was happening because we were making a request to `checkInstagramBusiness` for every profile switch that wasn't IG business. While we were waiting for success, the overlay would display. 
Since we are no longer auto-opening the modal [[PR](https://github.com/bufferapp/buffer-publish/pull/1366/files)], we should only call this request in the direct modal flow when we check whether a user has [converted to business](https://share.getcloudapp.com/v1ue6R7n) and when we first open the direct modal from the banner.
Also, it looks like [an error was displaying](https://share.getcloudapp.com/yAuYPvO5) in the flow once a user converted their profile to business. Added a fix for it. …

[PUB-2816] Remove gray overloading when switching profiles

---

packages/credit-card-form/components/CreditCardForm/form.jsx
packages/credit-card-form/components/CreditCardForm/styles.js
packages/plans/components/PlanColumnWithPremiumSolo/index.jsx
packages/tabs/components/TabNavigation/index.jsx

I noticed today that there were some button style regressions with the upgrade & payday page buttons. It looks like they were caused a few weeks ago by a change to the ui library button (it added a div wrapper to the button component). This change caused certain styles to no longer work. 
**Before** https://share.getcloudapp.com/d5uWrKNB
**After**: https://share.getcloudapp.com/DOuAXOrx
-   [ ] I have tested my changes/additions in the …

Fix payday and upgrade button regressions

---

packages/bootstrap/middleware.js
packages/profile-sidebar/reducer.js
packages/profile-sidebar/reducer.test.js
packages/profile-sidebar/utils/index.js
packages/profile-sidebar/utils/index.test.js

Add feature flip to filter profiles so we can later test this in production without changing the code.
Part of the org. switcher project.
-   [x] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c7 …

Add feature flip to filter profiles by organization

---

packages/server/parsers/src/userParser.js
packages/temporary-banner/components/TemporaryDashboardBanner/index.jsx
packages/temporary-banner/index.js

Add an in-app alert to let customers know we're retiring social login on June 30th. 
https://buffer.atlassian.net/browse/PUB-2824
Currently using the `has_password` field on the user model to understand whether a user has set a password. 
@philippemiguet do you know if this is the best way to tell whether a user is solely using social login and hasn't set a pw yet?  
https://share.getcloudapp.com/bLujpPoy
-   [ ] I have tested my …

[PUB-2824] Display retiring social login banner if user pw has not been set

---

packages/temporary-banner/components/TemporaryDashboardBanner/index.jsx

After chatting with Colleen on Core, I don't think the `has_password` field is always accurate as the core and publish db are not in sync. Commenting this out for now while I look more into it.  
Slack thread for context: https://buffer.slack.com/archives/C151RRDL1/p1591980767408700 …

Temporarily remove social deprecation banner

---

packages/temporary-banner/components/TemporaryDashboardBanner/index.jsx

Currently, there isn't a way to find out whether a user has set a password, as the Core db and Publish db is out of sync. 
Instead of changing the Core API, we will show the banner based off the `has_password` field with the knowledge that it may be out of date for social login users who have set their password since we've been using the Core password form. We'll remove the banner on June 30th. 
-   [ ] I have tested my changes/additions in …

[PUB-2824] Re-deploy the social login deprecation banner

---

cypress/e2e/publish.js
cypress/support/commands.js
cypress/support/index.js
cypress/support/login.js
package.json
yarn.lock

Add an await for auth in e2e test before clicking in the composer button.
- Added Testing Library Cypress plugin
- Included a `wait` for `/pusher/auth` to make sure the page is loaded before clicking on the composer button
The main reason why I added the Testing Library Cypress plugin, is because it makes it a lot easier to query elements in the DOM without the need to add additional tags in the elements we need to test (`data-cy`), and as we get more familiar with the queries from React Testing Library, we'll be able to easily use the same queries for our e2e tests without having to switch too much context.
-   [ ] I have …

e2e | Add an await for auth in e2e test

---

packages/general-settings/components/GeneralSettings/index.jsx
packages/general-settings/components/GoogleAnalytics/index.jsx
packages/general-settings/index.js
packages/general-settings/reducer.js
packages/general-settings/reducer.test.js

This change adds a note to the Campaign Tracking section notifying users that they must enable a link shortener before they enable Campaign tracking.
PUB-1179
[https://share.buffer.com/JruLDPpB](https://share.buffer.com/JruLDPpB)
-   [ ] I kept accessibility in mind by following the …

[PUB-1179] Error for campaign tracking with no link shortener

---

packages/temporary-banner/components/TemporaryDashboardBanner/index.jsx

- Change the social login retirement banner date to July 7 (it's recently been pushed back)
- Change the color theme to blue
https://buffer.atlassian.net/browse/PUB-2881
Screenshot: https://share.buffer.com/rRul1GEB …

[PUB-2881] Change date and color to social login retirement banner

---

packages/campaigns-list/middleware.js
packages/campaigns-list/middleware.test.js
packages/server/rpc/campaigns/getCampaignsList/index.js
packages/server/rpc/campaigns/getCampaignsList/index.test.js

Only allow a user to see the campaigns related to their global org id. 
https://buffer.atlassian.net/browse/PUB-2775
Originally, the intent was to create a new campaigns endpoint that filtered by publish org id instead of global org id. However, when working on the endpoint, I realized that since we're only storing the globalId for campaigns, it would be difficult to try to filter it by publish org id.
I instead decided to grab the global org id from the current organization in the front end, and pass it to the backend as a param. Now it should filter based on the global org id that's associated with the current publish organization selected.  
https://share.buffer.com/KouB1qBB
-   [x] I have added tests to cover my …

[PUB-2775] Fetch campaigns related to their current global org id

---

packages/profile-sidebar/components/ProfileSidebar/index.jsx
packages/profile-sidebar/index.js

Hide Profile Sidebar Social Account Shortcuts for users who are not org admin.
https://buffer.atlassian.net/browse/PUB-2805
-   [ …

[PUB-2805] Hide social shortcuts for non admin users

---

packages/composer/composer/components/ProfileSection.jsx

- Disable Posting Groups functionality for users without any posting groups
https://buffer.atlassian.net/browse/PUB-2879
After this PR: user with > 9 social accounts and no posting groups doesn't see the option:
Before this PR: user with > 9 social accounts and no posting groups sees the option:
Remains the same: user with > 9 social accounts and with posting groups sees the option. Users with <9 social accounts don't see the option.
-   [ ] …

[PUB-2879] Disable Posting Groups functionality for users without any posting groups

---

packages/server/parsers/src/userParser.js
packages/temporary-banner/components/TemporaryDashboardBanner/index.jsx
packages/temporary-banner/index.js

Social sign in will be deprecated on June 30th. Please do not deploy until June 30th.
PUB-2832 …

[PUB-2832] Remove Social Sign-in Deprecation Banner [DO NOT DEPLOY UNTIL JUNE 30]

---

packages/shared-components/QueueItems/styles.js

Fix long update in the queue of being overlapped by the time slots.
https://buffer.atlassian.net/browse/PUB-2878
Issue: https://share.buffer.com/12uNgeoR
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb79 …

[PUB-2878] Fix queue overlap when post is larger than 100vh

---

packages/profile-page/index.js

The publish page is crashing after a user goes to a non-profile page, then goes to profiles-page and hits back button. 
https://buffer.atlassian.net/browse/PUB-2872
I've currently added a change to handle this error, as the value where it's crashing in `profile-page` is related to the Load More logic, which doesn't apply to non-profile pages. 
The bigger issue with this bug is around how in the `AppPages` router component, we're meeting the conditions and hitting the ProfilePages logic before we're hitting the non-profiles route logic (campaigns, preferences etc) when we hit the back button. This is partly because the router `location` prop isn't updating correctly and still has the previous pathname.  **This bug is unrelated to the org-switcher and is more of an issue with our router …

[PUB-2872] Fix page crashing on back button to non-profile page

---

packages/analytics/index.js
packages/app-shell/index.js
packages/app-shell/reducer.js
packages/app-shell/reducer.test.js
packages/cta-banner/index.js
packages/cta-banner/index.test.js
packages/cta-banner/reducer.js
packages/cta-banner/reducer.test.js
packages/drafts/index.js
packages/drafts/reducer.js
packages/ig-first-comment-pro-trial-modal/middleware.js
packages/posting-schedule/index.js
packages/posting-schedule/index.test.jsx
packages/posting-schedule/reducer.js
packages/user/reducer.js

When the user data is only used in the UI component, I've stopped storing it in the component state and used state.user instead.
- Replace user data in app-shell
- Replace user data in cta-banner
- Replace user data in drafts
- Replace user data in ig-first-comment-pro-modal
- Add case to user reducer, to update user state when `user_${dataFetchActionTypes.FETCH_SUCCESS}` 
https://buffer.atlassian.net/browse/PUB-2895
-   [ ] I have tested my …

[PUB-2895] Replace user data

---

packages/app-shell/index.js
packages/composer/composer/utils/DataImportUtils.js
packages/composer/interfaces/buffer-publish.jsx
packages/cta-banner/middleware.js
packages/grid/index.test.jsx
packages/product-features/reducer.js
packages/product-features/reducer.test.js
packages/profile-sidebar/reducer.js
packages/profile-sidebar/reducer.test.js
packages/queue/middleware.test.js
packages/server/parsers/src/userParser.js
packages/server/rpc/preferences/changeDateTimePreferences/test.js
packages/stories/middleware.test.js
packages/tabs/index.js
packages/test/generate-data/index.js
packages/thirdParty/middleware.js
packages/thirdParty/middleware.test.js

- Use user data in product-features package
- Get user plan with userData.billing_plan_tier
- Get user planBase with userData.billing_plan_base
Extra:
- Replace `is_free_user` references by `isFreeUser`
- Replace `is_business_user` references by `isBusinessUser`
https://buffer.atlassian.net/browse/PUB-2905
The goal is to deprecate the features endpoint in a future task and get all the plans data from the same place.
After the org switcher rollout we plan on moving features to the backend, so we no longer need business logic props related to plans like isFreeUser, isProUser and isBusinessUser
-   [x] I have tested different user …

[PUB-2905] Use user data in product features

---

packages/server/parsers/src/userParser.js

- There was one case where userData.plan wasn't the same as userData.billing_plan_tier, which is in the pro plans.
The places where we check plan ==='pro' wouldn't work. I added this small tweak to make it work, once we are done with this tasks and proceed to move the business logic from the frontend this will be gone …

Fix temporary edge case

---

packages/app-pages/index.js
packages/campaign-form/index.js
packages/campaign-form/index.test.js
packages/campaign/index.js
packages/campaigns-list/index.js
packages/campaigns-list/middleware.js
packages/campaigns-list/middleware.test.js
packages/composer/composer/utils/DataImportUtils.js
packages/drafts/index.js
packages/profile-sidebar/index.js
packages/queue/index.js
packages/sent/index.js
packages/server/parsers/src/userParser.js
packages/test/generate-data/index.js

- Move campaigns and first comment feature references to parser
Since they are both for isProOrBusinessOrEnterpriseUserOrTeamMember, with the org switcher we'll need to override the team member option, and adjust the features to be displayed only for pro and up orgs
-   [ ] I kept …

Move user features to parser

---

packages/app-pages/index.test.js

Fixes a small problem with the App Pages integration tests.
While running the tests locally I noticed there is an error, even though the tests aren't broken, there is a reducer (general-settings) that keeps on failing because is missing the mocked response.
**This is the error thrown**
**This is where it's happening**
**This is where we call the endpoint** …

Fix missing endpoint mock in AppPages test

---

packages/composer/composer/components/App.jsx
packages/composer/composer/components/AppStateless.jsx
packages/composer/composer/components/Composer.jsx
packages/composer/composer/components/ComposerSection.jsx
packages/composer/composer/stores/AppStore.js
packages/composer/composer/utils/DataImportUtils.js
packages/composer/interfaces/buffer-publish.jsx
packages/server/parsers/src/userParser.js
packages/server/rpc/user/index.js
packages/test/generate-data/index.js

Inject orgs data in hasUserTag feature
So far we've been checking if we display certain features based on pro or up and if user is team member. With the org switcher we will no longer care about team members, just the org plan.
https://buffer.atlassian.net/browse/PUB-2904
-   [ ] I …

[PUB-2904] Inject orgs data

---

packages/default-page/index.js
packages/default-page/index.test.js
packages/profile-sidebar/reducer.js
packages/profile-sidebar/reducer.test.js

- Fix bug for the org switcher. When we have the org switcher, we are getting the features from the selected org owner. 
However, rollout features should belong to the user only.
https://buffer.atlassian.net/browse/PUB-2947 …

[PUB-2947] Fix org switcher bug

---

packages/drafts/components/DraftList/index.jsx
packages/drafts/index.js
packages/drafts/reducer.js
packages/drafts/reducer.test.js
packages/queue/components/QueuedPosts/index.jsx
packages/queue/index.js
packages/queue/reducer.js
packages/queue/reducer.test.js

- Fix filtered profiles in composer
We have a preserveStateOnClose when we open the composer in the queue or drafts. It prevents from re-rendering data again. When we switched orgs, the list of profiles changed, but that logic was blocking us from updating the data accordingly. 
_I guess at some point we should thing about the preserveStateOnClose again. I could see why we would want to preserve the composer message so we open the composer again and it's there. But I don't see why we don't update user and profiles info, this means that without a page refresh, the data in the composer might not be up to date_
https://buffer.atlassian.net/browse/PUB-2953
-   [x] All new …

[PUB-2953] Fix filtered profiles in composer for org switcher

---

packages/app-shell/components/AppShell/index.jsx
packages/app-shell/index.js
packages/server/parsers/src/userParser.js
packages/server/rpc/user/index.js
packages/thirdParty/middleware.js

- Add `canSeeOrgSwitcher` flag for AppCues
- Simplify org switcher display logic in AppShell by using canSeeOrgSwitcher
https://buffer.atlassian.net/browse/PUB-2936 …

[PUB-2936]Task/add org switcher appcues

---

packages/i18n/translations/en-us.json
packages/profiles-disconnected-banner/components/ProfilesDisconnectedBanner/index.jsx
packages/profiles-disconnected-banner/components/ProfilesDisconnectedBanner/story.jsx
packages/profiles-disconnected-banner/index.js
packages/profiles-disconnected-banner/index.test.jsx
packages/server/formatters/src/getURL.js
packages/server/parsers/src/userParser.js
packages/server/rpc/user/index.js
packages/tabs/components/TabNavigation/index.jsx
packages/tabs/index.js

- Hide reconnect button in settings tab for non-admin users
- Show custom message in profiles-disconnected-banner for non-admin users
Extra: use new translations in profiles-disconnected-banner
https://buffer.atlassian.net/browse/PUB-2968
Next: Adjust the profiles-disconnected-modal
**Non admin user:**
**Admin user:**  …

[PUB-2968] Hide reconnect channels for non-admin users

---

packages/profiles-disconnected-modal/components/ProfilesDisconnectedModal/index.jsx
packages/profiles-disconnected-modal/components/ProfilesDisconnectedModal/story.jsx
packages/profiles-disconnected-modal/index.js

- Replace reconnect cta for non-admin users in profiles-disconnected-modal
Extra: Use new translations 
https://buffer.atlassian.net/browse/PUB-2968
**Admin user in disconnected profile:**
**Non-admin in disconnected profile:**
-   [ ] I kept accessibility in mind by following the …

[PUB-2968] Replace reconnect cta for non-admin users in profiles-disconnected-modal

---

packages/profiles-disconnected-modal/components/ProfilesDisconnectedModal/index.jsx

- Fix disconnect modal reconnect button: users without the org switcher flip weren't seen the right option
-   [ ] I have …

Fix disconnect modal reconnect button for non org switcher users

---

helm/buffer-publish.yaml

Upgraded the chart `buffer-service` used by `buffer-publish` from version 1.0.3 to 1.1.1

Upgrading buffer-publish chart to 1.1.1

---

packages/campaigns-list/components/ListCampaigns/EmptyState/index.jsx
packages/campaigns-list/components/ListCampaigns/EmptyState/story.jsx
packages/campaigns-list/components/ListCampaigns/index.jsx
packages/campaigns-list/index.js
packages/i18n/translations/en-us.json

- Add empty campaigns state for non-admin users, as they can't create campaigns.
https://buffer.atlassian.net/browse/PUB-2976
- …

[PUB-2976] Add empty state variation for non admin

---

packages/initial-loading/reducer.js
packages/server/parsers/src/userParser.js

- We were taking the beta redirect features from the owner of the org, so if the owner was in Classic the team members couldn't access Publish
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc1 …

Fix redirect

---

packages/analytics/components/Analytics/index.jsx
packages/analytics/components/AnalyticsList/index.jsx
packages/analytics/index.js
packages/app-pages/index.test.js
packages/past-reminders/components/PastRemindersPosts/index.jsx
packages/past-reminders/index.js
packages/queue/components/QueuedPosts/index.jsx
packages/queue/index.js
packages/queue/index.test.js
packages/sent/components/SentPosts/index.jsx
packages/sent/index.js
packages/server/parsers/src/orgParser.js
packages/shared-components/BitlyClickNotification/index.jsx
packages/shared-components/QueueItems/PostContent/index.jsx
packages/shared-components/QueueItems/index.jsx
packages/shared-components/QueueItems/styles.js

Replace features.isFreeUser() and features.isProUser() by orgs features
- `hasAnalyticsFeature: orgData.planBase === 'business',`
- `hasBitlyFeature: orgData.planBase !== 'free',`
- `has30DaySentPostsLimitFeature: orgData.planBase === 'free',`
- `hasCalendarFeature: orgData.planBase !== 'free',`
- `hasShareAgainFeature: orgData.planBase !== 'free',`
Delete unused  ShowMorePosts
https://buffer.atlassian.net/browse/PUB-2993
-   [ ] I have …

[PUB-2993] Replace features.isFreeUser() and features.isProUser() by orgs features

---

packages/temporary-banner/components/TemporaryDashboardBanner/index.jsx
packages/temporary-banner/components/TemporaryDashboardBanner/story.jsx
packages/temporary-banner/index.js

Add temporary banner for retiring IG personal profiles
https://buffer.atlassian.net/browse/PUB-3043
The copy will likely change, waiting to hear back from Mike E.
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e …

[PUB-3043] Add temporary banner for retiring IG personal profiles

---

packages/grid/components/GridPosts/story.jsx
packages/locked-profile-notification/components/LockedProfileNotification/index.jsx
packages/locked-profile-notification/components/LockedProfileNotification/story.jsx
packages/locked-profile-notification/index.js
packages/locked-profile-notification/index.test.jsx
packages/profile-sidebar/components/ProfileConnectShortcut/index.jsx
packages/profile-sidebar/components/ProfileSidebar/index.jsx
packages/profile-sidebar/index.js
packages/queue/middleware.test.js
packages/server/parsers/src/orgParser.js
packages/server/rpc/preferences/changeDateTimePreferences/test.js
packages/stories/middleware.js
packages/stories/middleware.test.js
packages/thirdParty/middleware.js
packages/thirdParty/middleware.test.js

Replace features.isFreeUser() and features.isProUser() by orgs features
https://buffer.atlassian.net/browse/PUB-2993
-   [ ] I …

[PUB-2993] Replace features.isFreeUser() by org features

---

packages/profile-sidebar/components/ProfileSidebar/index.jsx
packages/profile-sidebar/index.js
packages/server/parsers/src/userParser.js

Currently, there is no way for users to connect new personal instagram profiles. However, as we're still supporting old personal ig profiles, advocates would like a way to connect personal profiles for debugging purposes. We're only displaying personal ig connect button if the `is_admin` field on the user object is true. 
"The user collection in mongo has a role field which can be set to admin or customer or possibly affiliate." - Mick
-   [ …

Add temporary way for buffer admin to connect personal ig profile

---

packages/composer-popover/components/ComposerWrapper/index.jsx
packages/composer/composer/AppConstants.js
packages/composer/composer/action-creators/AppActionCreators.js
packages/composer/composer/action-creators/AppInitActionCreators.js
packages/composer/composer/components/App.jsx
packages/composer/composer/components/AppStateless.jsx
packages/composer/composer/components/ComposerSection.jsx
packages/composer/composer/stores/AppStore.js
packages/composer/composer/tests/action-creators/AppActionCreators.test.js
packages/composer/interfaces/buffer-publish.jsx
packages/server/parsers/src/orgParser.js

- Add orgs data to composer
- Grab orgs data instead of user data in composer queue limit error
- Add plan and role features data to org parser
Next: Replace user references (isBusinessUser, features) by orgs data in the composer
https://buffer.atlassian.net/browse/PUB-2998
-   [ ] …

[PUB-2998] Add orgs data to composer

---

packages/plans/components/Plans/index.jsx
packages/plans/index.js
packages/server/parsers/src/userParser.js
packages/server/rpc/user/index.js
packages/thirdParty/middleware.js

- Replace plan === 'pro' references by planBase
I've made sure the single source of truth for the planName (the org) is storing the same values as the API. However, on the AppCues and the plans page, I'm still overriding that value, as 1) the plans page is eventually gonna disappear, 2) changing the appCues would require Mike E to change the conditions set in the platform.
We have 2 different fields for plans names:
`billing_plan_tier` is the name of plan (free, pro8, pro15, solo_premium_business, premium_business)
`billing_plan_base` is the group of the plan (free, pro, business
Currently we store the billing_plan_tier in plan and billing_plan_base in planBase, but our frontend expects plan to be a mix between both.
https://buffer.atlassian.net/browse/PUB-2990
-   [x] My code follows the …

[PUB-2990] Replace plan === 'pro' references by planBase

---

packages/app-pages/index.test.js
packages/campaign/components/ViewCampaign/index.jsx
packages/campaign/components/ViewCampaign/story.jsx
packages/campaign/index.js
packages/campaign/index.test.js
packages/campaigns-list/components/ListCampaigns/index.jsx
packages/campaigns-list/index.js
packages/campaigns-list/middleware.js
packages/campaigns-list/middleware.test.js
packages/campaigns-list/reducer.js
packages/campaigns-list/reducer.test.js
packages/past-reminders/components/PastRemindersPosts/index.jsx
packages/past-reminders/components/PastRemindersPosts/story.jsx
packages/past-reminders/index.js
packages/queue/components/QueuedPosts/index.jsx
packages/queue/components/QueuedPosts/story.jsx
packages/queue/index.js
packages/queue/index.test.js
packages/sent/components/SentPosts/index.jsx
packages/sent/components/SentPosts/story.jsx
packages/sent/index.js

- Remove fetchCampaignsIfNeeded, only being used by people without the org switcher feature flip
https://buffer.atlassian.net/browse/PUB-2918
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16 …

[PUB-2918] Remove fetchCampaignsIfNeeded

---

packages/app-shell/index.js
packages/organizations/reducer.js
packages/sent/index.js
packages/server/parsers/src/orgParser.js
packages/thirdParty/middleware.js

- Move analyzeCrossSale and canSeeOrgSwitcher
- Add isOwner prop to trial expired modals
https://buffer.atlassian.net/browse/PUB-3007
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e57 …

[PUB-3007] Move org roles dependable props

---

packages/shared-components/GridList/index.jsx

The images in the `Shop Grid` tab in Publish are positioned "top", but that's not how it's going to be cropped in the Grid. This is a small tweak to make sure we are showing the images as they're going to display later on 😄 
I think that for accessibility purposes we could do better by turning these into image tags and allowing alt text: this might be something to consider 🤔 
Before / after:
-   [x] I have tested my changes/additions in the …

Center images on Shop Grid preview

---

packages/profile-sidebar/index.js
packages/server/parsers/src/orgParser.js
packages/server/parsers/src/userParser.js

The user endpoint `is_admin` is for Buffer Admin. The org endpoint is for admin users within the organization. Currently, organization admin users are able to see the connect ig personal profile button.
https://buffer.slack.com/archives/C151RRDL1/p1601889480136700
This will be a good one to rename to something like "isBufferOrgAdmin" in the endpoint. This value is being used in many places (global admin, etc) so will need to coordinate if we refactor. 
-   [ ] I have performed a self-review of …

Only show the connect ig personal profile button for buffer admins

---

packages/composer/composer/components/LocationComposerBar.jsx

- Remove check from location checkbox when there are no IG profiles with FB accounts w/ location associated
-   [ ] I have …

Remove check from IG location checkbox when no profiles with FB accounts w/ location associated

---

packages/shared-components/QueueItems/Header/index.jsx

- Fix condition so calendar buttons render independently from the timezone …

Fix calendar buttons condition

---

packages/account-notifications/components/Notifications/index.jsx
packages/account-notifications/index.js
packages/account-notifications/reducer.js
packages/i18n/translations/en-us.json
packages/server/parsers/src/userParser.js

The purpose of this change is to add an additional setting for post failed notifications.
This will also require [buffer-web changes](https://github.com/bufferapp/buffer-web/pull/17332#issue-511746402) to be deployed before this can be merged.
PUB-3061
https://share.buffer.com/Wnur8jqD
-   [ ] I have commented my code, particularly in hard-to-understand …

[PUB-3061] Add notification setting for post failures

---

.github/workflows/lighthouse.yml

Depfu is a bot that automatically makes PRs for updating dependencies. It does not trigger a staging build (at least not right now, that might be worth trying in the future though). But since it never triggers a staging build that ALSO means Lighthouse CI hangs for several hours waiting for the site to be deployed, until it finally times out. (You'll see this error in the checks section of all the previous Depfu PRs)
This PR fixes that by disabling the Lighthouse run for depfu tagged PRs.
-   [ …

Don't run Lighthouse CI on Depfu PRs

---

packages/analytics-middleware/middleware.js
packages/analytics-middleware/middleware.test.js

This change is to add the user's global organization ID to all events tracked in our Segment tracking plan.
PUB-3118
-   [ ] I …

[PUB-3118] Add org id to all tracked events

---

packages/globalAccount/middleware.js
packages/organizations/middleware.js

A quick change that removes publishOrganizationSwitchedTo and publishOrganizationSwitchedFrom and replaces them with 'previousOrganizationId' as requested by the data team.
PUB-3118 …

[PUB-3118] Adjust previous org values for org tracking

---

packages/engagement-promo-modal/components/EngagementPromoModal/index.jsx

- Add close button to modal, so users can dismiss it when for some reason they can't see the "Dismiss" button.
- 
Some users with zoom > 100% are complaining they can't see the dismiss button. We are adding a quick fix with a close button here so they can dismiss the modal. However, I'm opening an issue to investigate the real problem: how can users with zoom > 100% get access to our modals entirely.
-   [ ] I have tested my …

Add close button to Engage Promo Modal

---

packages/composer/composer/utils/WebAPIUtils.js

Should fix up https://buffer.atlassian.net/browse/PUB-3237 by using the new topics array instead of hashtags which is now empty.
https://buffer.atlassian.net/browse/PUB-3237
https://share.buffer.com/xQuYGnPm …

Fix Twitter Hashtag Autocomplete in Composer

---

packages/onboarding/components/OnboardingPage/index.jsx
packages/onboarding/components/OnboardingPage/style.js

- Remove deprecated `Button type="link"`
The deprecated component will be deleted in a new major version soon.
-   [ ] I have …

Deprecate BDS button link

---

packages/campaign/components/ViewCampaign/index.jsx
packages/campaign/index.js
packages/campaign/reducer.js

When we opened up the share again logic to all users, we removed code that caused the share again button to show on campaigns/sent tab without the onClick logic. We likely want the share again logic in the sent tab for campaigns, so I added the onClick logic for it. 
Related: https://buffer.slack.com/archives/CHN88PG2J/p1612961166098000
-   [ ] I have …

Add share again logic to campaigns

---

packages/server/formatters/entitlements.js
packages/server/formatters/index.js
packages/server/parsers/index.js
packages/server/parsers/orgParser.js

Add a constant file with entitlements and replace campaigns plan check with entitlement coming from the backend.
PUB-3407: We are accessing the features/entitlements from the backend, so we are replacing the `orgParser` from plan checks to entitlements that come from the API, for now, we are just testing with campaigns.
The e2e tests are failing because we haven't deployed the changes in the backend, as soon as those are merged, the tests should no longer fail.
-   [ ] I have performed a …

PUB-3407 | Add entitlements in orgParser for campaigns

---

packages/composer/composer/components/Editor.jsx
packages/composer/composer/components/SourceUrl.jsx
packages/composer/composer/lib/validation/ValidateDraft.js
packages/composer/composer/stores/ComposerStore.js
packages/composer/composer/tests/lib/validation/ValidateDraft.test.js
packages/composer/composer/utils/StringUtils.js
packages/composer/composer/utils/WebAPIUtils.js

- Undo https://github.com/bufferapp/buffer-publish/pull/1619, that automatically picks the first link as the source url when Pinterest posts have links.
- Make source field mandatory for Pinterest when there are links in the post.
- Since Pinterest marks most url shorteners as spam, block users from inserting buff.ly and bit.ly source urls.
- **NEW:** Unshorten Pinterest links when moving from omni to individual composer
Pinterest blocks most url shorteners. Our Pinterest profiles don't have the option to select link shorteners in their settings. If users are composing to multiple profiles at the same time, and one of them has link shortening available, all the profiles including Pinterest will get it in the frontend - we then remove the link shortener for Pinterest in the backend. …

[PUB-3167] Add validation to Pinterest source url

---

packages/ig-first-comment-modal/components/InstagramFirstCommentModal/index.jsx

To redirect shared channels users that need to fix their comment permissions to https://account.buffer.com/channels when they see this modal:
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16 …

Fix redirect to shared channels page on InstagramFirstCommentModal

---

helm/buffer-publish.dev.yaml

This PR aims to maintain the consistency of using the same staging DB for dev services, across dev-api, core-auth-dev.
The change switch the publish dev environments to use core-dev instead of core production.
https://threads.com/34394333229 …

Use the core-auth svc from dev instead of production

---

packages/server/parsers/orgParser.js

If the organization is One Buffer, hide the link to the billing section. 
If, for some reason or because it's linked somewhere else on the Internet, the user ends up in the classic billing page, we have another PR for that in buffer-web: https://github.com/bufferapp/buffer-web/pull/17564. 
https://buffer.atlassian.net/browse/PUB-3233
-   [ ] I have …

Disable Billing link if organization is One Buffer

---

packages/server/index.js
packages/server/lib/rpcErrorMiddleware.js

Adds the stacktrace to unhandled RPC errors when running locally so we don't have to wonder what parser is failing. 😄 
-   [ ] I …

Better RPC errors locally
